kiegroup/jbpm

jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/correlation/JPACorrelationKeyFactory.java

I was writing some tests for correlation keys when I realized it is not so easy to find out that you are accidently passing an empty business key to your correlation key instance. I was getting exceptions like this:
java.lang.NullPointerException: null
at java.util.ArrayList.<init>(ArrayList.java:164)
at org.jbpm.persistence.correlation.CorrelationKeyInfo.getProperties(CorrelationKeyInfo.java:61)
at org.jbpm.persistence.JpaProcessPersistenceContext.getProcessInstanceByCorrelationKey(JpaProcessPersistenceContext.java:122)
at org.jbpm.persistence.processinstance.JPAProcessInstanceManager.getProcessInstance(JPAProcessInstanceManager.java:208)
at org.jbpm.process.instance.ProcessRuntimeImpl.getProcessInstance(ProcessRuntimeImpl.java:238)
at …

Do not allow to create correlation key with empty content

---

jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/pom.xml

jbpm-executor-ejb references jbpm-services as it's parent, skipping one level in the hierarchy. This pull request fixes that.
(Discovered this due to master not building for me on my local machine.)

Fix parent for jbpm-executor-ejb

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java

When you use PerProcessInstance with CorrelationKeyContext, you will get a WARN message.
For example,
$ mvn test -Dtest=PerProcessInstanceRuntimeManagerTest#testCreationOfSessionWithPersistenceByCorrelationKey
...
2015-06-22 14:28:49,730 [main] [org.jbpm.runtime.manager.impl.PerProcessInstanceRuntimeManager] WARN  ProcessInstanceIdContext shall be used when interacting with PerProcessInstance runtime manager
I think CorrelationKeyContext is also acceptable so sending this PR.

Suppress WARN when PerProcessInstance + CorrelationKeyContext

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ProcessFactoryTest.java
jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/CompositeNodeFactory.java

Added name() method to CompositeNodeFactory.

JBPM-4691 name() for fluent API CompositeNode is missing

---

jbpm-test-coverage/pom.xml
pom.xml

* the tests are only compiled during the standard build. This
is to make sure that compilation failures are detected as
early as possible.
* the tests can be executed using "-Pintegration-tests" or
"-Dintegration-tests"
@livthomas please let me know if you have some concerns about this.

[JBPM-4653] run jbpm-test-coverage tests in specific profile

---

jbpm-bpmn2-emfextmodel/pom.xml

* these are additional EMF tags not recognized by javadoc tool (by default)

bpmn2-emfextmodel: configure custom javadoc tags to fix warnings

---

jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/DBUserGroupCallbackImplTest.java
jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/util/PersistenceUtil.java

Added support for com.edb.Driver class to data source properties handling.
Please if it's possible, merge it also to 6.3.x and 6.2.x branch. Without this we cannot execute community tests on Postgres Plus.

JBPM-4749 Persistence tests don't support Postgres Plus

---

jbpm-test-coverage/src/main/java/org/jbpm/test/casemgmt/WorkCaseService.java

Hello,
when looking through the case-mgmt test coverage I have found a small issue. Since nextInt(n) picks number from 0 (inclusive) to n (exclusive), -1 was not supposed to be there (the very last user would not be picked).
Marian

Fix random user generation in case-mgmt test coverage

---

jbpm-audit/pom.xml
jbpm-bpmn2-emfextmodel/pom.xml
jbpm-bpmn2/pom.xml
jbpm-flow-builder/pom.xml
jbpm-flow/pom.xml
jbpm-human-task/jbpm-human-task-audit/pom.xml
jbpm-human-task/jbpm-human-task-core/pom.xml
jbpm-human-task/jbpm-human-task-jpa/pom.xml
jbpm-human-task/jbpm-human-task-workitems/pom.xml
jbpm-persistence-jpa/pom.xml
jbpm-query-jpa/pom.xml
jbpm-runtime-manager/pom.xml
jbpm-services/jbpm-kie-services/pom.xml
jbpm-services/jbpm-services-api/pom.xml
jbpm-services/jbpm-shared-services/pom.xml

Depends on:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/183

[DROOLS-1129] consistent OSGi Bundle-SymbolicName for all jars

---

jbpm-workitems/pom.xml
jbpm-workitems/src/test/java/org/jbpm/process/workitem/rest/BasicAuthRestWorkItemHandlerTest.java
jbpm-workitems/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java

* RequestHandler was removed in CXF 3.x and needs to be replaced
by ContainerRequestFilter
* see http://cxf.apache.org/docs/30-migration-guide.html
for additional info
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/201.
@mrietveld / @mswiderski  could you please take a look?

jbpm-workitems: fixes after CXF 2.x -> CXF 3.x upgrade

---

jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/util/PersistenceUtil.java

- Added com.edb driver handling to PersistenceUtil.useTransactions() method.

JBPM-5116 Persistence tests doesn't use transactions for handling LOBs in Postgresql Plus

---

jbpm-installer/build.for.eclipse.luna.xml
jbpm-installer/build.xml
jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/src/test/resources/arquillian.xml
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/test/resources/arquillian.xml
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/test/resources/arquillian.xml
pom.xml

* deprecated in JDK 8 (e.g. has no effect) and
removed in JDK 9 (build fails)

Remove no longer needed -XX:MaxPermSize configs

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/AbstractLDAPUserGroupInfo.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/LDAPUserGroupCallbackImpl.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/LDAPUserInfoImpl.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/utils/LdapSearcher.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/LDAPBaseTest.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/LDAPUserGroupCallbackImplTest.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/LDAPUserInfoImplTest.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/utils/LdapSearcherTest.java

Both LDAPUserGroupCallbackImpl and LDAPUserInfoImpl classes contained very long methods with many code duplicates which made it really hard to understand how exactly they worked.
I have refactored them and extracted the logic dealing directly with LDAP to LdapSearcher class as well as their common setup to AbstractLDAPUserGroupInfo. I have not changed the behavior of LDAPUserGroupCallbackImpl or LDAPUserInfoImpl. Both of them are covered by a lot of tests which as you can see have not been changed at all.
The only thing that has been changed is `ldap.roles.attr.id` configuration property in LDAPUserGroupCallbackImpl which is now `ldap.role.attr.id`. I think there was a typo in the previous version and since we are working on the next major version we do not have to care about backward …

JBPM-5157 - Refactoring of LDAPUserGroupCallbackImpl and LDAPUserInfoImpl

---

jbpm-query-jpa/pom.xml

* the API is exposed by Java 8 by default, but not by
Java 9. Marking the dependency as provided to not
change the current behavior

query-jpa: explicitly depend on jboss-jaxb-api_2.2_spec

---

jbpm-examples/pom.xml
jbpm-human-task/jbpm-human-task-audit/pom.xml
jbpm-human-task/jbpm-human-task-core/pom.xml
jbpm-workitems/pom.xml

* fixed some POM indentation as well
Part of an ensemble:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303

[DROOLS-1216] exclude commons-logging and use jcl-over-slf4j instead

---

jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/persistence/JPATaskPersistenceContext.java

no unit test created - the tests for this functionality are already there, and they should be still passing after this change.

JBPM-5204 Redundant DB calls when Pessimistic locking is used

---

jbpm-flow-builder/pom.xml
jbpm-flow-builder/src/main/java/org/jbpm/process/workitem/JsonWorkItemParser.java
jbpm-flow-builder/src/main/java/org/jbpm/process/workitem/WorkDefinitionImpl.java
jbpm-flow-builder/src/main/java/org/jbpm/process/workitem/WorkItemRepository.java
jbpm-flow-builder/src/test/java/org/jbpm/process/workitem/WorkDefinitionImplTest.java
jbpm-flow-builder/src/test/java/org/jbpm/process/workitem/WorkItemRepositoryTest.java
jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repository/TestServiceFour/TestServiceFour.wid
jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repository/index.conf

- added support to use json in wid configs
- WorkItemRepository supports now parsing both mvel (default) as well as json
- added to tests

BPMSPL-295 - added support for json in wid configs

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/AsyncTaskCallbackTest.java

* the test timeouts quite regularly on slower Jenkins machines.
Increasing the timeout will show us if the test simply
timeouts because of that; or if there is some other (concurrency)
issue in which case the would still fail after 30s
Please don't merge this yet, let's trigger rebuild several times to see if the test would still timeout or not.

Increate test timeout to stabilize test on slower CI machines

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/CompositeCommand.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/GetTasksByGroupCommand.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskQueryServiceImpl.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/command/CommandBasedTaskService.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/LifeCycleBaseTest.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/TaskQueryServiceBaseTest.java
jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/Taskorm.xml
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/task/SynchronizedTaskService.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/main/java/org/jbpm/services/ejb/impl/TaskServiceEJBImpl.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskQueryFilterTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/TaskSubjectAndDescriptionTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/regression/task/HumanTaskAssignmentTest.java

Related to the release this week. 
PR Set: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/160
- https://github.com/droolsjbpm/jbpm/pull/560
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/605

[6.4.x] RHBPMS-4184,JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

---

jbpm-flow/src/main/java/org/jbpm/process/StatefulProcessSession.java

After changes in KIE API introduced by DROOLS-1267, it is not possible to compile jBPM as well as KIE Server (and maybe other projects). I have implemented `submit` method added to KIE API by throwing `UnsupportedOperationException`. Not sure if it is the best approach but it seems like it is only Drools-related operation.

[6.5.x] Fix compilation problems caused by changes in KIE API

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java

@mswiderski this does not fix the test, but it at least prevents the build from hanging when the tests goes havoc
Timeout 30s should I think be enough even for slower machines. If we have tests that take more than that, we should probably think about fixing them.

Use default timeout for jbpm-bpmn2 tests to avoid build hanging

---

jbpm-installer/auth/users.properties
jbpm-installer/standalone-eap-6.4.0.xml
jbpm-installer/standalone-eap-7.0.0.xml
jbpm-installer/standalone-full-eap-6.4.0.xml
jbpm-installer/standalone-full-eap-7.0.0.xml
jbpm-installer/standalone-full-wildfly-10.0.0.Final.xml
jbpm-installer/standalone-wildfly-10.0.0.Final.xml

Hi @krisv , @mswiderski , @dgutierr ,
Can you please check if you agree on this change? If so, will create the PR for master as well. 
Currently passwords on the jbpm-installer are on clear text, but both add-user script and our users management stuff do encrypt the passwords. So adding users from the UI adds the hashed password on the properties file, but the default passwords are on clear text.
I see two options:
1- Adding a configuration flag on the users management stuff to indicate wether passwords should be encrypted and use this configuration to set no encryption on the jbpm-installer.
2.- Moving the jbpm-installer to the use of encrypted passwords, as both add-user script and users management stuff expects.
This PR is the fix for option 2 -> Added users management configurations …

JBPM-5082: Added users management configurations for the jbpm installer.

---

jbpm-installer/pom.xml

* there are no java classes in src/main/java
which could be analyzed and the plugin just
fails becuase of that

Skip findbugs for jbpm-installer

---

jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java

Just a quick fix in test - providing same time as arguments of the test method. It called getToday() twice, which can differ in milliseconds sometimes, because it is called twice.
Master PR: https://github.com/droolsjbpm/jbpm/pull/596

Fixed Timestamp parameters for LocalTaskAuditTest.testDueDateUpdateSame test

---

jbpm-container-test/jbpm-container-test-suite/pom.xml

Hi,
I had to override xnio versions because otherwise these tests would not run properly with productized binaries on EAP 7. This change won't probably be needed on master.
Marián

Override xnio versions because of productization kie-platform-bom

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/model/CaseDefinitionComparator.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java

Placed case definition sorting before paging - results have to be sorted first to provide correct input for paging.
Introduced ascending/descending switch.
Removed redundant whitespaces from test.

JBPM-4646: fix case definition sorting

---

jbpm-container-test/jbpm-container-test-suite/src/main/java/org/jbpm/test/container/tools/IntegrationMavenResolver.java

Hi,
I have noticed, that one property in container tests is not used anymore, so I got rid of it.
Thanks

[6.5.x] Remove unused property for Maven resolver

---

jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
jbpm-bpmn2/src/test/resources/BPMN2-EventSubprocessErrorSignalEmbedded.bpmn2
jbpm-flow-builder/src/main/java/org/jbpm/compiler/ProcessBuilderImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/core/node/EventSubProcessNode.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventSubProcessNodeInstance.java
jbpm-installer/db/ddl-scripts/mysql5/mysql5-jbpm-schema.sql
jbpm-installer/db/ddl-scripts/mysqlinnodb/mysql-innodb-jbpm-schema.sql

RHBPMS-4208 - [GSS] (6.3.z) Unable to get log tables precision up to milliseconds when using MariaDB/MySQL
RHBPMS-4262 - [GSS] (6.3.z) Signal not getting invoked externally through rest API when it is in Error Scenario

[6.4.x] Backports for  6.3.4

---

jbpm-audit/src/test/java/org/jbpm/process/audit/AbstractAuditLogServiceTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/query/AuditQueryTest.java
jbpm-installer/src/test/java/org/jbpm/persistence/scripts/util/SQLScriptUtil.java

- Fixed handling of empty lines in upgrade SQL scripts tests.
- Fixed order by test - first test case from this test wasn't needed because it hadn't any order by - this failed sometimes because each DB can have different default ordering. 
- Fixed handling empty values from various DBs in AbstractAuditLogServiceTest.
I didn't create JIRA for this, because it's just test fixes. If it is needed, I'll create one.

Fixed tests that use DBs. 

---

jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseCommentNotFoundException.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/CaseCommentCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java

If user tried to update or delete not existing comment then NoSuchElementException was thrown.

JBPM-4646 - Case management - improved handling of missing comments

---

jbpm-services/jbpm-services-api/pom.xml
jbpm-services/jbpm-services-api/src/build/revapi-config.json

here is the revapi plugin configured for jbpm-services-api module. Thanks for justifications you made. Please wait for this PR droolsjbpm/droolsjbpm-build-bootstrap#303 to be merged, so we have the most up-to-date version tested.
Marian

Add revapi plugin to check public API in jbpm-services-api module

---

jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/ExecutorServiceFactory.java

This PR allows to define the JNDI lookup name of AvailableJobsExecutor implementation in ExecutorServiceFactory, thus allowing to load a customized implementation

[JBPM-5285] Custom JNDI name for AvailableJobsExecutor in ExecutorServiceFactory

---

jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/test/java/org/jbpm/remote/ejb/test/TestKjars.java
jbpm-container-test/jbpm-remote-ejb-test/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/test-kjar-bpmn-build/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/test-kjar-evaluation/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/test-kjar-integration/pom.xml

Fixes the build failing due to rewrite of test artifacts version by automation scripts.

Use project version for test artifacts

---

jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/test-kjar-bpmn-build/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/test-kjar-evaluation/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/test-kjar-parent/test-kjar-integration/pom.xml

The plugin is being built after the jbpm repo
(in droolsjbpm-integration), so it can not be
used here.

Do not use kie-maven-plugin

---

jbpm-runtime-manager/pom.xml

depends on https://github.com/droolsjbpm/drools/pull/1029

[DROOLS-1353] define ExecutableRunner interface - fix for osgi

---

jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml

Before the change, when running `mvn clean install -DskipTests` the container would still get started/stopped, which takes considerable amount of time and is not needed in such case.
@rsynek could you please quickly check this?

Don't start/stop container with -DskipTests

---

jbpm-installer/src/main/resources/db/ddl-scripts/postgresql/postgresql-jbpm-lo-trigger-clob.sql

Trigger script to insert/update/delete "fake" oid reference in jbpm_active_clob table in order to protect jBPM CLOB large objects from vacuumlo.

JBPM-5476 - vacuumlo deletes active large objects of jBPM CLOB data

---

jbpm-services/jbpm-services-cdi/pom.xml
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/humantaskservice/CustomHumanTaskServiceProducer.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/humantaskservice/CustomHumanTaskServiceTest.java

Weld 2.4.1.Final behaves somewhat different and is initializing the beans
during discovery. That leads to a call
CustomTaskPersistenceContextManager#beginCommandScopedEntityManager
which throws the exception. The bean is thus not initialized and the CDI
container is not able to inject some members (as they were not
initialized and thus are not available for injection). Using the
CommandBasedTaskService mock should lead to a same result - we do assert
that the custom bean is being injected as the execute() methods throws
exception.
Needs to be merged together with https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/350.
@mswiderski could you please take a look? I am not sure I understood the intention of the test correctly, so the fix may have to be updated.

Fix failing test after Weld 2.4.1.Final upgrade

---

jbpm-bpmn2/pom.xml
jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BusinessRuleTaskHandler.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
jbpm-bpmn2/src/test/resources/dmn/0020-vacation-days.dmn
jbpm-bpmn2/src/test/resources/dmn/BPMN2-BusinessRuleTaskDMN.bpmn2
jbpm-bpmn2/src/test/resources/dmn/BPMN2-BusinessRuleTaskDMNByDecisionName.bpmn2
jbpm-bpmn2/src/test/resources/dmn/BPMN2-BusinessRuleTaskDMNMultipleDecisionsOutput.bpmn2
jbpm-flow/pom.xml
jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
jbpm-flow/src/main/java/org/jbpm/workflow/core/node/RuleSetNode.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
pom.xml

@etirelli @tarilabs @krisv guys, here comes support for DMN in Business Rule Task of BPMN2
Overall, it's based on data input to provide following parameters:
- namespace - required
- model name - required
- decision name - optional, if not given will call evaluate all
these parameters are provided as data input/data input associations. So it differs from the DRL based support which requires rule flow group and that is given as attribute (an jBPM specific). Though that providing there three new custom attributes was a bit too much. Moreover, this aligns with how we deal with user tasks so we keep it consistent. At parsing time these DMN parameters are removed from the data inputs so they will never be inserted into the DMN context as input data so it's clear data set.
The switch that …

JBPM-5681 - DMN support for BusinessRuleTask

---

jbpm-services/jbpm-services-api/src/build/revapi-config.json

Hi,
this PR is related to droolsjbpm/droolsjbpm-build-bootstrap#393. Revapi config JSON file was divided into filter and ignores parts.
Marian

Split revapi configuration into filter and ignores

---

jbpm-installer/src/main/filtered-resources/lib/readme.txt
jbpm-installer/src/main/resources/build.properties

Needs to be merged together with:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/398
https://github.com/droolsjbpm/kie-wb-distributions/pull/469

[GUVNOR-2889] rename 'kie-wb-distribution-wars-*.war' to 'kie-wb-*.war'

---

jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml

...to enable tests on Sybase, as driver needs to be present on client's classpath due to BZ1281864

Add DB driver to Failsafe plugin's classpath

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/model/instance/CaseFileInstanceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/resources/META-INF/CaseMgmtorm.xml
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java

Ensure that all case instances have a case role even if done defined in the model.
Updated queries to retrieve owner from assignment instead of using audit change log user.

JBPM-5816 - Allow changing case owner

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/dynamic/HumanTaskSpecification.java

@cristianonicolai here is a tiny change to make the dynamic task work from the case mgmt showcase app, otherwise it fails with NPE

avoid NPE when dynamic task parameters are not given

---

jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/TaskQueryServiceBaseTest.java

**Add tests with groups and excluded owners**
Adds 2 tests methods that test behavior of excluding user/users
from group which is set as potential owner of the task.

JBPM-5610: Not able to exclude multiple owners for HumanTask - Tests

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/CompositeNodeInstance.java
jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/AsyncContinuationSupportTest.java

@krisv here is the option to turn all nodes into async mode via deployment descriptor. This means we can have it globally by using server level deployment descriptor or per kjar deployed.
in deployment descriptor it needs to be given as environment entry named "AsyncMode" and the value is "true" or "false"

JBPM-5880 - 'async' as a default option for all tasks

---

jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentImpl.java
jbpm-document/src/test/java/org/jbpm/document/service/impl/DocumentImplTest.java

Avoid NPE while calling toString on DocumentImpl without lastModifiedDate.
Simple unit test included

(JBPM-5878) DocumentImpl toString() generates NPE when no modification date is available

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StartEventTest.java
jbpm-flow/pom.xml
jbpm-flow/src/main/java/org/jbpm/process/core/timer/BusinessCalendarImpl.java
jbpm-flow/src/main/java/org/jbpm/process/core/timer/DateTimeUtils.java
jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java
jbpm-flow/src/test/java/org/jbpm/process/core/timer/DateTimeUtilsTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/event/BoundaryEventOnTaskWithCalendarTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/ConcurrentGlobalTimerServiceTest.java

Add support for ISO_8601 repeating intervals.
Cherrypick of https://github.com/kiegroup/jbpm/pull/809 and https://github.com/kiegroup/jbpm/pull/819

JBPM-5886: Replace joda-time with Java 8 time implementation

---

jbpm-runtime-manager/pom.xml
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/TimerInitFailureRuntimeManagerTest.java

I noticed that this new Byteman test hasn't been passing with IBM Java, but I have found a way to boot Byteman even with this version of Java. What do you think? Should I create the same workaround for other modules where Byteman is used?
Thanks,
Marian

[6.5.x] Fix Byteman test for IBM Java

---

jbpm-services/jbpm-kie-services/pom.xml
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/UserTaskAdminServiceImplTest.java

One case covers scenario where we cant to forward task to multiple PO(group)
One case covers adding PO to non-existent task and checks for exception
One case covers Add/RemoveExcludedOwners with groups

JBPM-5370: Add test cases covering add/removepotential owners with groups

---

jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/correlation/JPACorrelationKeyFactory.java
jbpm-persistence/jbpm-persistence-jpa/src/main/resources/META-INF/JBPMorm.xml
jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/correlation/CorrelationPersistenceTest.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/mapper/JPAMapper.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/CorrelationKeyTest.java

@tsurdilo here is a back port from master to 7.0.x

[7.0.x] JBPM-5897 - Fails to start a process with CorrelationKey which is unique but includes correlation properties of an existing correlation key

---

jbpm-services/jbpm-services-api/src/build/revapi-config.json

this is only a minor change to the revapi-config.json file, since these files are no more only on master branch, but on 7.0.x as well.
Marian

Change revapi-config.json comment to be more general

---

jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/AsyncContinuationSupportTest.java
jbpm-services/jbpm-executor/src/test/resources/BPMN2-AsyncServiceProcess.bpmn2
jbpm-services/jbpm-executor/src/test/resources/BPMN2-AsyncSubProcess.bpmn2
jbpm-services/jbpm-executor/src/test/resources/BPMN2-SubProcess.bpmn2
jbpm-services/jbpm-executor/src/test/resources/BPMN2-WaitForEvent.bpmn2
jbpm-workitems/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskHandlerTest.java

@MarianMacik see the second commit here to find out the adjustment of the test to work with signal. In general it was singling to early - before the async managed to trigger the signal node.

Add tests for 'async' as a default option for all tasks

---

jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseService.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java

I have extended case management tests which cover triggering ad-hoc tasks. This is needed in order to properly test [BPMSPL-317](https://issues.jboss.org/browse/BPMSPL-317).
I have also fixed `processInstanceId` parameter in the JavaDoc of `triggerAdHocFragment` from `CaseService`.
It seems that the files were not properly formatted so there are many whitespace changes. You can look at this commit without whitespace changes [here](https://github.com/kiegroup/jbpm/commit/8327a326fc14395c0bac232146213e7b940c1a12?w=1).

JBPM-5974: Extend tests triggering case ad-hoc tasks

---

jbpm-persistence/.gitignore

During the refactoring of the _jbpm-persistence_ module, the **.gitignore** file has been removed from this module's root directory and Git sees all files and directories created by IDEs now. This pull-request addresses this problem.

Add .gitignore file to jbpm-persistence module

---

jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/processinstance/ProcessInstanceResolverStrategyTest.java

change in https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/c1df75a4d209ae8c705a2848f9679658f8051c7d#diff-600376dffeb79835ede4a0b285078036R77
weirdly affected this test where a slf4j logger was intersted into ksession and was persisted. 
Temp fix for this test while someone can figure out why this change in bootstrap affected it.

[6.5.x] RHBPMS-4659 - persisting org.slf4j.Logger fails - temp fix for test

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CarInsuranceClaimCaseTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceDefinitionImplTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/StageCompletionConditionTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseWithTwoStagesConditions.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskAutocomplete.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskCaseDataBoolean.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskCaseDataInteger.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskCaseDataString.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskCaseFileAndProcessVariable.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskCaseFileVariable.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskCaseFileVariableNoPrefix.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskCount.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskNoAutoStart.bpmn2
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/completion/StageWithTaskProcessVariable.bpmn2

I have extended case stage completion condition tests as described in [JBPM-6013](https://issues.jboss.org/browse/JBPM-6013).
Most of the tests are failing because of [JBPM-6029](https://issues.jboss.org/browse/JBPM-6029). It seems the engine checks completion condition only when some task is completed but variables used in this condition may be changed in the meantime and the stage should be completed immediately when this happens.
The other thing I am not sure about is using case file variable without `caseFile_` prefix in the completion condition. I was told it should be possible to use case file variables directly if there is no process variable with the same name. However, it seems it does not work. See the ignored test.

JBPM-6013: Extend case stage completion condition tests

---

jbpm-audit/src/test/java/org/jbpm/process/audit/AbstractAuditLogServiceTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/query/AuditDeleteTest.java

Added cleaning tables in the beginning and after each test for AuditDeleteTest
Fixed comparing wrong values in CommandBasedAuditLogServiceTest
(cherry picked from commit fee7a89)

[JBPM-6075] JBPM-Audit: fix failing tests

---

jbpm-audit/src/test/java/org/jbpm/process/audit/AbstractAuditLogServiceTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/query/AuditDeleteTest.java

Added cleaning tables in the beginning and after each test for AuditDeleteTest
Fixed comparing wrong values in CommandBasedAuditLogServiceTest

[6.5.x] [JBPM-6075] JBPM-Audit: fix failing tests

---

jbpm-audit/pom.xml
jbpm-flow/pom.xml
jbpm-human-task/jbpm-human-task-audit/pom.xml
jbpm-human-task/jbpm-human-task-core/pom.xml
jbpm-human-task/jbpm-human-task-workitems/pom.xml
jbpm-query-jpa/pom.xml
jbpm-runtime-manager/pom.xml
jbpm-services/jbpm-shared-services/pom.xml

Hi,
I, @psiroky and @baldimir have found that TotalCompletionTimeAssignmentStrategyTest was failing with our automation because of `ClassNotFoundException: org.jbpm.services.task.assignment.impl.TotalCompletionTimeLoadCalculator`. We found out that this class wasn't present inside binaries jbpm-human-task-audit.jar, but was present in sources.jar. The root cause was the maven-bundle-plugin config which had empty Private-Package configuration and this new class was a part of a new package which wasn't in Export-Package either. Therefore, maven-bundle-plugin didn't put this class inside jar. PR builds were passing because they consume target/classes binaries and not resulting jars. To prevent this from happening in future I have removed empty Private-Package configurations from pom.xml …

Remove empty Private-Package config from maven-bundle

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java

-Modified core getComments method to use page/pageSize info from query context for pagination purposes

JBPM 6073: getComments method not returning desired page

---

jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-app/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml

Hi, @mswiderski @tomjenkinson,
here is the PR which should solve some of the issues with #898. jbpm-remote-ejb-test module shouldn't use BTM or Narayana at all since it runs only with WidlFly 10/EAP 7. Therefore, if you cherry-pick or rebase onto this, I think you shouldn't have any troubles with this module.
Thanks,
Marian

jbpm-remote-ejb-test cleanup of dependencies

---

jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml

Hi, @mswiderski 
this PR only covers simple exclusion of xml-apis for WebSphere 9. Tests were failing with productization builds because of different version of xercesImpl artifact to the version used in community.
Thanks,
Marian

jbpm-in-container-test: Exclude xml-apis on WebSphere 9

---

jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java

Added local cache for ejb timer service to improve performance after restart
Marked new timers as new to skip the timer service check by name to improve performance

RHBPMS-4761 - Transaction timeout when running EJB Timers on WAS

---

jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java

Added local cache for ejb timer service to improve performance after restart
Marked new timers as new to skip the timer service check by name to improve performance

[6.5.x] RHBPMS-4762 - Transaction timeout when running EJB Timers on WAS

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractDeploymentService.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/DeactivateDeploymentServiceWithSyncTest.java

Same as #942, but the test itself already uses one listener.

[7.3.x] Stabilize DeactivateDeploymentServiceWithSyncTest

---

jbpm-audit/src/test/java/org/jbpm/process/audit/AuditLogServiceTest.java
jbpm-audit/src/test/resources/logback-test.xml
jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/correlation/CorrelationPersistenceTest.java
jbpm-persistence/jbpm-persistence-jpa/src/test/resources/logback-test.xml
jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java
pom.xml

Surrounds "setURL" method invocation on db driver with try-catch and tries to use "setUrl" method in case no "setURL" method is present when initializing datasource. (Some drivers have setUrl some setURL)
Catch InvocationTargetException and log it.
Adds try-catch blocks around DB operation calls. Some operations throw exceptions when DB configuration is bad and these exception are hiding the configuration problem.
Sets _logLevel_ to _warn_ for narayana for some modules, since some relevant information wasn't being logged on _error_ level.

JBPM-6309: Investigate and fix jBPM community DB tests with Narayana

---

jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java

This adds additional method that handles setting up properties
for Sybase and DB2. For DB2 there are 2 specific properties
and Sybase requieres username and password setup before
actuall getConnection() call.
Removes redundant array creations and enhances logging.
@baldimir @MarianMacik  This should be the last change required for tour matrix jobs to work.
@mswiderski could you please review?

JBPM-6309: Fix jBPM community DB tests with Narayana

---

jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java

cherry-pick of #970 for 7.3.x
This adds additional method that handles setting up properties
for Sybase and DB2. For DB2 there are 2 specific properties
and Sybase requires username and password setup before
actuall getConnection() call.
Removes redundant array creations and enhances logging.

[7.3.x] JBPM-6309: Fix jBPM community DB tests with Narayana

---

jbpm-flow/src/main/java/org/jbpm/process/core/timer/BusinessCalendarImpl.java
jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java

Since the #init method doesn't allow a null `businessCalendarConfiguration`, any checks against `null` will never pass.

Remove dead code in BusinessCalendarImpl

---

jbpm-flow/src/main/java/org/jbpm/process/instance/event/DefaultSignalManager.java

JBPM-5400 - Concurrency problem in the class org.jbpm.process.instance.event.DefaultSignalManager
JBPM-5413 - Memory Leak in DefaultSignalManager
* changed DefaultSignalManager for concurrency
* Fix memory leak in processEventListeners

[6.5.x] RHBPMS-4940 - Memory Leak in DefaultSignalManager

---

jbpm-audit/src/main/java/org/jbpm/process/audit/event/DefaultAuditEventBuilderImpl.java

The proposed code avoids the generation of NPE every time you launch a process with no parent.
The inboxing performed by the JVM to create a Long with a NULL value and the later outboxing to assign a long from a NULL Long value generates a NPE every time you launch a process without parent.
This is a performance fix, please apply it.
Regards

Avoid generation of NPE while launching a Process without Parent

---

jbpm-audit/pom.xml
jbpm-audit/src/test/java/org/jbpm/process/audit/AbstractAuditLogServiceTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/AuditLogServiceTest.java

1. AbstractAuditLogServiceTest.runTestLogger4WithCustomVariableIndexer fixed when comparing process variable values loaded from audit log. Sometimes variable values were retrieved from audit log in wrong order when Oracle DB was used.
2. AuditLogServiceTest fixed: audit log clearing added during tearDown.

Jbpm tests fixing

---

jbpm-audit/src/test/java/org/jbpm/process/audit/CommandBasedAuditLogServiceTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/jms/AsyncAuditLogProducerTest.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/TaskCommentTest.java

Fixes CommandBasedAuditLogServiceTest and several asserts in testAsyncAuditLoggerCompleteWithVariablesCustomIndexer related to variable values and IDs loaded from audit log.

JBPM-6487 Jbpm tests stabilisation

---

jbpm-document/src/main/java/org/jbpm/document/Documents.java
jbpm-document/src/main/java/org/jbpm/document/marshalling/DocumentsMarshallingStrategy.java
jbpm-document/src/test/java/org/jbpm/document/marshalling/DocumentsMarshallingStrategyTest.java

Documents is a new type that wraps a List<Document>. The new MarshallingStrategy re-used the existing DocumentMarshallingStrategy for individual document persistence.

Initial implementation of JBPM-6502. Support collection of documents.

---

jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/main/java/org/jbpm/test/container/listeners/CountDownProcessEventListener.java
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/EJBService.java
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/ejbcompl/EThreadInfoTest.java
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/tx/ETransactionTest.java

I have made a couple of enhancements to stabilize jbpm-container tests. I have removed quite a lot of timers and changed them for CountDown listener synchronization. There are still some timers in other tests, however, I decided to leave this portion as is for now since they are stable.

[7.4.x] Stabilize jbpm-container tests

---

jbpm-audit/pom.xml
jbpm-human-task/jbpm-human-task-audit/pom.xml
jbpm-human-task/jbpm-human-task-jpa/pom.xml
jbpm-services/jbpm-executor/pom.xml
jbpm-workitems/jbpm-workitems-core/pom.xml

I ma not 100% sure this is the best option, but it seems to work without much fuzz. I've declared the deps as `<scope>provided</scope>` to keep this backwards compatible - e.g. the deps won't be transitively brought to the other modules depending on these.
This only makes sure that the the simple `mvn clean install` works. Fixing all the tests to run successfully on JDK9 will be a different task.

Add missing EE spec jars to support Java 9 build

---

jbpm-services/jbpm-kie-services/pom.xml

Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.

AF-593+: Move uberfire-maven-utils to kie-soup.

---

jbpm-distribution/pom.xml

This is the last change needed to make the `mvn clean install -Dfull -DskipTests` build work on JDK9.

distribution: JDK9 javadoc requires additional deps

---

jbpm-flow/src/main/java/org/jbpm/process/core/timer/NamedJobContext.java
jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/QuartzSchedulerService.java
jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/quartz/DeploymentsAwarePostgreSQLDelegate.java
jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/quartz/DeploymentsAwareStdJDBCDelegate.java
jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/quartz/QuartzUtils.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskDeadlinesServiceImpl.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeManagerFactoryImpl.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/factory/InMemorySessionFactory.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/factory/JPASessionFactory.java
jbpm-test-coverage/src/test/resources/quartz-db-short-misfire.properties
jbpm-test-coverage/src/test/resources/quartz-db.properties

this PR provides extension to default SQL delegates that take into considerations deployments that are present in the system. By that queries done by quartz will filter triggers by the deployments that are actually able to execute the job.
To make this possible, trigger (and job) group name is now set to deployment id (if available).

JBPM-6590 - Isolation of Quartz scheduler / triggers per kjar

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StartEventTest.java
jbpm-bpmn2/src/test/resources/BPMN2-MultipleStartEventProcess.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-MultipleStartEventProcessLongInterval.bpmn2

Number of instances created by the timer was reduced, aborting of the active processes after test finished was added together with history clearing. New process definition with longer timer duration added.

JBPM-6487 Jbpm tests stabilisation pr4

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StartEventTest.java
jbpm-bpmn2/src/test/resources/BPMN2-MultipleStartEventProcessDifferentPaths.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-TimerStartCron.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-TimerStartCycleLegacy.bpmn2

* cron interval extended for testTimerStartCron
* ksession.dispose() moved before loadStatefulKnowledgeSession so that no two sessions exist at the same time
* session restoring removed from testMultipleEventBasedStartEventsTimerDifferentPaths
* repeat interval for timer in BPMN2-MultipleStartEventProcessDifferentPaths added
* JbpmBpmn2TestCase: NPE check in clearHistory method
* testTimerStartCycleLegacy: timer frequency extended

JBPM-6487 StartEventTest stabilisation

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithPotOwnerDesc.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/builder/UserTaskPotOwnerQueryBuilder.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/builder/UserTaskPotOwnerQueryBuilderFactory.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithModifVarsQueryMapper.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithPotOwnerQueryMapper.java
jbpm-services/jbpm-kie-services/src/main/resources/META-INF/services/org.jbpm.services.api.query.QueryParamBuilderFactory
jbpm-services/jbpm-kie-services/src/main/resources/META-INF/services/org.jbpm.services.api.query.QueryResultMapper
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskInstanceWithPotOwnerTest.java
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/UserTaskInstanceWithPotOwnerDesc.java
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/query/QueryResultMapper.java

Allow to search tasks assigned by potential owner through

JBPM-6670 - Allow to search tasks assigned by potential owner through

---

jbpm-workitems/jbpm-workitems-bpmn2/pom.xml

This removes duplicated dependency which is already declared in this pom with default (compile) scope, which also makes that artifact available on test classpath. I've got a PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/639 pending to prevent this kind of duplicated dependency declaration which depends on this PR being merged.

Remove duplicated jaxb-core dependency declaration

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/async/AsyncIntermediateCatchSignalTest.java

@mswiderski or anyone else, could you please review? 
The test still fails randomly. I am not sure if there is a bug in JBPM or not. The process listener is invoked 4 times occasionally (looks like just 4 out of 5 processes finish sometimes).

JBPM-6720 Add timeout to test and replace wait notify with a latch

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ProcessFactoryTest.java
jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java
jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ActionNodeFactory.java
jbpm-flow/src/test/java/org/jbpm/process/ProcessFactoryTest.java

Adds test to show correct usage for JBPM-6713 and can set dynamic process via RuleFlowProcessFactory now (plus formatting)

JBPM-6713 - Fluent Rule Flow API - signal example

---

jbpm-services/jbpm-services-cdi/pom.xml

@mswiderski 
Fixes issues described in https://github.com/kiegroup/jbpm/pull/1123#issuecomment-360393508.
Thanks,
Marian

Fix CDI Tests by adding AssertJ as a test dependency

---

jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml

This change makes Arquillian work with WebLogic 12.2.1.3.0. Change is complete from the Arquillian side, if somebody wants to run tests, they would need the newest Cargo, but as of now it is OK to merge it like this since really nobody in community will run it on WebLogic I think.

jbpm-container: Make Arquillian functional on WebLogic 12.2.1.3.0

---

jbpm-audit/src/main/java/org/jbpm/process/audit/event/DefaultAuditEventBuilderImpl.java

@mswiderski This PR stores the eventDate in NODEINSTANCELOG the same way you did in processes and tasks.

JBPM-6821: Information not available in NodeInstance event listener

---

jbpm-audit/src/test/java/org/jbpm/process/audit/AbstractAuditLogServiceTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/jms/AsyncAuditLogProducerTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/query/AuditQueryCoverageTest.java
jbpm-audit/src/test/java/org/jbpm/process/audit/query/AuditQueryDataUtil.java
jbpm-audit/src/test/java/org/jbpm/process/audit/query/AuditQueryTest.java

here is the PR we discussed. I basically eliminated jUnit Assert in two classes and added removal of entities in the tests which created them so it won't cause issues to other tests.

Stabilize Audit tests

---

jbpm-bpmn2/src/test/resources/BPMN2-EventSubprocessSignal-Nested.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/log/TaskLogClean-inputAssociation.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/task/HumanTask-inputTransformation.bpmn2

Update to BPMN definitions which were failing the tests. OMG has decided to move schemas under HTTPS protocol.

Update XSD Schema locations in BPMN2 definitions

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/LogCleanupCommandTest.java

@mswiderski when playing a little bit with LogCleanupCommand I found that if you skip task logs and delete only process logs, it behaves correctly, but when you then try to delete everything including task logs, task logs are not deleted because they don't have active process instances in ProcessInstanceLog table. So my proposal is to delete them too since they are orphans now.
Quick summary of changes:
* Delete everything which either belongs to non-active process instance or doesn't belong to any - it now applies to NodeInstanceLog, VariableInstanceLog, TaskEventImpl and AuditTaskImpl (it worked with Node/VariableInstanceLog before since it is deleted together with ProcessInstanceLog, so there are no orphans left, only task-related things can have orphans)
* Unignored remaining …

RHBA-248 - LogCleanupCommand follow-up

---

jbpm-workitems/jbpm-workitems-archetype/src/main/resources/archetype-resources/jbpm-workitems-__rootArtifactId__/pom.xml
jbpm-workitems/jbpm-workitems-archetype/src/main/resources/archetype-resources/jbpm-workitems-__rootArtifactId__/src/assembly/widrepo-assembly.xml
jbpm-workitems/jbpm-workitems-archetype/src/main/resources/archetype-resources/jbpm-workitems-__rootArtifactId__/src/main/resources/kie-ddtemplate.st
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/RequiredParameterValidator.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/Wid.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidInfo.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidParameter.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidProcessor.java
jbpm-workitems/jbpm-workitems-core/src/test/java/org/jbpm/process/workitem/core/util/RequiredParameterValidatorTest.java
jbpm-workitems/jbpm-workitems-core/src/test/java/org/jbpm/process/workitem/core/util/RequiredParametersTestHandler.java
jbpm-workitems/jbpm-workitems-core/src/test/java/org/jbpm/process/workitem/core/util/WidProcessorTest.java

Added "required" attribute to the WidParameter allowing users to set certain handler input params to be set as required (handler will not execute if required params cannot be found) 
Updated WidProcessor to generate a parameter validation class for each of the handlers. This class checks existence of the required parameters and will throw exception if they cannot be found.
Added ValidatingAbstractLogOrThrowWorkitemHandler which workitem handlers can extend. It provides a validate method that will call the handlers validation class
Small changes to workitem archetype to add generation of the deployment descriptor

JBPM-5223 - Improve WorkItemHandler parameter definition

---

jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidParameter.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidResult.java
jbpm-workitems/jbpm-workitems-core/src/test/java/org/jbpm/process/workitem/core/util/WidProcessorTest.java

allow users to fully declare their types in handler class via annotation, for example 
```java
@WidParameter(name = "myParam", type = "new ObjectDataType(com.sample.MyType)")
@WidResult(name = "myResult", type = "new ObjectDataType(com.sample.MyType)")
```

update wid parameter and wid result type definition

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/ProcessInstanceCustomQueryMapper.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/QueryServiceImplTest.java

I've added some modifications in the mapper ProcessInstancesCustom and a new test in order to search processes without vars.

JBPM-7206: New custom query mapper for processes

---

jbpm-container-test/jbpm-in-container-test/pom.xml

There is an issue https://issues.jboss.org/browse/RESTEASY-1748 with Resteasy on weblogic. The issue prevents using REST services so REST WIH tests will fail on WebLogic. I will be notified when the bug is fixed, so it should be only a temporary fix.

Downgrade Resteasy to fix jbpm-container tests on WebLogic

---

jbpm-container-test/jbpm-in-container-test/pom.xml

[7.7.x] Downgrade Resteasy to fix jbpm-container tests on WebLogic 

---

jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java

@mswiderski As discussed, here is the fix. I have tested it on our Jenkins with all databases and it passed 3 times in a row. The reason why I don't include a test is that this test which was able to reproduce it in plain jBPM engine took more than minute for some databases (generating a big amount of data so query can clash wrong data), so I think it is not worth including it. We will still be able to verify it in KIE Server tests though. Thanks!
Marian

JBPM-7277 - Node SLA is not updated for the right node

---

jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/SimpleRuntimeEnvironmentTest.java

I came through this test class which extended the implementation class because of the access to protected field. I switched it for Mockito injection as it properly should be.

SimpleRuntimeEnvironmentTest shouldn't extend SimpleRuntimeEnvironment

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/RuntimeDataServiceImpl.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/RuntimeDataServiceImplTaskLookupTest.java

@mswiderski  We've detected some incoherence in the tasks search by pot-owner. When the group is set:
- With status=null: the groupIds set in the input parameters isn't taken into account.
- With status not null: the groupIds set in the input parameters is taken into account.
And in all the queries used in this method (for example: https://github.com/kiegroup/jbpm/blob/4b5895028198c2ba6d3abf06ce2bd8c1a05d3c33/jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/Taskorm.xml#L225) the where clause takes into account as pot-owner the userId OR the groups, but when the group is set in the input parameters the userId's groups aren't taken into account.

RHPAM-1192: Error in the tasks search by potential owners

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/CompensationTest.java
jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/base/TransactionalPersistenceEventManager.java
jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/processinstance/objects/TestTransactionalPersistenceEventManager.java
jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/session/PersistentStatefulSessionTest.java
jbpm-persistence/jbpm-persistence-jpa/src/test/resources/META-INF/services/org.jbpm.persistence.api.integration.PersistenceEventManager

@mswiderski I have found the testIntegrationWithEventManager3 test failing in case MapBasedPersistenceTest is run before it. I think the issue was that these tests introduce their own Transaction Manager [here](https://github.com/kiegroup/jbpm/blob/master/jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/map/impl/MapBasedPersistenceTest.java#L53) which is actually ManualProcessTransactionManager. In such a case, MapBased tests registered their own TX manager and when TransactionalPersistenceEventManager creates its tx manager [here](https://github.com/kiegroup/jbpm/blob/master/jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/base/TransactionalPersistenceEventManager.java#L48) it does not find all thing it needs via JNDI, so …

Stabilize EventEmitter tests

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/store/DeploymentStore.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/store/DeploymentStoreTest.java
jbpm-services/jbpm-kie-services/src/test/resources/descriptor/KModuleDeploymentUnit.txt

active flag in the deployment unit descriptor is false by default overruling the
state in the database, causing the deployment not to start upon restart if the tag
element is absence

[6.5.x] [RHBPMS-5156] Exisiting deployments from 6.4.2 are always deactivated after server restart in 6.4.6+

---

jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml

There are conflicts on WAS when creating an XML from deployment descriptor. This fixes it.

Exclude jboss-jaxb-api_2.2_spec from WebSphere

---

jbpm-audit/src/main/java/org/jbpm/process/audit/NodeInstanceLog.java
jbpm-audit/src/main/java/org/jbpm/process/audit/ProcessInstanceLog.java
jbpm-audit/src/main/java/org/jbpm/process/audit/VariableInstanceLog.java
jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/impl/model/BAMTaskSummaryImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/AttachmentImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/BooleanExpressionImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/CommentImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/DeadlineImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/DelegationImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/EscalationImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/I18NTextImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/NotificationImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/PeopleAssignmentsImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/ReassignmentImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/TaskImpl.java
jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/correlation/CorrelationPropertyInfo.java
jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/ProcessInstanceInfo.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ContextMappingInfo.java
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/entities/ErrorInfo.java
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/entities/RequestInfo.java

Signed-off-by: calvin zhu <calvinzhu@hotmail.com>
This PR is for 
https://issues.jboss.org/browse/RHPAM-1271
It use JPA 2.1 annotation to create the indexes (index list is from jbpm-installer/src/main/resources/db/ddl-scripts)

RHPAM-1271 KIE database creation does not include indexes

---

jbpm-workitems/jbpm-workitems-rest/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java
jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java
jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/TestRESTResource.java

adding Accept-Charset header to enforce server to send back the proper
charset.
The content-type might or might not send back the parameter charset so
this keeps that in mind that.

[JBPM-5188] Content negotiation @ RestWorkItemHandler

---

jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseService.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/AddDynamicProcessToStageCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/AddDynamicTaskToStageCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/TriggerAdHocNodeInStageCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseMultiInstanceStage.bpmn2
jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicNodeInstance.java

@DuncanDoyle if you find some time have a look

JBPM-7549 - Allow the use of stage-name to trigger adhoc fragment

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/ProcessInstanceAdminServiceImpl.java
jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/ProcessInstanceAdminServiceImplTest.java
jbpm-services/jbpm-services-api/src/build/revapi-config.json
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/admin/ProcessInstanceAdminService.java

Added new api function to get errors by deployment id

[RHPAM-1599] REST Endpoint for getting errors in a kie-container doesn't filter the result by container id

---

jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/pom.xml
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/test/java/org/jbpm/services/ejb/timer/EJBTimerJobNameTest.java

Creating unique names when it exists the same name of process across
containers

[JBPM-7988] EJB timer stops working in specific circumstances

---

jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidInfo.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidParameter.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WidResult.java
jbpm-workitems/jbpm-workitems-core/src/test/java/org/jbpm/process/workitem/core/util/WidProcessorTest.java

adds runtime type of parameters and results so this way users can specify for example
```java
@WidParameter(name = "Files", runtimeType = "java.util.List")
```
this helps users know what type each parameter and resuts are (can specify exactly when creating business processes) as well as helps with auto generation of fully executable bpmn2 for each handler.

JBPM-8034 - Add runtime type for wid parameters and results

---

jbpm-event-emitters/jbpm-event-emitters-elasticsearch/pom.xml

This allows to run these tests on JDK11.

JDK11: Include javax.activation:activation to elastic search

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/QueryServiceImpl.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/UserAndGroupsTasksPreprocessor.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/query/preprocessor/UserAndGroupsTasksPreprocessorTest.java
jbpm-services/jbpm-services-api/src/build/revapi-config.json
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/query/model/QueryDefinition.java

Adding a new preprocessor in order to filter by potential owners. The preprocessor creates 2 types of filter:
If the custom query hasn't got any query-params related to the potential owners, the preprocessor adds a new column filter by the logged user and his groups.
If the custom query has a query-params related to a list of potential owners, the logged user won't be take into account in the filter, but the new preprocessor will add a new column filter by the list of potOwners included in the query-params and their groups.

JBPM-8155 - New preprocessor in custom queries

---

jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml

Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/885

JBPM-7951 Remove patched tomcat-dbcp

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractDeploymentService.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/KModuleDeploymentService.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/utils/PreUndeployOperations.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/KModuleDeploymentServiceTest.java
jbpm-services/jbpm-services-api/src/build/revapi-config.json
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/DeploymentService.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-api/src/main/java/org/jbpm/services/ejb/api/DeploymentServiceEJBRemote.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-client/src/test/java/org/jbpm/services/ejb/client/helper/DeploymentServiceWrapper.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/main/java/org/jbpm/services/ejb/impl/DeploymentServiceEJBImpl.java

AF-1687: Align with 'kie-server' with development mode
Added extra param to decide if existing process instances must be aborted or not when undeploying.
@mswiderski @tomasdavidorg could you please take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/614
https://github.com/kiegroup/jbpm/pull/1424
https://github.com/kiegroup/droolsjbpm-integration/pull/1698
https://github.com/kiegroup/kie-wb-common/pull/2422

AF-1685: Development Lifecycle Streamline

---

jbpm-workitems/jbpm-workitems-bpmn2/pom.xml
jbpm-workitems/jbpm-workitems-rest/pom.xml

Another fix for JDK 11...
* jbpm-workitems-bpmn2 needs deps for WebServices which are used in tests
* jbpm-workitems-rest needs activation dep because CXF used in tests depends on javax/activation/DataSource

Fix jbpm-workitems tests to run with JDK 11

---

jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml

Websphere (WAS) and WebLogic (WLS) should support only Java EE7, keeping rest of application servers with Java EE8.
Then, for WAS and WLS, hibernate version should be downgrade to ${version.org.hibernate-4ee7} (defined at kie-parent) and some exclusions should be added in order to get rid of incompatibilities among classes (PersistenceProvider, TransactionManager)

set hibernate version to hibernate-4ee7 (was, wls)

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
jbpm-workitems/jbpm-workitems-bpmn2/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskTest.java
jbpm-workitems/jbpm-workitems-bpmn2/src/test/resources/calling-dmn-passthru.bpmn2
jbpm-workitems/jbpm-workitems-bpmn2/src/test/resources/string-passthru.dmn

In the DMN engine, there is a difference between passing a variable with a null value and not passing a variable. If a DMN model would support receiving a null input. it is currently impossible to invoke this model from BPMN. The DMN model will complain about a missing input requirement (since the null value variable was not passed) and the execution will not append. With this fix, null value variables are passed to DMN and the execution works.

RuleSetNodeInstance should pass null variable values to DMN

---

jbpm-services/jbpm-services-cdi/src/main/java/org/jbpm/services/cdi/impl/ExcludeNonCDIImplExtension.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/humantaskservice/HumanTaskServiceWithAuditExclusionTest.java

excluding org.jbpm.services.task.audit.jms.AsyncTaskLifeCycleEventProducer for only cdi applications

[JBPM-8038] Upgrading to 7.15: AsyncTaskLifeCycleEventProducer

---

jbpm-workitems/jbpm-workitems-bpmn2/pom.xml

org.apache.cxf:cxf-rt-frontend-jaxws depends on JAX-WS API (at compile time), but for JDK 11 these classes are not part of JDK. This can cause issues in any component which uses jbpm-workitems-bpmn2 artifact, i.e. Spring Boot.
It is interesting that although Apache CXF 3.3.0 officially supports JDK 11, the dependency on JAX-WS API still wasn't added, although now we use version 3.1.16.

Raise scope of jaxws-api for jbpm-workitems-bpmn2

---

jbpm-installer/src/test/java/org/jbpm/persistence/scripts/util/TestsUtil.java

This is just to exclude drop scripts in DDL tests since there is currently no support for them. Creation and drop of schema is done by hibernate.

jbpm-installer test: Exclude executing drop ddl scripts

---

jbpm-installer/src/test/java/org/jbpm/persistence/scripts/util/TestsUtil.java

[7.18.x] jbpm-installer test: Exclude executing drop ddl scripts

---

jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml

This should help avoid false negatives in duplicate deploy/undeploy tests.

jbpm-remote-ejb: Disable deployment sync

---

jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/correlation/CorrelationPropertyInfo.java
jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/correlation/CorrelationKeySizePersistenceTest.java

added CORRELATION_KEY_LOG_LENGTH to CorrelationPropertyInfo

[JBPM-8342] Newly added system property - org.jbpm.correlationkey.len gth - does not truncate the "value" column in the CorrelationPropertyInfo table

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java

I have refactored (no logic changed) the WorkItemNodeInstance class to allow redefining the data mapping logic when inheriting from the class. No behavior was changed.
Basically this let us extend the class and customize how we do the data mapping for the inputs/outputs.
Let me know if you have questions!
Thanks

Refactoring of WorkItemNodeInstance for extensibility

---

jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/correlation/CorrelationPropertyInfo.java
jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/correlation/CorrelationKeySizePersistenceTest.java

added CORRELATION_KEY_LOG_LENGTH to CorrelationPropertyInfo
cherry pick from (#1460)

[JBPM-8342] Newly added system property - org.jbpm.correlationkey.length - does not truncate the "value" column in the CorrelationPropertyInfo table

---

jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/timer/GlobalJpaTimerJobInstance.java

Backport of https://github.com/kiegroup/jbpm/pull/1466
@mswiderski @jstastny-cz could you please take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/jbpm/pull/1467
https://github.com/kiegroup/droolsjbpm-integration/pull/1784

[7.18.x] JBPM-8363: EJB Timer error in development mode for existing process during deploy

---

jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BusinessRuleTaskHandler.java
jbpm-flow/src/main/java/org/jbpm/workflow/core/node/RuleSetNode.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
jbpm-workitems/jbpm-workitems-bpmn2/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskTest.java
jbpm-workitems/jbpm-workitems-bpmn2/src/test/resources/calling-dmn-decision-service.bpmn2
jbpm-workitems/jbpm-workitems-bpmn2/src/test/resources/decision-service.dmn

I've update the business rule task code to allow invocation of DMN decision services.
I'm also contributing a test case that tests that only the output decisions of the decision service are returned and that the encapsulated ones are not. The test case also show that the rest of the model is not executed as the rest of the model has an input that is not provided.

JBPM-8374 Added support for invoking Decision Services from BPMN Business Rule Tasks

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/StartCaseCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseWithJPADataTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseExecutionInOneGo.bpmn2
jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java

adding variables as parameters upon process instance start
this avoids the problem of start/complete in the same sentence causing vars not logged

[JBPM-8077] When a case goes straight through from start to end, case file data is not persisted in the logs.

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/SingletonRuntimeManager.java

Discussed with @mswiderski 
I wanted to avoid to add dependency 'jbpm-services-ejb-timer' so it may look a bit verbose. Can this be written more concise?

add WARN for a combination of Singleton strategy and EJB Timer Scheduler

---

jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/test/java/org/jbpm/remote/ejb/test/task/EWebServiceTaskTest.java
jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java

@mswiderski Finally after some time this is "fixed". Please check especially the javadoc for WIH and notice that I have also removed (probably no more used) JDK9 profile, since I tested that it now works with JDK10 and JDK11 (except for WS tests), so probably will also work with JDK9 (which is EOL anyway).

BAQE-826 - Solve Apache CXF issue in jBPM tests

---

jbpm-flow-builder/src/main/java/org/jbpm/compiler/ProcessBuilderImpl.java
jbpm-flow/src/main/java/org/jbpm/process/core/validation/impl/ProcessNodeValidationErrorImpl.java
jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java

These 2 changes allows us to have extensibility options to keep node information with the error message for builder/validation.
Our tool highlights the shape in error after a publication and those simple modifications let us hook into the framework and retrieve the info we need in the fronted.
The default behavior of the engine is not changed at all.
ProcessBuilderImpl: Icreated a method to transfer the error into ParseEerror so that we can overload it to provide our own class that extends ParserError and keep the node information
RuleFlowProcessValidator: The message formating hardcoding is moved to the new class that extends the previous class. The non formatted message is also accessible as well as the node.

Allow extensibility in the process builder/validator 

---

jbpm-runtime-manager/src/test/resources/META-INF/beans.xml
jbpm-services/jbpm-executor-cdi/src/main/resources/META-INF/beans.xml
jbpm-services/jbpm-executor-cdi/src/test/resources/META-INF/beans.xml
jbpm-xes/pom.xml

@cristianonicolai @MarianMacik please review.
After jboss ip bom replacement, XES Main tests were failing due to incorrect versions of commons-cli library. New dependencyManagement section has been added to handle right ones.

dependencyManagement section added after jboss_ip_bom replacement

---

jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
jbpm-workitems/jbpm-workitems-webservice/pom.xml

@gmunozfe There was an issue on JDK11 in jbpm-container tests. An upgrade of cxf-rt-databinding-jaxb no longer depends on jaxb-impl (see https://github.com/apache/cxf/commit/54b71171e89bb1be7d169ac91bb626c9c1ca293b#diff-3ab950a3633cee6bcef4ee7e98da8d33), so I had to add it in jbpm-container test suite. Moreover, we don't need jaxb-core there since cxf-rt-databinding-jaxb no longer depends on it and tests are passing (at least locally).

Fix WebServiceWorkitemHandler with JDK 11

---

jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/LocalTransactions.java
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/TransactionsTest.java
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/WebServiceInvokeTest.java

Or how to shave off nearly 20 seconds from test execution...

JBPM-8701 - Remove unnecessary sleeps from jbpm-in-container tests

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/AsyncEventNodeInstance.java
jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/AsyncContinuationSupportTest.java

setting the proper level when we are moving backward in the flow
so it is not interpreted incorrectly by the iteration level.

[JBPM-8644] AsyncMode doesn't wait on Inclusive converging Gateway

---

jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorImpl.java
jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/BasicExecutorBaseTest.java

In windows 2K16 instances, two tests were failing due to execution is so fast that milliseconds precision is not enough: 
- added  "<=" in the failing Assert for _testCustomIncrementingRequestRetrySpecialValues_
- changed PrintOutCommand to DelayedPrintOutCommand for _testPrioritizedJobsExecutionInvalidProrities_
Fixing also some warnings at priority bounds check, as the order of binding parameters was wrong.
@MarianMacik please review

Stabilization and fixes on some wrong traces

---

jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/ElasticSearchEventEmitter.java

This is a bugfix for the extension jbpm-event-emitters-elasticsearch, which converts explicitely using UTF-8.
Some variables values might contain special characters. For example in German that are umlauts (ä,ö,ü).
Currently if some variable contains one of these characters, they are not stored in Elasticsearch.
Instead you will get this error from Elasticsearch:
```
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte
```

Send UTF-8 encoded content to Elasticsearch

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/ExecutorLogCleanTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/service/ServiceTaskHandlerTest.java

Some tests need a little tuning due to fast execution at windows 2016 servers:
-deleteErrorLogsByDate, it's removing two logs (instead of expecting one) because dates are the same for both. Added this scenario to the test.
-ServiceTaskHandlerTests (testShorten[Full]InterfaceNameBPMN2[Workitems]) are expecting 1 as result (input date lower) but obtaining 0 (same date). Updated to pass a previous date (day before) instead of current date.

Stabilize tests due to fast exec at win2k16 servers

---

jbpm-human-task/jbpm-human-task-workitems/src/main/java/org/jbpm/services/task/wih/util/PeopleAssignmentHelper.java
jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/HTWorkItemHandlerBaseTest.java
jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/PeopleAssignmentHelperTest.java

remove default createdBy assignment to a task

[JBPM-8801] Process instance assign first potencial actor to field "created by" when it is empty in process definition

---

jbpm-runtime-manager/pom.xml
jbpm-services/jbpm-kie-services/pom.xml
pom.xml

Guys,
this should fix the issue with code coverage reporting. Now the `jacoco.exec` file is present in the `target` of the directory the Maven command is run from. The other option was to create a new profile section in the `jbpm-runtime-manager` POM so it would override the Byteman-only section defined in it. I have also noticed that there were unused Byteman dependencies declared, so I removed them. Feel free to comment.
Thanks @rsynek for having the devil idea about having 2 java agents!

JBPM-8856 - Fix code coverage in the jbpm-runtime-manager module

---

jbpm-runtime-manager/pom.xml
jbpm-services/jbpm-kie-services/pom.xml
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/DeactivateDeploymentServiceWithSyncTest.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/DeploymentServiceWithSyncTest.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/objects/CountDownDeploymentListener.java
jbpm-services/jbpm-kie-services/src/test/resources/entity/entity-test-persistence.xml
jbpm-services/jbpm-services-cdi/pom.xml
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/impl/admin/ProcessInstanceMigrationServiceCDIImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/impl/manager/MultipleRuntimeManagerTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/impl/manager/SingleRuntimeManagerTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/impl/manager/SingleRuntimeManagerWithEmbeddedTaskServiceTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/impl/manager/SingleRuntimeManagerWithListenersTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/BPMN2DataServiceCDIImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/DeploymentServiceCDIImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/DeploymentServiceCDIImplWithSyncTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/ProcessServiceCDIImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/QueryServiceCDIImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/RuntimeDataServiceCDIImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/RuntimeDataServiceTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/UserTaskServiceCDIImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/hr/HumanResourcesHiringTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/humantaskservice/CustomHumanTaskServiceTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/humantaskservice/HumanTaskServiceWithAuditExclusionTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/support/CDISupportProcessTSInjectionDisabledTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/support/CDISupportProcessTSInjectionSingletonTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/support/CDISupportProcessTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/util/CountDownDeploymentListenerCDIImpl.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/test/java/org/jbpm/services/ejb/test/DeploymentServiceEJBWithSyncIntegrationTest.java

1. `forkMode` is deprecated
2. ~~We don't need it in 2 of 3 modules as it doesn't contain any Arquillian tests.~~

Don't use forkMode because it is deprecated

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseWithStageAndBoundaryTimer.bpmn2
jbpm-flow/src/main/java/org/jbpm/workflow/core/node/DynamicNode.java

Issue happened when there were nodes without name, inside a stage. 
After boundary timer is fired, _resolveVariable_ method may receive a null string in the first param, due to process contains nodes without setting their names.
Added check at **DynamicNode** class, _acceptEvent_ method with resolver function, and test to validate it.

RHPAM-2422: Avoid NPE for cases with null name nodes and boundary timers inside stage

---

jbpm-installer/src/main/resources/db/ddl-scripts/postgresql/postgresql-jbpm-lo-trigger-clob.sql
jbpm-installer/src/test/java/org/jbpm/persistence/scripts/util/SQLScriptUtil.java
jbpm-installer/src/test/java/org/jbpm/persistence/scripts/util/TestsUtil.java

Following issues during ddl script execution for postgresql have been sorted out:
- Delimiter semicolon has to be kept without splitting if found inside a dollar quoted block
- schema sql has to be executed prior to trigger sql
- missing drop table jbpm_active_clob

Fix tests for postgresql ddl scripts

---

jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/HelloWebService.java
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/RegisterRestService.java
jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml

After AssertJ upgrade from version 3.8.0 to 3.14.0, the uberjar is now 4.5 MB instead of 1.2 MB which means the deployed archives are bigger as well and sometimes there is an OutOfMemoryError when tests are run.
* Raised max heap size for WildFly/EAP from 1 GB to 1.5 GB
* Include AssertJ only in archives which need it

JBPM-8952 - Stabilize jbpm-in-container test after AssertJ upgrade

---

jbpm-test-coverage/pom.xml

Missing this dependency for the new tests related to CaseLogCleanupCommand (JBPM-8745), which provokes ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory

Missing dependency with jdk11 (com.sun.xml.bind:jaxb-impl) for CaseLogCleanupCommand (JBPM-8745) 

---

jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/QuartzSchedulerService.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/TimerMigrationManagerTest.java
jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-UserTaskBoundary-v1.bpmn2
jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-UserTaskBoundary-v2.bpmn2

self remove timer if there is no next boundary event in human task

[JBPM-8896] NPE during Process Migration when Boundary Timer is fired but UserTask not completed

---

jbpm-installer/src/test/java/org/jbpm/persistence/scripts/TestPersistenceContext.java
jbpm-installer/src/test/java/org/jbpm/persistence/scripts/UpgradeScriptsTest.java

Since UpgradeScriptsTest contains known issues for
- db2: fails 'Call SYSPROC.ADMIN_CMD'
- sybase: no 6.0 scripts exist
then, skip upgrade tests for these database types.

Skip UpgradeScriptsTest for db2 and sybase

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/deadlines/notifications/impl/NotificationListenerManager.java

adding support for autodiscovering and registering new notification listeners

[JBPM-8998] Missing SpringBoot support in NotificationListener

---

jbpm-installer/src/main/resources/build.properties

from this version it seems that some URLs are not accessible any more.
Changed all left over http to https.
Changed https://repository.jboss.org/ to https://origin-repository.jboss.org/ since the origin-repository gets updated immediately.
Script was tested now and it works properly again.

fixed last http left overs and URLs

---

jbpm-services/jbpm-kie-services/pom.xml
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/audit/ServicesAwareAuditEventBuilder.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/audit/ServicesAwareAuditEventBuilderTest.java

When bypassing user auth, ProcessEvent can now use 'initiator' from process data if set, when creating ProcessInstanceLog for ProcessStartedEvent.

[JBPM-8991] Allow for process initiator to be set using 'initiator' value from process data

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/ProcessInstanceLogCleanTest.java

deleteLogsByDate method fixed by adding a delay of 1sec when starting up BPM processes in order to avoid issue with equal dates.
Previous fix didn't work completely as there were cases where some of the dates were equals between them and some of them not. For instance, out of 4 dates, 2 were equals between them and the other 2 were equals between them but different than the first two. So it is difficult to manage this scenario. 
One option would've been to use same data structure, either a hashset or a list for both, startDates and resultList but I think the easiest solution is to add a small delay of 1 second when starting up the processes. 
By doing this, we make sure the start dates are completely different one each other.

Fixed issue when having same dates - deleteLogsByDate method

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/pom.xml
jbpm-human-task/jbpm-human-task-audit/pom.xml
jbpm-human-task/jbpm-human-task-core/pom.xml
jbpm-human-task/jbpm-human-task-workitems/pom.xml
jbpm-installer/pom.xml
jbpm-runtime-manager/pom.xml
jbpm-services/jbpm-executor-cdi/pom.xml
jbpm-services/jbpm-executor/pom.xml
jbpm-services/jbpm-kie-services/pom.xml
jbpm-services/jbpm-services-cdi/pom.xml
jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/pom.xml
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/pom.xml
jbpm-test/pom.xml
jbpm-workitems/jbpm-workitems-webservice/pom.xml

It should work with -Dfull and jdk11

[JBPM-9028] Fix jdk11 downstream compilation

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/correlation/CorrelationKeyInfo.java

remove select for CorrelationKeyInfo and adding unique index

[RHPAM-2789] CorrelationKeyInfo table is used even without using correlation key functionality

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/subprocess/ReusableSubProcessTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/subprocess/ErrorHandlingMainProcess.bpmn
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/subprocess/ErrorHandlingSubprocess.bpmn

error boundary compensation event is not thrown.

[7.7.x] [RHPAM-2782] Error boundary event not working as expected with reusable subprocess node.

---

jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java

removing transient objects when the timer is created.

[RHPAM-2805] memory growth when starting a high number of process instances with a high timers

---

jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPAProcessInstanceManager.java

name in correlation key does not reflect the external form. Change to switch factory
implementation

[JBPM-9073] Unique index error when correlationKey name is set to null

---

README.md

The issue in GitHub is moved to https://issues.redhat.com/projects/JBPM/issues
So this badge always shows 0 issue without a link to the issue.

remove unused badge `issue`

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ExecutionErrorInfo.java
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/error/ExecutionErrorInfoTest.java

trim string in execution error info so it does truncate when info does not fit the column

[RHPAM-2903] 255 characters limitation in ExecutionErrorInfo database table

---

jbpm-audit/src/test/java/org/jbpm/process/audit/jms/AsyncAuditLogProducerTest.java

At **mysql/mariadb** execution of _AsyncAuditLogProducerTest#testAsyncAuditLoggerComplete_, the nodes returned by **findNodeInstances** are
`{Start, Task, End, Start, Task, End}`
instead of expected
`{Start, Start, Task, Task, End, End}`
:grey_exclamation: Notice that _log_date_ is the same when running tests, as execution is very fast.
:point_right: Sorted in the test by **nodeInstanceId** and id to fix it.

[RHPAM-2861] Stabilize mysql JMS test ordering also by nodeInstanceId

---

jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/AddTaskCommand.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskInstanceServiceImpl.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/UserTaskAdminServiceImplTest.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/RuntimeDataServiceImplTest.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskInstanceWithPotOwnerTest.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/support/SupportProcessBaseTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/TaskLogCleanTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/regression/task/HumanTaskTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/task/HumanTask-Listener.bpmn2

transitions between task status are not being captured.
It is needed to trigger the events in the lifecycle of the task.

[RHPAM-2840] issue with afterTaskActivatedEvent method of TaskLifeCycleEventListener

---

jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/StartProcessFromArbitraryNodesServiceImplTest.java
jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/BPMN2-SimpleRestartWithErrorOnEntryScriptHT.bpmn2
jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/BPMN2-SimpleRestartWithErrorOnExitScriptHT.bpmn2
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/RuntimeDataService.java

Missing EntryType for ERROR (exit audit logs assigns this type when the node was exited because a problem of the node), needed for start a process from that Error nodes.

[JBPM-9177] Missing ERROR as EntryType for retrieving full History

---

jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/DBUserGroupCallbackImplTest.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/DBUserInfoImplTest.java

Table name uses a reserved word for mysql.
If quoted with backticks (`), then other dbs (mssql, db2) don't work (incorrect syntax).

[JBPM-9155] GROUPS is a reserved word since mysql 8.0.2

---

jbpm-workitems/jbpm-workitems-rest/pom.xml
jbpm-workitems/jbpm-workitems-rest/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java
jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/RESTWorkItemHandlerProxyTest.java

Creating new constructor with additional useSystemProperties parameter,
which allow creating connection using system properties.
Depends on [droolsjbpm-build-bootstrap#1355](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1355)

JBPM-9138 - RESTWorkItemHandler doesn't support proxy

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/SLAComplianceTest.java
jbpm-flow/src/main/java/org/jbpm/process/instance/command/UpdateTimerCommand.java

When updating SLA Timers, new SLADueDate should be calculated and set for being coherent with the new triggering of the timer

[RHPAM-2980] Set new SLADueDate when updating SLA timer

---

jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/quartzdialects/QuartzDialectResolver.java

Previously, dbAllocator was instantiating MariaDB instances with "MySQL" db name, but now Quartz schema validation is failing because the database name was missing.

Register dialect for validating Quartz-mariaDB

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/VariableTagsTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/AddDataCaseFileInstanceCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/RemoveDataCaseFileInstanceCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/ReopenCaseCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/StartCaseCommand.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/UserTaskCaseReadOnlyCaseFileItem.bpmn2
jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java
jbpm-test-coverage/src/main/java/org/jbpm/test/entity/MedicalRecord.java

Now it is possible to assign a value to a case property when the
process is created, but a ViolationException will be thrown if trying
to update it when reopening.
Implementation note. In order to not change existing interface, which I
believe to be out of scope, the
parameter to decide if ViolationException should be thrown or not is
specified inside the parameters map.

[JBPM-9097] Case variable: "readonly" tag permits changing value after

---

jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/DBUserGroupCallbackImplTest.java
jbpm-human-task/jbpm-human-task-core/src/test/resources/jbpm.usergroup.callback.db.properties

Refactoring this test class to parameterize it with the 2 possible configurations: programmatically and declaratively, as DOC team was asking about some examples of declaratively configuration to be properly documented.

[JBPM-9200] Tests for DB UserGroupCallback with declarative config

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/async/AsyncMultisubprocessTest.java

Sometimes this test **AsyncMultisubprocessTest** fails, depending on the CPU processing time.
The issue is because 4 iterations (_number_reviews_ variable) for multisubprocess are asynchronously launched, and when two of them (_approvalsRequired_ variable) are completed, the outcome variable switches to true, so processes finishes and uncompleted tasks change to `Exited` status, which makes them fail if they are still trying to transition.
_org.jbpm.services.task.exception.PermissionDeniedException: User '[UserImpl:'rhpamAdmin']' was unable to execute operation 'Claim' on task id 3 due to a no 'current status' match_
I think the easier fix is to force that _approvalsRequired_ are the same as _number_reviews_, so completion condition cannot be achieved while transitioning other human tasks …

[BAQE-1454] Stabilize flaky test: AsyncMultisubprocessTest

---

jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/ElasticSearchEventEmitter.java

Change default date time format of events sent to Elasticsearch from 12h to 24h format.

JBPM-7880 - Fix default date-time format

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalTimerServiceBaseTest.java

testInterediateTimerWithGlobalTestService
Replaced sleeps by countdown latch listener

[JBPM-9212] Stabilize GlobalQuartzDBTimerServiceTest -

---

jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseRuntimeDataService.java
jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/model/instance/CaseInstance.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/model/instance/CaseInstanceImpl.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java

Adding new overloaded getCaseInstances method to CaseRuntimeDataService that allows the possibility to include case file information if a flag is set
Merge with [droolsjbpm-integration:2151](https://github.com/kiegroup/droolsjbpm-integration/pull/2151)

[JBPM-9223] include case file details in case list.

---

jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/VariableTagsTest.java
jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java

if the value is an empty string, the variable is not consider as
present.

[RHPAM-3048] Consider empty string an invalid value for required

---

jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/map/impl/MapPersistenceTest.java

Fix JpaBasedPersistenceTest.processWithNotNullStartDateTest after [jbpm#1705](https://github.com/kiegroup/jbpm/pull/1705)

[JBPM-9272] Failing test due to startDate processInstance/processInstanceInfo precision

---

jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/DDLScriptsTest.java
jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/GenerateDDLScriptsTests.java
jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/SpringbootDDLScriptsTest.java
jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/UpgradeScriptsTest.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/ScriptsBase.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/TestPersistenceContextBase.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/ScriptFilter.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/TestsUtil.java

With [jbpm#1651](https://github.com/kiegroup/jbpm/pull/1651) new DDL scripts (named with prefix _springboot_) were added for postgresql and oracle, generated with the property _**hibernate.id.new_generator_mappings**_ set to _true_.
These scripts have to be validated against definition in order to keep them always updated.

[JBPM-9259] Create a test to validate new springboot DDL scripts

---

jbpm-workitems/jbpm-workitems-rest/pom.xml
jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/RESTWorkItemHandlerProxyTest.java

Depends on [droolsjbpm-build-bootstrap#1423](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1423)

[JBPM-9269] ibm jdk: Missing sun.security classes for mock-server tests

---

jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/Taskorm.xml

After [jbpm#1680](https://github.com/kiegroup/jbpm/pull/1680), when the join clause was added to this query an exception has come out only for sybase.
Removed `OrganizationalEntityImpl potentialOwners` from the query, as it was useless, will solve it.

[JBPM-9258] Sybase: GetSubTasksByParentTaskId query syntax fails

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/query/model/QueryParam.java

upstream jira :
https://issues.redhat.com/browse/JBPM-9296

[JBPM-9296] Self contained Audit/History module

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/UserGroupCallbackTaskCommand.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/UserTaskAdminServiceImplTest.java

Currently If user does not exist in callback, the organizational entity is not created, but no exception is thrown, so later a constraint violation is thrown, as described in the JIRA.
This change will make error message more descriptive  (the operation itself cannot suceed if the user is not in the context, we cannot allow arbitrary users to be added to organizationentity)
**JIRA**:
[JBPM-9306](https://issues.redhat.com/browse/JBPM-9306)

[JBPM-9306] Raising exception when user is not defined

---

jbpm-workitems/jbpm-workitems-repository-archetype/.gitignore

[**JBPM-9312**](https://issues.redhat.com/browse/JBPM-9312)

[JBPM-9312] - Add .gitignore file to jbpm-workitems-repository-archetype module

---

jbpm-workitems/jbpm-workitems-rest/pom.xml

**JIRA**: 
[JBPM-9316](https://issues.redhat.com/browse/JBPM-9316)

[JBPM-9316] Missing javax.xml.bind package with jdk11

---

jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/ErrorLinkProcessTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/common/DifferentLinkProcess.bpmn2

Actually, the way engine works, links are included as metadata
information of the parent process or every container node, so there is
not vissibility between the links of a subprocess and links of the
parent process, meaning that, at all effects, a no link scenario is
similar to a link in different subprocess.
Error Message was already improved as part of RPHAM-3132, so message
when there is no association is
"There is not connection from any throw link to these catch links {list
of ids}" or "There is not connection from any catch link to these throw
links {list of ids}"
Since now the ids of the missing connections are logged, although the
same message is printed regardless there is no link or there is a link
in a different process,  the user can easily tie knots, avoiding the
confusion. …

[JBPM-9261] unclear validation message for link in different subprocess

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/KModuleDeploymentService.java

If the project is classpath there is no need to resolve artifacts. They should be already in the class loader.
https://issues.redhat.com/browse/JBPM-9344

[JBPM-9344] Maven project loader requires solving pom with immutable spring boot images.

---

jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/EmailDeadlinesBaseTest.java
jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/EmailDeadlinesDBTest.java
jbpm-human-task/jbpm-human-task-core/src/test/resources/org/jbpm/services/task/service/DeadlineWithNotification.mvel

Changed also the base test to make it more clear: the email defined in the mvel rule is not needed to be populated before nor at userinfo.properties (for DefaultUserInfoImpl) neither at database (for DBUserInfoImpl)

[JBPM-9278] Tests for Email deadline notifications with DBUserInfoImpl

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/DefaultRegisterableItemsFactory.java

Jira: https://issues.redhat.com/browse/JBPM-9366
Allow access to environment variables through env['<my env name var']

[JBPM-9366] Allow environment variables during WIH registering.

---

jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/test/CountDownAsyncJobListener.java
jbpm-test-coverage/pom.xml
jbpm-test-coverage/src/main/java/org/jbpm/test/listener/CountDownAsyncJobListener.java
jbpm-test-coverage/src/test/java/org/jbpm/test/regression/ParallelAsyncJobsTest.java

[**BAQE-1456**](https://issues.redhat.com/browse/BAQE-1456): Get rid of jbpm-executor test jar in jbpm-test-coverage

[BAQE-1456] Get rid of jbpm-executor test jar in jbpm-test-coverage

---

jbpm-event-emitters/jbpm-event-emitters-kafka/pom.xml
jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/java/org/jbpm/event/emitters/kafka/CloudEvent_1_0.java
jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/java/org/jbpm/event/emitters/kafka/KafkaEventEmitter.java
jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/resources/META-INF/services/org.jbpm.persistence.api.integration.EventEmitter
jbpm-event-emitters/jbpm-event-emitters-kafka/src/test/java/org/jbpm/event/emitters/kafka/KafkaEventEmitterTest.java
jbpm-event-emitters/pom.xml
jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/EventEmitter.java

Defining kafka event emitter
Unit test included in this PR (integratin test will be included by QE)
**JIRA**: 
[JBPM-9413](https://issues.redhat.com/browse/JBPM-9413)
Depends on 
[#1495](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1495)

[JBPM-9413] AMQ Streams (Kafka) integration Notifier / producer

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/KModuleDeploymentService.java

Jira https://issues.redhat.com/browse/JBPM-9407
Moving the code required for objects creating to a method so it could be overwritten

[JBPM-9407] Spring Boot - Multiple Data Sources and Pluggable Variable Persistence

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventNodeInstance.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java

added timer name to configure SLA in order to generate a proper job handle id.
Otherwise it will registered twice: once the node is reached and once the node is unmarshalled
Jira https://issues.redhat.com/browse/RHPAM-3233
cherry pick from 
https://github.com/kiegroup/jbpm/commit/885d1be66859fdbbab1736dc0b368064efb0db3c

(QE) [7.44.x] [JBPM-9447] No session found for context in case SLA on user task is violated

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventSubProcessNodeInstance.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/async/AsyncAdHocSubprocessTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/Exception.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/Level1P.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/Level2C.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/Level3SC.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/MainProcess.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/SubProcess.bpmn2

Jira: https://issues.redhat.com/browse/JBPM-9459

[JBPM-9459] Nested process instances abort doesn't work when a task in event subprocess is marked with "Is Async" as true

---

jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BusinessRuleTaskHandler.java
jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/TaskHandler.java
jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/elements/DataAssociationFactory.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/DataTest.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/xml/elements/DataAssociationFactoryTest.java
jbpm-bpmn2/src/test/resources/BPMN2-DataInputAssociations-Pojo-Complete.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-DataInputAssociations-Pojo.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-DataOutputAssociations-Map.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-DataOutputAssociations-Pojo-EmptyFrom.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-DataOutputAssociations-Pojo.bpmn2
jbpm-bpmn2/src/test/resources/BPMN2-DataOutputAssociations-PojoList.bpmn2
jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/ProcessDialectRegistry.java
jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/MVELAssignmentAction.java
jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/MVELAssignmentBuilder.java
jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/MVELProcessDialect.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceResolverFactory.java

Reading expressionLanguage from process
Implementing assigment for mvel
Introduced system property (org.kie.jbpm.bpmn2.useDefinitionLanguage) to specify if expressionLanguage should be read from definitions if language is not specified in Assigment (default value false, since there are working process which have mvel as definition and are using Xpath)
**JIRA**: 
[JBPM-9470](https://issues.redhat.com/browse/JBPM-9470)

[JBPM-9470] User Task output variable mapping to an object attribute

---

jbpm-db-scripts/src/main/resources/db/ddl-scripts/db2/db2-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/derby/derby-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/h2/h2-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/hsqldb/hsqldb-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/mysql5-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/oracle-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver/sqlserver-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver2008/sqlserver2008-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sybase/sybase-jbpm-schema.sql

Jira: https://issues.redhat.com/browse/JBPM-9503

[JBPM-9503] Duplicate correlationkey for 2 active process instances

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/SimpleRegisterableItemsFactory.java

Adding addProcessEvent (ProcessEventListener) to
SimpleRegistrableItemsFactory. This way the caller can specify its own
instances rather than delegate creation on refelection as
addProcessEvent (Class) does
**JIRA**: 
[JBPM-9504](https://issues.redhat.com/browse/JBPM-9504)
https://github.com/kiegroup/droolsjbpm-integration/pull/2339
https://github.com/kiegroup/droolsjbpm-knowledge/pull/489

[JBPM-9504] Exception on unDeploy at KafkaServerExtension

---

jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java

**JIRA**: [JBPM-9546](https://issues.redhat.com/browse/JBPM-9546)
Added jira scenarios to tests

[JBPM-9546] Add tests for BusinessCalendar Calculations

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManager.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineInitlializer.java

Jira :https://issues.redhat.com/browse/JBPM-9590

[JBPM-9590] Lazy loading runtime engine can cause not unlock the kie session id during disposal

---

jbpm-services/jbpm-services-api/src/build/revapi-config.json

**JIRA:** [BAQE-1696](https://issues.redhat.com/browse/BAQE-1696)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1585

BAQE-1696 - Change revapi to check against 7.48.0.Final

---

jbpm-test/src/main/java/org/jbpm/test/services/AbstractCaseServicesTest.java

**JBPM-9377**: _Should add TaskEventListeners into AbstractCaseServicesTest_ 
[link](https://issues.redhat.com/browse/JBPM-9377)
<details>
<summary>
Added TaskEventListeners into AbstractCaseServicesTest
</summary>
</details>

JBPM-9377: Added TaskEventListeners into AbstractCaseServicesTest

---

jbpm-flow-builder/src/main/java/org/jbpm/assembler/AbstractProcessAssembler.java

@danielezonca @afalhambra  @jiripetrlik
See https://issues.redhat.com/browse/JBPM-9643
Scope of this PR is to allow is to remove deprecated method.
A fix has already been made with https://github.com/kiegroup/droolsjbpm-knowledge/pull/508 but FDB take too much time.
This is an attempt to speed up resolution.
In my local machine I started full clean install and I've successfully  gone past the module that was failing, but the full build takes hours.
@jiripetrlik I'm not sure if you are the QE responsible for this project :smile:

[JBPM-6943] Renamed deprecated method inside AbstractProcessAssembler

---

jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
jbpm-flow/src/main/java/org/jbpm/workflow/core/node/ActionNode.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/ActionNodeInstance.java
jbpm-test-coverage/src/test/java/org/jbpm/test/regression/subprocess/IntermediateEventSubprocessCatchTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/subprocess/IntermediateEventSubprocessCatch.bpmn2

Jira: https://issues.redhat.com/browse/JBPM-9632
To avoid problems with the action nodes (intermediate throw) I added a new metadata for the node
"executeActionAfterComplete" when is set to true the signal is process after finishing processing the current flow.(like a passthrough)

[JBPM-9632] Intermediate Throw event signal stops processing workflow before signal is processed.

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/PotOwnerTasksPreprocessor.java

Comparison to remove the ID column should be case sensitive. Constant is
upper case and column names in pgsql/mysql are lower case. This causes
the ID column to be grouped, which leads to redundant rows that makes
the test fails
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9650)

[JBPM-9650] Potential owners of tasks retrieved by query don't match expected owners

---

jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/VariableScope.java
jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataType.java
jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/BooleanDataType.java
jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/EnumDataType.java
jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/FloatDataType.java
jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/IntegerDataType.java
jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java
jbpm-flow/src/main/java/org/jbpm/process/instance/AbstractProcessInstanceFactory.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/ExtendedNodeInstanceImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/ForEachNodeInstance.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java

**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9641)
https://github.com/kiegroup/droolsjbpm-integration/pull/2419

[JBPM-9641] Convert process variable to right data type

---

jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java
jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/objects/TestWorkItemHandler.java
jbpm-bpmn2/src/test/resources/BPMN2-MultiInstanceLoopHumanTaskWithBoundaryTimer.bpmn2
jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProcessInstanceMarshaller.java
jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java
jbpm-flow/src/main/java/org/jbpm/marshalling/impl/JBPMMessages.java
jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/ExtendedNodeImpl.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java
jbpm-flow/src/main/resources/org/jbpm/marshalling/jbpmmessages.proto
jbpm-test-util/src/main/java/org/jbpm/test/listener/process/DefaultCountDownProcessEventListener.java

register boundary events for multiple instance loop.

[JBPM-9002] no catching timer for parallel task or subprocess

---

jbpm-flow-builder/pom.xml

- Moving drools-mvel test-jar dependency to drools-legacy-test-util test-jar dependency
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6231
<details>
<summary>
</summary>
</details>

[DROOLS-6231] Review drools-mvel test leftovers : 2nd round

---

pom.xml

jbpm-test-util is already present in the [jbpm-bom](https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/9ceebd82ff4d03bd14bd8db38463d7c8fd8adcef/jbpm-bom/pom.xml#L643-L653).
[JBPM-9698](https://issues.redhat.com/browse/JBPM-9698)
<details>
<summary>
</summary>
</details>

JBPM-9698 - Remove jbpm-test-util from dependencyManagement section

---

jbpm-audit/src/main/java/org/jbpm/process/audit/variable/ProcessIndexerManager.java

Jira: https://issues.redhat.com/browse/JBPM-9645

[JBPM-9645] Creating ProcessIndexerManager can cause NullPointerException

---

jbpm-test-util/src/main/java/org/jbpm/test/persistence/util/PersistenceUtil.java

**[JBPM-9711](https://issues.redhat.com/browse/JBPM-9711)**: JbpmJUnitBaseTestCase no longer uses default datasource properties
referenced pull requests: https://github.com/kiegroup/jbpm-work-items/pull/181, https://github.com/kiegroup/kie-jpmml-integration/pull/52

[JBPM-9711] JbpmJUnitBaseTestCase no longer uses default datasource properties

---

jbpm-flow/pom.xml
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
jbpm-flow/src/test/java/org/jbpm/workflow/instance/node/RuleSetInstanceTest.java

ClassCastException occurs when mapping DMN output to a Java Object in a BPMN
**JIRA**: 
[JBPM-9452](https://issues.redhat.com/browse/JBPM-9452)
I created a minimal, reproducible example [here](https://github.com/Optum/kie-examples/tree/master/1) and verified this fixes the issue. I didn't see any unit tests for the `RuleSetNodeInstance` class so I wasn't sure what would be the best way to get an automated test in place for this. If you think we need one, I'd be happy to work on that and I'd appreciate some guidance to point me in the right direction.
<details>
<summary>
</summary>
* <b>a full …

[JBPM-9452] ClassCastException fix

---

jbpm-test-coverage/src/test/java/org/jbpm/test/JbpmTestCase.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/BusinessRuleTaskTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildPersonCollectionDecision.dmn
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildPersonDecision.dmn
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/businessRuleCollectionTaskProcess.bpmn2
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/businessRuleTaskProcess.bpmn2
jbpm-workitems/jbpm-workitems-bpmn2/pom.xml
jbpm-workitems/jbpm-workitems-bpmn2/src/main/java/org/jbpm/process/workitem/bpmn2/AbstractRuleTaskHandler.java
jbpm-workitems/jbpm-workitems-bpmn2/src/main/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskHandler.java
jbpm-workitems/jbpm-workitems-bpmn2/src/main/java/org/jbpm/process/workitem/bpmn2/DecisionTaskHandler.java
jbpm-workitems/jbpm-workitems-bpmn2/src/main/java/org/jbpm/process/workitem/bpmn2/TypeTransformer.java
jbpm-workitems/jbpm-workitems-bpmn2/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskTest.java
jbpm-workitems/jbpm-workitems-bpmn2/src/test/java/org/jbpm/process/workitem/bpmn2/TypeTransformerTest.java
jbpm-workitems/jbpm-workitems-bpmn2/src/test/java/org/jbpm/process/workitem/bpmn2/objects/Person.java

Jira: https://issues.redhat.com/browse/JBPM-9774

[JBPM-9774] Incorrect object type returned in a DMN business-rule task of a BPMN

---

jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/support/JbpmMetadataContributor.java
jbpm-persistence/jbpm-persistence-jpa/src/main/resources/META-INF/services/org.hibernate.boot.spi.MetadataContributor

**[JBPM-9782](https://issues.redhat.com/browse/JBPM-9782)**: Fix missing service loader for automatically activate disable count check

[JBPM-9782] - Fix missing service loader for automatically activate disable count check

---

jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/java/org/jbpm/event/emitters/kafka/KafkaEventEmitter.java

Signed-off-by: desmax74 <mdessi@redhat.com>
See:https://issues.redhat.com/browse/JBPM-9716
Wrong bootstrap servers property in the Kafka Emitter

[7.52.x][JBPM-9716]Wrong bootstrap property in the Kafka Emitter

---

jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/java/org/jbpm/event/emitters/kafka/KafkaEventEmitter.java

See: https://issues.redhat.com/browse/JBPM-9716
Signed-off-by: desmax74 <mdessi@redhat.com>
<details>
<summary>
</summary>
</details>

[JBPM-9716] Wrong bootstrap property in the Kafka Emitter

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/UserTaskServiceImpl.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
jbpm-services/jbpm-services-api/src/build/revapi-config.json
jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/UserTaskService.java

Bulk method implementation.
I followed the same approach that was used for other bulk methods,
meaning that any not id found exception is ignored.
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9786)
https://github.com/kiegroup/droolsjbpm-integration/pull/2518

[JBPM-9786] Add REST Endpoint for claiming tasks in bulk

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java

**JIRA**: 
[https://issues.redhat.com/browse/JBPM-9685](https://issues.redhat.com/browse/JBPM-9685)
In order to allow queries based on tasks by Date ranges I have added support for the following filters:
* GREATER_THAN
* GREATER_OR_EQUAL_TO
* LOWER_THAN
* LOWER_OR_EQUAL_TO
* BETWEEN
That will allow queries of this type:
```
new QueryParam("createdon", "BETWEEN", List.of(new Date(1616751677400L), new Date(1616751677500L)))
```

[JBPM-9685] Add support for Date ranges

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/ExecuteSQLQueryCommandTest.java

**[JBPM-9796](https://issues.redhat.com/browse/JBPM-9796)**: Adding unit test for ExecuteSQLQueryCommand job command

[7.52.x][JBPM-9796] - Adding unit test for ExecuteSQLQueryCommand job command

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/ExecuteSQLQueryCommandTest.java

**[JBPM-9796](https://issues.redhat.com/browse/JBPM-9796)**: Adding unit test for ExecuteSQLQueryCommand job command

[JBPM-9796] - Adding unit test for ExecuteSQLQueryCommand job command

---

jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/mysql5-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/task_assigning_tables_mysql.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/task_assigning_tables_mysql_innodb.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.58-to-7.59-task_assigning_tables.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.58-to-7.59.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.11-to-7.12-task_assigning_tables.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.11-to-7.12.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/jbpm-7.58-to-7.59-task_assigning_tables.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/jbpm-7.58-to-7.59.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.11-to-7.12-task_assigning_tables.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.11-to-7.12.sql
jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/DDLScriptsTest.java
jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/UpgradeScriptsTest.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/ScriptsBase.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/TestPersistenceContextBase.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/ScriptFilter.java

**[JBPM-9746](https://issues.redhat.com/browse/JBPM-9746)**: Precision time (milliseconds) for datime columns should be taken into account for MySQL and MariaDB

[JBPM-9746] Precision time (milliseconds) for datime columns should be taken into account for MySQL and MariaDB

---

jbpm-event-emitters/jbpm-event-emitters-kafka/src/test/java/org/jbpm/event/emitters/kafka/KafkaEventEmitterTest.java

**JIRA**:  [BAPL-2054](https://issues.redhat.com/browse/BAPL-2054)
Update Kafka to version 2.8.0
PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1714
- https://github.com/kiegroup/droolsjbpm-integration/pull/2568
- https://github.com/kiegroup/jbpm/pull/1996
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
* <b>an upstream build</b> please …

 [BAPL-2054] Update MockProducer usage related to Kafka 2.8.0 upgrade

---

jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WorkItemHeaderInfo.java
jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/util/WorkItemHeaderUtils.java
jbpm-workitems/jbpm-workitems-core/src/test/java/org/jbpm/process/workitem/core/util/WorkItemHeaderUtilsTest.java
jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
jbpm-workitems/jbpm-workitems-webservice/src/test/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandlerTest.java

Supporting `WebServiceWorkItemHandler` parameters of the form HEADER_xxxx and HEADER_xxxx_NS, where xxxx is the name of the header and value is the content and the namespace of the soap header to be added
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9738)
https://github.com/kiegroup/droolsjbpm-integration/pull/2566

[JBPM-9738] Adding support for headers in WebServiceWorkItemHandler

---

jbpm-workitems/jbpm-workitems-bpmn2/pom.xml

**JIRA**:  [JBPM-9878](https://issues.redhat.com/browse/JBPM-9878)

[JBPM-9878] Missing jakarta dependency for jdk11 workitems-bpmn2 tests

---

jbpm-workitems/jbpm-workitems-bpmn2/pom.xml

**JIRA**: [JBPM-9878](https://issues.redhat.com/browse/JBPM-9878)
Backport from 1e672680de770a5e766f8e97f9dfdeea68a649e5

[7.59.x][JBPM-9878] Missing jakarta dependency for jdk11 workitems-bpmn2 tests

---

jbpm-flow/src/main/java/org/jbpm/process/core/async/AsyncSignalEventCommand.java
jbpm-flow/src/test/java/org/jbpm/process/core/async/AsyncSignalEventCommandTest.java
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/wih/AsyncWorkItemHandlerCmdCallback.java

Jira: https://issues.redhat.com/browse/JBPM-9969

[JBPM-9969] failure to create AsyncSignalEventCommand through REST API

---

jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcess.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/event/StartEventTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/StartEvent-MultipleTimers.bpmn2

Jira: https://issues.redhat.com/browse/JBPM-9961

[JBPM-9961] Process with multiple timer startNodes only triggers one

---

jbpm-flow/src/main/java/org/jbpm/process/core/timer/GlobalSchedulerService.java
jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java

Jira: https://issues.redhat.com/browse/JBPM-9915
cherry-pick: https://github.com/kiegroup/jbpm/commit/0f229c0097ba4c06cfc7b0667fefa48593b011c9

(GSS) [7.59.x] [JBPM-9915] EJBTimerScheduler.localCache contains entries from already fired timers

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/ProcessServiceImpl.java

Jira: https://issues.redhat.com/browse/JBPM-9928
cherry-pick https://github.com/kiegroup/jbpm/commit/6314dd2a4ef9bc4a27724d4724f86ceac2f1f04d

(GSS) [7.59.x] [JBPM-9928] ProcessServiceImpl.getAvailableSignals should obtain ProcessInstance in read-only mode to avoid race condition

---

jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/AbstractEJBServicesTest.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/HumanTaskConfigurator.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/InitDeadlinesCommand.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskDeadlinesServiceImpl.java
jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/Taskorm.xml
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeManagerFactoryImpl.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/SingletonRuntimeManager.java
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/AbstractDeploymentDescriptorTest.java
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/TimerMigrationManagerTest.java
jbpm-runtime-manager/src/test/java/org/jbpm/test/util/AbstractBaseTest.java
jbpm-services/jbpm-executor/src/test/java/org/jbpm/test/util/AbstractExecutorBaseTest.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractDeploymentService.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/ConcurrentGlobalTimerServiceTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalTimerServiceBaseTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalTimerServiceVolumeTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/InMemoryTimerPersistenceTest.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/SerializedTimerRollbackTest.java
jbpm-test/src/main/java/org/jbpm/test/JbpmJUnitBaseTestCase.java
jbpm-test/src/main/java/org/jbpm/test/services/AbstractCaseServicesTest.java
jbpm-test/src/main/java/org/jbpm/test/services/AbstractKieServicesTest.java

[JBPM-9920] Loading only the timers of the initialized deployment
Trying to avoid call to dispose in tests
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9920)

[7.59.x] [JBPM-9920] Avoiding race condition between deployment and timer

---

jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/commands/ListTimersCommand.java

Jira: https://issues.redhat.com/browse/JBPM-10005

[JBPM-10005] Add suspendUntil timer to getTimers call

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/JAASUserGroupCallbackImpl.java

Jira: https://issues.redhat.com/browse/JBPM-10039

[JBPM-10039] Incorrect groups are returned when "org.kie.server.bypass.auth.user" is set and JAASUserGroupCallbackImpl is used

---

jbpm-audit/src/main/java/org/jbpm/process/audit/JPAAuditLogService.java
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/LogCleanupCommand.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/LogCleanupCommandTest.java

Rescheduling command automatically if suspecting there might be more
records to delete when records per transaction is set
ProcessInstanceLog deletion are saved for the latests transaction, since the subqueries depends on them
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-10037)

[JBPM-10037] LogCleanupCommnand and records per transation

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/AddTaskCommand.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskInstanceServiceImpl.java
jbpm-test-coverage/src/test/java/org/jbpm/test/regression/task/HumanTaskTest.java

Moving the activate event triggering code inside addTask. This should generate a valid sequence. 
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-10065)

[JBPM-10065] Triggering task activated event in a different way

---

jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/ProcessServiceImplTest.java
jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/DateVariableTestProcess.bpmn
jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/MIProcess.bpmn

* JBPM-10112: Expand class name of fundamental java classes if not defined as FQCN to address org.xmlpull.v1.XmlPullParserException in VariableScope.validateVariable
* JBPM-10112: Handle date variable validation
* JBPM-10112: Remove cast to avoid ClassCastException

[7.67.x][JBPM-10112] Fix org.xmlpull.v1.XmlPullParserException in VariableScope.validateVariable (#2200)

---

jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/ProcessServiceImplTest.java
jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/DateVariableTestProcess.bpmn
jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/MIProcess.bpmn

* JBPM-10112: Expand class name of fundamental java classes if not defined as FQCN to address org.xmlpull.v1.XmlPullParserException in VariableScope.validateVariable
* JBPM-10112: Handle date variable validation
* JBPM-10112: Remove cast to avoid ClassCastException

[7.67.x-blue][JBPM-10112] Fix org.xmlpull.v1.XmlPullParserException in VariableScope.validateVariable (#2200)

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/JAASUserGroupCallbackImpl.java

Backport of https://github.com/kiegroup/jbpm/pull/2125/commits/b675883ae8778ff23dc7c390461cc47361af6cd8

[7.67.x-blue][JBPM-10039] Incorrect groups are returned when "org.kie.server.bypass.auth.user" is set and JAASUserGroupCallbackImpl is used

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/JAASUserGroupCallbackImpl.java

Backport of https://github.com/kiegroup/jbpm/pull/2125/commits/b675883ae8778ff23dc7c390461cc47361af6cd8

[7.67.x][JBPM-10039] Incorrect groups are returned when "org.kie.server.bypass.auth.user" is set and JAASUserGroupCallbackImpl is used

---

jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/JPATaskLifeCycleEventListener.java
jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/TaskImpl.java

**JIRA**: _(https://issues.redhat.com/browse/RHPAM-4445)_

[7.67.x-blue] [RHPAM-4445] Unable to update the task description with long string(more than 255 chars)

---

jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/CDataWriterInterceptor.java
jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/CDataXMLStreamWriter.java
jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java

**JIRA**: [JBPM-10118](https://issues.redhat.com/browse/JBPM-10118)
Related test:  
* https://github.com/kiegroup/droolsjbpm-integration/pull/2858
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in …

[JBPM-10118] Wrap into CDATA to avoid escape chars in SOAP headers

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManager.java
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManagerTest.java
jbpm-runtime-manager/src/test/resources/signal-test.bpmn

**JIRA**: [JBPM-10139](https://issues.redhat.com/browse/JBPM-10139)
Without the check, the local map contains two entries for the same RuntimeEngine - one with the caseId as key, the other with the processInstanceId. The entries of the local map are then iterated over in the signalEvent method, which is causing duplicate signals to be sent.

JBPM-10139: Avoid duplicate entries in PerCaseRuntimeManager.local map to avoid multiple signals being sent

---

jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/CaseLogCleanupCommandTest.java

This fixes the following error in the GHA log: WARN  Error during command org.jbpm.casemgmt.impl.audit.CaseLogCleanupCommand error message Unparseable date: "2022-12-01T11:24:25"

Use date format for log cleanup command

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java

**JIRA**: https://issues.redhat.com/browse/JBPM-10144

[JBPM-10144] Flush TimerMappingInfo persist operation early to avoid stale timers

---

jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java

Customer reported a failure on timer involved scenarios. 
Log contains this exception
```
Caused by: org.hibernate.exception.GenericJDBCException: could not prepare statement
at deployment.ROOT.war//org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
at deployment.ROOT.war//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
at deployment.ROOT.war//org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
at deployment.ROOT.war//org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
at deployment.ROOT.war//org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2 …
```

[JBPM-10087] Trying to create new transaction to perform query

---

jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/TimerUpdateTest.java

This basically makes timer id to behave as if singleton strategy was used both for per request and per process instance. 
Thats clearly needed on per request. Singleton remains the same and the only concern might be that know the timer id is globally unique and before, when using per process instance, it was unique per process instance. 
But I think that a per process instance id into a globally unique one should not cause any issue (the contrary is not true)
Changed the approach to use the max process instance timer id if the runtime strategy if not per process instance
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-10172)

[JBPM-10172] Same id used for timers when using per request

---

jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskDeadlinesServiceImpl.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/util/DeadlineSchedulerHelper.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java

[JBPM-10176](https://issues.redhat.com/browse/JBPM-10176)
needs:
-  https://github.com/kiegroup/droolsjbpm-knowledge/pull/641
- https://github.com/kiegroup/drools/pull/5293
Add a TimerJobContext to detect if a job is just created to not look for it in existing timers
The problem is only noticeable if you have lot of timers and creates a new notifications.
The interface allow any other job creating timers to control this behaviour.

[JBPM-10176] Detect creation of timers for notifications

---

jbpm-flow/pom.xml

Jira : https://issues.redhat.com/browse/KOGITO-9500
Decalred pmml-model as optional as  the below dependencies are unsupported  in SWF.
org.jpmml:pmml-model:jar:1.5.1:compile
org.jpmml:pmml-agent:jar:1.5.1:compile

[KOGITO-9500] - Remove pmml dependencies from SWF

---

jbpm-services/jbpm-executor/pom.xml
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/LogCleanupCommand.java
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/LogCleanupCommandTest.java
jbpm-services/jbpm-executor/src/test/resources/byteman-scripts/simulateSlowLogCleanupCommand.btm

When scheduling a LogCleanupCommand with NextRun=1d, the actual execution time for the next run is calculated as (current command execution time + nextRun value). Over time, this can lead to the scheduled execution time to slip, ie. a job scheduled initially at 00:00 gets executed at 00:10, and the execution could be outside of a designated maintenance window.
The expectation is that subsequent executions happen at the defined start time + nextRun value, ie. a job scheduled initially at 00:00 with NextRun=1d should always run at 00:00, regardless of how long it takes to execute it.

[kie-roadmap-119] Scheduled jobs do not keep configured execution time

---

jbpm-flow/src/main/java/org/jbpm/workflow/core/node/WorkItemNode.java
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/MigrationManagerTest.java
jbpm-runtime-manager/src/test/resources/migration/v1/AddTaskAfterActiveExpression-v1.bpmn2
jbpm-runtime-manager/src/test/resources/migration/v2/AddTaskAfterActiveExpression-v2.bpmn2

Issue: 
https://github.com/kiegroup/kie-issues/issues/386

[kie-issues-386] PIM removes dynamic task description of Human Tasks

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java

Original expression needs to be added as it is to external event listeners. This way it can be converted when persisted.

[JBPM-10188] Signaling process instances

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/migration/MigrationManager.java
jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/TimerMigrationManagerTest.java
jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-ProcessSLA-v1.bpmn2
jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-UserTaskSLA-v1.bpmn2
jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-ProcessSLA-v2.bpmn2
jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-UserTaskSLA-v2.bpmn2

Jira: https://github.com/kiegroup/kie-issues/issues/509

[kie-issues-509] Handle SLA timers during process instance migration

---

jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java

**JIRA**: 
[https://issues.redhat.com/browse/JBPM-10203](https://issues.redhat.com/browse/JBPM-10203)

[JBPM-10203] Fixing null pointer exception for cancelActivity

---

jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNode.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/AsyncEventNodeInstance.java

issue: https://github.com/apache/incubator-kie-issues/issues/646

[incubator-kie-issues-646] Duplicate timer created for Task SLA Due date with AsyncMode env setting

---

jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/ProcessInstanceInfo.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java

**JIRA**:  
[link](https://issues.redhat.com/browse/JBPM-10187)
https://github.com/kiegroup/drools/pull/11

[JBPM-10187] Sorting resources to avoid deadlock

---

jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java

This keeps track of the engines that has already being signalled to avoid signalling the same engine twice as part of the same signalEvent call.

[JBPM-10208] Signalling engine only once

---

jbpm-flow/src/main/java/org/jbpm/process/core/DisposableRuntimeEngine.java
jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java
jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/timer/GlobalJpaTimerJobInstance.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java

EJBTimerScheduler bean was using BMT. 
A BTM bean will always suspend the incoming transaction, therefore any operation within the bean, for example, scheduling a timer, will be performed in a different transaction. 
This PR switch back to CMT, removing the risk of a short delay timer colliding with the parent transaction. 
Since CMT was changed to BMT to be able to control delays and recovery when the timer is executed, as an alternative, we use CMT with requires_new to force a new transaction (achieving the same result than by handling UserTransaction). Also, the recoverTimerJobInstance was refactor a bit to make it clear that essentially, whatever the scenario (sessionNotFound, intervalTrigger or failed times) the recovery is executed within another transaction (as the regular call)

[JBPM-10209] Switching to CMT

---

jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java

JIRA: https://issues.redhat.com/browse/RHPAM-4864
Add equals/hashCode methods in order to ensure List.contains works properly.

[private-bamoe-issues#1326] Avoid duplicate timer execution with long running timers and async nodes

---

jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java

https://github.com/apache/incubator-kie-issues/issues/645
trigger the listeners and timer removal event if the timer was not registered in this node.

[incubator-kie-issues-645] potential fix for orphans

---

jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/LogCleanupCommandTest.java
jbpm-services/jbpm-executor/src/test/resources/byteman-scripts/simulateSlowLogCleanupCommand.btm

This is following up on the work from #2292 
The problem with job rescheduling still occurs when 'pagination' exists (There are more records to delete than the 'recordsPerTransaction' parameter). When this happens, in each page it ends up moving the date and time of next execution by not taking into account the date of the first page of the current cycle but using the current one.
This PR addresses the issue by storing the execution time of the original LogCleanupCommand.

[RHPAM-4872] Fix RepeatMode=FIXED when deleted records > RecordsPerTransaction

---

jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/DDLScriptsTest.java

**JIRA**: [JBPM-10195](https://issues.redhat.com/browse/JBPM-10195)
Missing configuration for oracle 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …

[JBPM-10195][oracle] Schema validation exception springboot DDL Scripts

---

README.md

This Pull request fixes Getting started guides links in ReadMe file

Fix links to Getting Started guides in README.md

---

jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/testProcessInstanceThroughEmitter.json
jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/model/ProcessInstanceView.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/IdentityProviderAwareProcessListener.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/audit/ServicesAwareAuditEventBuilder.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/audit/ServicesAwareAuditEventBuilderTest.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/IdentityProviderAwareProcessListenerTest.java
jbpm-test-util/src/main/java/org/jbpm/test/persistence/processinstance/objects/TestEventEmitter.java

**JIRA**: [kie-roadmap#76](https://github.com/IBM/kie-roadmap/issues/76)
WORK-IN-PROGRESS

[kie-roadmap#76] Track user aborting a process instance

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/CompleteTaskCommand.java
jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/TaskContext.java
jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/persistence/TaskTransactionInterceptor.java
jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/TaskCompletedListenersTest.java
jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/HumanTask-simple-with-outputvars.bpmn2

Provide a workaround to get variables values in beforeTaskCompleted listener before they are updated during completing task 
**JIRA**:
[link](https://issues.redhat.com/browse/RHPAM-4446)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/639

[7.67.x-blue] RHPAM-4446: beforeTaskCompletedEvent shows updated value of process vars

---

jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
jbpm-runtime-manager/pom.xml
jbpm-services/jbpm-kie-services/pom.xml

Replaces https://github.com/kiegroup/jbpm/pull/2398

[7.67.x-blue] RHPAM-3709: upgrade maven dependencies to address CVE-2021-26291

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java

**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-10230)

[JBPM-10230] Fix multiple ForEachNodeInstances

---

jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java

If a catch with same event type was created as part of trigger complete, the new catch was signalled. 
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-10233)

[JBPM-10233] Using original list of nodes for dispatching

---

jbpm-flow/src/main/java/org/jbpm/process/instance/impl/CancelNodeInstanceAction.java
jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java

[link](https://issues.redhat.com/browse/JBPM-10234)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code …

[JBPM-10234] CancelNode should be able to cancel more than one instance

---

jbpm-audit/src/main/java/org/jbpm/process/audit/AbstractAuditLogger.java
jbpm-audit/src/main/java/org/jbpm/process/audit/AbstractAuditLoggerAdapter.java
jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
jbpm-audit/src/main/java/org/jbpm/process/audit/event/AuditEventBuilder.java
jbpm-audit/src/main/java/org/jbpm/process/audit/event/DefaultAuditEventBuilderImpl.java
jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogProducer.java
jbpm-flow/src/main/java/org/jbpm/process/instance/command/UpdateTimerCommand.java
jbpm-flow/src/test/java/org/jbpm/process/instance/command/UpdateTimerCommandTest.java
jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/ManagedAuditEventBuilderImpl.java
jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/audit/ServicesAwareAuditEventBuilder.java
jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/audit/ServicesAwareAuditEventBuilderTest.java

(cherry picked from commit 42b3d054b5ad89d4a4babdbc8b631bd0dff2c5ed c563d2517cc675be3322e267bcec5ac306edb8c4)
**JIRA**: [RHPAM-4779](https://issues.redhat.com/browse/RHPAM-4779)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/648
* https://github.com/kiegroup/drools/pull/63
* https://github.com/kiegroup/droolsjbpm-integration/pull/3050
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …

[7.67.x-blue] RHPAM-4779: SLA due date value in ProcessInstanceLog table is not updated after updating process SLA

---

jbpm-db-scripts/src/main/resources/db/ddl-scripts/db2/db2-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/derby/derby-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/h2/h2-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/hsqldb/hsqldb-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/mysql5-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/oracle-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-bytea-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver/sqlserver-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver2008/sqlserver2008-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sybase/sybase-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/db2/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/derby/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/h2/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/hsqldb/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sybase/rhpam-7.13.1-to-7.13.5.sql

Closes: https://github.com/apache/incubator-kie-issues/issues/1049

[incubator-kie-issues#1049] Add index to ProcessInstanceLog table to improve LogCleanupCommand performance

---

jbpm-db-scripts/src/main/resources/db/ddl-scripts/db2/db2-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/derby/derby-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/hsqldb/hsqldb-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/mysql5-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/oracle-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-bytea-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/postgresql-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver/sqlserver-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver2008/sqlserver2008-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/ddl-scripts/sybase/sybase-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/db2/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/derby/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/hsqldb/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/rhpam-7.13.1-to-7.13.5.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sybase/rhpam-7.13.1-to-7.13.5.sql

Removes the index from the scripts for database systems that don't support defining indexes with "where" clause. It is only supported in SQLServer and PostgreSQL.

[7.67.x-blue] [incubator-kie-issues#1049] Add index to ProcessInstanceLog table to improve LogCleanupCommand performance

---

jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/mysql5-jbpm-schema.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.61-to-7.62-TimerMappingInfo.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.72-to-7.73.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.12-to-7.13.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.13-to-7.13.1.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/jbpm-7.72-to-7.73.sql
jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.13-to-7.13.1.sql

- Fixes drop indexes, it needs table specification on MySQL, otherwise it fails. 
- Fixes TimerMappingInfo creation on MySQL, the generated keyword doesn't work on MySQL.

Fix SQL scripts for MySQL.

---

jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/test/java/org/jbpm/services/ejb/timer/EJBTimerSchedulerTest.java

Fix https://issues.redhat.com/browse/JBPM-10242

[JBPM-10242] Allow the possibility of disabling linear search for removeJob and getTimerByName operations

---

jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/LDAPUserGroupCallbackImpl.java

Added case insensitive comparison to fix this [issue](https://issues.redhat.com/browse/JBPM-10238)
Fix-: added a new property "ldap.entity.ignore.case", if set to true, will do case insensitive comparison, default value is false to ensure backward compatibility.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or …

Fix for issue JBPM-10238 adding case insensitive comparison for entity

---

jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/LogCleanupCommand.java
jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java

**JIRA**: _(DBACLD-162578)_ 
This PR will  fix the rescheduling in both scenarios:
Long running LogCleanupCommand
Multiple LogCleanupCommand runs due to RecordsPerTransaction setting

[DBACLD-162578] LogCleanupCommand rescheduling with FIXED delay not working as expected
