kiegroup/jbpm

- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/KjarRuntimeEnvironmentTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/AbstractDeploymentDescriptorTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/MvelResolverDeploymentDescriptorManagerTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/RuntimeManagerWithDescriptorTest.java
- jbpm-test-coverage/pom.xml
@mswiderski this should fix the 3 additional failing tests. I am setting the run order of the jbpm-test-coverage tests to see if that "fixes" the `org.jbpm.test.regression.ParallelAsyncJobsTest.testRunBasicAsync`
> Fix failing tests

- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/KjarRuntimeEnvironmentTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/AbstractDeploymentDescriptorTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/MvelResolverDeploymentDescriptorManagerTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/RuntimeManagerWithDescriptorTest.java
- jbpm-test-coverage/pom.xml
Same as https://github.com/droolsjbpm/jbpm/pull/397 but for 6.4.x
> [6.4.x] fix failing tests

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/TransactionsTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/AsyncTaskTransactionTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jpa/PatientVariablePersistenceStrategyTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/PessimisticLockTasksServiceTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessPersistenceHumanTaskTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/ConcurrentGlobalTimerServiceTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalTimerServiceBaseTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/SerializedTimerRollbackTest.java
PR for this issue: https://issues.jboss.org/browse/JBPM-5045
Master PR: https://github.com/droolsjbpm/jbpm/pull/432
Please merge this. It is needed for 6.3 product testing on supported DBs.
> JBPM-5045 "Try-catch-finally"-zed transaction handling.

- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/DBUserGroupCallbackImplTest.java
- jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/util/PersistenceUtil.java
- jbpm-services/jbpm-executor/pom.xml
- pom.xml
> [BZ-1308925] re-use db config methods (fixes issues with MariaDB)

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalQuartzDBTimerServiceTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalTimerServiceBaseTest.java
> Fix global quartz db timer service test

- jbpm-flow/src/main/java/org/jbpm/process/StatefulProcessSession.java
Releted to https://github.com/droolsjbpm/drools/pull/732
> [DROOLS-1119] fix timers serialization

- jbpm-test-coverage/src/main/java/org/jbpm/test/casemgmt/WorkCaseService.java
As in #451, but in 6.3.x.
Thanks!
> Fix random user generation

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/TxUserTaskServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/tx/child-process-01.bpmn2
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/tx/parent-process-01.bpmn2
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/subprocess/CallActivitiesWithUserTasksProcessTest.java
(cherry picked from commit 801df91557418ad14889edbec7ebefc907ab203f)
> [6.3.x] BZ-1310820 - Can't signal sub process when using the EJB API

- jbpm-workitems/src/main/java/org/jbpm/process/workitem/email/EmailWorkItemHandler.java
I believe this property is called Body, not text.
> Fix javadoc property name

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/TxUserTaskServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/tx/child-process-01.bpmn2
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/tx/parent-process-01.bpmn2
(cherry picked from commit 801df91557418ad14889edbec7ebefc907ab203f)
> [6.4.x] BZ-1310820 - Can't signal sub process when using the EJB API

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/ExceptionWorkItemHandler.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/NoExceptionWorkItemHandler.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByJPATest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/RetrySyncWorkItemByMemoryTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/retry-workitem-jpa.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/retry-workitem-memory.bpmn2
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/parser/ParserWorkItemHandlerTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/rest/BasicAuthRestWorkItemHandlerTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java
@mswiderski Hi, it is update unit test.
please check it.
> JBPM-5084: troubleshooting function for workitem: unit test

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
https://issues.jboss.org/browse/ENTESB-4697
> ENTESB-4967 Different behaviour of DocumentBuilderFactory in Fuse and EAP

- jbpm-workitems/pom.xml
- jbpm-workitems/src/main/java/org/jbpm/process/workitem/jpa/JPAWorkItemHandler.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/jpa/JPAWorkItemHandlerTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/jpa/Product.java
- jbpm-workitems/src/test/resources/JPAWIH.bpmn2
- jbpm-workitems/src/test/resources/META-INF/persistence.xml
- jbpm-workitems/src/test/resources/SampleWorkDefinitions.conf
- jbpm-workitems/src/test/resources/jndi.properties
JBPM-5147 -  Provide a JPA Work Item Handler
> JBPM-5147 -  Provide a JPA Work Item Handler

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/xml/ServicesProcessDataEventListener.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/BPMN2DataServicesTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/QueryServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/humanTask.bpmn
@mrietveld do you mind taking a quick look?
> JBPM-5191 - Task properties doesn't include values - only data types

- jbpm-workitems/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java
Sometime REST services return content type with extra information.
E.g. application/json;charset=utf-8
> Be resilent to complex content type

- jbpm-installer/db/upgrade-scripts/db2/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/db2/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/derby/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/derby/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/h2/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/h2/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/hsqldb/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/hsqldb/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/mysql5/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/mysql5/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/mysqlinnodb/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/mysqlinnodb/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/oracle/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/oracle/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/postgresql/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/postgresql/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/sqlserver/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/sqlserver/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/sqlserver2008/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/sqlserver2008/jbpm-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/sybase/bpms-6.2-to-6.3.sql
- jbpm-installer/db/upgrade-scripts/sybase/jbpm-6.3-to-6.4.sql
@mswiderski Would you mind reviewing?
If possible, please prioritize because (I believe) it's related to the release.
> 6.4.x: JBPM-5186 - Added indexes to update scripts (to improve query performance on VariableInstanceLog and NodeInstanceLog)

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/bpmn2/ProcessDescriptor.java
See org.jbpm.kie.services.impl.xml.ServicesProcessDataEventListener.resolveUnqualifiedClasses()
[Github link to original method](https://github.com/droolsjbpm/jbpm/blob/master/jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/xml/ServicesProcessDataEventListener.java#L215)
which is called [here](https://github.com/droolsjbpm/jbpm/blob/master/jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/xml/ServicesProcessDataEventListener.java#L276)
@mswiderski Would you mind taking a look?
> - removed unused (duplicate) ProcessDescriptor.resolveUnqualifiedClasses method

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/Signal.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EndEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateCatchEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SignalHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/StartEventHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StartEventTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/structureref/StructureRefTest.java
- jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/ProcessBuildData.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/bpmn2/BPMN2DataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/bpmn2/ProcessDescriptor.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/ProcessAssetDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/xml/ServicesProcessDataEventListener.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/BPMN2DataServicesReferencesTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/BPMN2DataServicesTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/ProcessServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/logback-test.xml
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/signal.bpmn
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/ProcessDefinition.java
@mswiderski Would you mind taking a look? 
(Or @psiroky, now that you're also working on jBPM? :D )
> GUVNOR-2173 - Asset Oracle: Change Impact prediction -- support for signal and global information

- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- jbpm-flow/src/test/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidatorTest.java
> JBPM-5231: refactored adding errors in RuleFlowProcessValidator

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskVariablesAccessTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/HumanTaskWithVariables.bpmn2
here are the tests for a task variables access inside a whole process.
I will backport it to master in a minute too.
Marian
> [6.5.x] BPMSPL-246 - Add HumanTaskVariablesAccessTest

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskVariablesAccessTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/HumanTaskWithVariables.bpmn2
Same as #542, but for master branch.
Marian
> BPMSPL-246 - Add HumanTaskVariablesAccessTest

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/RuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/RuntimeDataServiceImplTest.java
Related to the 6.3.3 GA release.
> 6.4.x: RHBMS-4188 - Unable to use LATEST in process image REST endpoint

- jbpm-human-task/jbpm-human-task-core/src/main/resources/operations-dsl.mvel
I have removed unnecessary permission from `operations-dsl.mvel`.
> JBPM-5283 - Remove actual owner from roles allowed to activate tasks

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/CompositeCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/GetTasksByGroupCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskQueryServiceImpl.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/command/CommandBasedTaskService.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/LifeCycleBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/TaskQueryServiceBaseTest.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/Taskorm.xml
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/task/SynchronizedTaskService.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/main/java/org/jbpm/services/ejb/impl/TaskServiceEJBImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskQueryFilterTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/TaskSubjectAndDescriptionTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/task/HumanTaskAssignmentTest.java
PR Set: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/160
- https://github.com/droolsjbpm/jbpm/pull/560
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/605
> [6.5.x] RHBPMS-4184,JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/CompensationTest.java
- jbpm-bpmn2/src/test/resources/compensation/BPMN2-BookResource.bpmn2
- jbpm-bpmn2/src/test/resources/compensation/BPMN2-Booking.bpmn2
- jbpm-bpmn2/src/test/resources/compensation/BPMN2-CancelResource.bpmn2
Added and modified files to make Compensation Event work with Reusable Subprocess (https://issues.jboss.org/browse/JBPM-5295)
> [JBPM-5295] Compensation Events with Reusable Subprocesses

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/migration/MigrationManager.java
@sutaakar and here is back port to 6.5.x
> [6.5.x] RHBPMS-4249, JBPM-5319 - Transaction exception for Per Process Instan…, RHBPMS-4247, JBPM-5317 - Failed to upgrade process instances in Maria

- jbpm-installer/src/main/resources/auth/users.properties
- jbpm-installer/src/main/resources/standalone-eap-7.0.0.xml
- jbpm-installer/src/main/resources/standalone-full-eap-7.0.0.xml
- jbpm-installer/src/main/resources/standalone-full-wildfly-10.0.0.Final.xml
- jbpm-installer/src/main/resources/standalone-wildfly-10.0.0.Final.xml
Please see https://github.com/droolsjbpm/jbpm/pull/585. This is same fix for master branch. Thanks!
> JBPM-5082: Added users management configurations for the jbpm installer.

- jbpm-installer/db/upgrade-scripts/db2/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/db2/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/derby/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/derby/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/h2/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/h2/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/hsqldb/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/hsqldb/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/mysql5/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/mysql5/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/mysqlinnodb/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/mysqlinnodb/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/oracle/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/oracle/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/postgresql/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/postgresql/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/sqlserver/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/sqlserver/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/sqlserver2008/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/sqlserver2008/jbpm-6.4-to-6.5.sql
- jbpm-installer/db/upgrade-scripts/sybase/bpms-6.3-to-6.4.sql
- jbpm-installer/db/upgrade-scripts/sybase/jbpm-6.4-to-6.5.sql
Replaced Java comments with SQL comments.
Master PR: https://github.com/droolsjbpm/jbpm/pull/599
> JBPM-5325 Replaced Java comments with SQL comments in .sql files.

- jbpm-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-container-test-suite/src/test/resources/arquillian/websphere85x/arquillian.xml
Hi,
I have made a slight change in jBPM container tests to be able to run these tests with our (QA) Cargo automation.
Thanks,
Marián
> Change Cargo profile location in container tests

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/BusinessAdminTasksPreprocessor.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/DeploymentIdsPreprocessor.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/PotOwnerTasksPreprocessor.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/query/preprocessor/PotOwnerTasksPreprocessorTest.java
Included logging for debugging pre-processor filters
> JBPM-5351 - Fix missing logged in user id in organizational entity list

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/AbstractRuntimeEJBServicesTest.java
- jbpm-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/ejbcompl/EThreadInfoTest.java
- jbpm-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/tx/ETransactionTest.java
- jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/AgendaFilterTest.java
- jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ExecutionFlowControlTest.java
- jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessFlowControlTest.java
- jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessMarshallingTest.java
- jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessRuleFlowGroupTest.java
- jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessUpgradeTest.java
- jbpm-flow-builder/src/test/java/org/jbpm/test/util/AbstractBaseTest.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/event/DefaultSignalManager.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/MilestoneNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateNodeInstance.java
- jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/session/PersistentStatefulSessionTest.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/DefaultRegisterableItemsFactory.java
- jbpm-services/jbpm-services-cdi/src/main/java/org/jbpm/services/cdi/impl/manager/InjectableRegisterableItemsFactory.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/FireUntilHaltTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/RuleTaskTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/SessionIsolationTest.java
@mariofusco here are the changes we talked about
@krisv we need to talk about this as it quite a lot change the business rule task - it makes it sync/no wait state which essentially it was anyway in v6 as we always triggered it via listener (rule flow group activated calls fireAllRules).
> DROOLS-987 - Errors in Phreak under heavy and multi threaded load

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskVariablesAccessTest.java
Hi @mswiderski,
here is the proposed PR. Although the tests have been passing, there was a 'No transaction running' exception, but it should be OK now.
Marián
> Fix HumanTaskVariablesAccessTest

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskVariablesAccessTest.java
> [6.5.x] Fix HumanTaskVariablesAccessTest

- jbpm-container-test/jbpm-container-test-suite/src/main/java/org/jbpm/test/container/tools/IntegrationMavenResolver.java
> Remove unused property for Maven resolver

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IncrementalCompilationTest.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcess.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- Fixed concurrency issue in RuleFlowProcessValidator. 
- Removed duplicite start and end nodes validation => Fixed IncrementalCompilationTest.
@mswiderski please, verify my changes. Thanks. (I am sorry for formatting changes)
> JBPM-5369 RHBPMS-4369 Could not parse knowledge when creating RuntimeManager concurrently

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-EventSubprocessSignalExpression.bpmn2
- jbpm-flow/src/main/java/org/jbpm/process/core/event/EventFilter.java
- jbpm-flow/src/main/java/org/jbpm/process/core/event/EventTypeFilter.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/EventNodeInterface.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/EventSubProcessNode.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventSubProcessNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/TimerNodeInstance.java
@krisv it was relatively easy to fix and might become handy, wdyt?
> JBPM-5363 - Evaluation of variable expressions in subprocesses

- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/utils/CollectionUtils.java
This PR changes CollectionUtils.equals method so that it has a time complexity of O (nlogn) opposed to previous version O(n^2)
It also corrects hashCode to make sure the contract for hashCode/equals is valid (if equals is true, hashCode should be the same)
> Added CollectionUtils performance fix

- jbpm-installer/src/main/resources/db/upgrade-scripts/sqlserver2008/bpms-6.0-to-6.1.sql
- jbpm-installer/src/main/resources/db/upgrade-scripts/sqlserver2008/jbpm-6.0-to-6.1.sql
- jbpm-installer/src/main/resources/db/upgrade-scripts/sqlserver2008/jbpm-6.1-to-6.2.sql
- Replaced numeric(19,0) with bigint.
> JBPM-5396 RHBPMS-4443 SQL upgrade scripts contain numeric(19,0) datatype instead of bigint

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
@sutaakar and here is the master ...
> JBPM-5398 - Transaction issues with Timer catch event

- jbpm-services/jbpm-shared-services/pom.xml
See https://github.com/droolsjbpm/jbpm/pull/673
> DROOLS-1353: remove unused dependency

- jbpm-services/jbpm-services-api/pom.xml
Hi, @psiroky,
same as droolsjbpm/droolsjbpm-knowledge#189.
Thanks.
Marian
> Include nonBreaking changes in revapi report

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/DroolsDeclaredTypeSequenceFlowExpressionTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-DroolsDeclaredTypeSequenceFlowExpressionTest.bpmn2
Test which was forgotten to cherry pick from master to 6.5.x
(cherry picked from commit 9f2a47e)
> [DROOLS-1327] test that uses Drools declared types in sequence flow expression.

- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseRuntimeDataService.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/resources/META-INF/CaseMgmtorm.xml
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
> JBPM-4646 - Case management - get tasks for cases as stakeholder

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/UserTaskCaseBoundary.bpmn2
@krisv here is the fix for boundary events to not be seen as ad hoc fragments
> JBPM-4646 - Case management - boundary events are not ad hoc fragments

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
@sutaakar same for 6.5.x branch
> [6.5.x] JBPM-5398 - Transaction issues with Timer catch event

- jbpm-services/jbpm-services-api/pom.xml
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
Hello,
I have made a small change in a revapi config before upgrading it to 0.8.0. Please do not merge it yet.
Thanks,
Marian
> Add revapi filter

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/marshalling/CaseFileInstanceMarshallingStrategy.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/model/instance/CaseFileInstanceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseFileConditionalEvent.bpmn2
depends on https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/202
> JBPM-5541 - Case file conditional event fails other cases

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManager.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManagerTest.java
ExcludedOwners can no longer execute operations on tasks (unless they are also a Business Administrator of the task).
> Fixes JBPM-5610

- pom.xml
Please merge after PR https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/382 has been merged.
> Move findbugs configuration to kie-parent

- jbpm-flow/pom.xml
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
jbpm alignment accordingly to droolsjbpm/kie-dmn#41 .
> DROOLS-1434: moving DMN public interfaces to kie-dmn-api module

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/CompositeCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/GetUserTaskCommand.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/commands/GetUserTaskCommandTest.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/form/FormProviderServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/form/FormProviderServiceImplTest.java
- jbpm-services/jbpm-services-cdi/src/main/java/org/jbpm/services/cdi/impl/form/FormProvidesServiceCDIImpl.java
@mswiderski can you take a look?
This PR should be merged with:
- https://github.com/droolsjbpm/jbpm-wb/pull/633
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/828
> RHBPMS-4576: A user can display tasks for which he is not Potential Owner or Bussines Admin

- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/java/AbstractJavaProcessBuilder.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/java/JavaActionBuilder.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/java/JavaProcessDialect.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/java/JavaReturnValueEvaluatorBuilder.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/AbstractMVELBuilder.java
@mariofusco @tarilabs could you please take a look at this guys? I don't know if I got the adjustments right...
> DROOLS-1446 - ruleunit implementation - jbpm adjustments

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/CommonUtils.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/RuntimeDataServiceImpl.java
@sutaakar do you mind verifying this on 6.5 bits before merging?
> [6.5.x] RHBPMS-4638 - SQLGrammarException when retrieving user tasks

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/org/jbpm/test/container/archive/localtransactions/tomcat-context.xml
Hi, @psiroky,
here is the change we spoke about recently. Please merge it after the tests are OK.
Thanks,
Marián
> Change Java delegation model from parent-first to parent-last

- jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
(cherry picked from commit 136f49d60b8562e1a1f6d3ff5c47cec1be86f498)
> [6.5.x] RHBPMS-4597 - ksession leak with Timer+Loop+PerProcessInstance

- jbpm-installer/src/main/resources/build.xml
> JBPM-5765: Update installer to latest eclipse Neon and BPMN2 Modeler

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAAuditLogService.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/query/AbstractAuditDeleteBuilderImpl.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/query/NodeInstanceLogDeleteBuilderImpl.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/query/VarInstanceLogDeleteBuilderImpl.java
- jbpm-audit/src/test/java/org/jbpm/process/audit/query/AuditDeleteTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StartEventTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/objects/Person.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/persistence/TimerCycleOnBinaryPackageTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/process/audit/command/AuditCommandsTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-IntermediateCatchEventConditionPI.bpmn2
- jbpm-bpmn2/src/test/resources/BPMN2-IntermediateCatchEventSignal.bpmn2
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/service/AuditTaskDeleteBuilderImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/service/TaskEventDeleteBuilderImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/service/TaskJPAAuditService.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/AuditTaskDeleteTest.java
- jbpm-human-task/jbpm-human-task-audit/src/test/resources/META-INF/persistence.xml
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/TaskQueryServiceBaseTest.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/query/TaskSummaryImpl.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/Taskorm.xml
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/LogCleanupCommand.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/CleanupLogCommandWithProcessTest.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/TaskSummaryQueryMapper.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/query/QueryResultMapper.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/TaskLogCleanTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/TaskSubjectAndDescriptionTest.java
depends on https://github.com/kiegroup/drools/pull/1159
> [6.5.x] Backports for rollup 6.4.3

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
@rsynek could you please review? This should fix the test failures seen in the nightly builds.
> Container test fixes

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
- jbpm-container-test/pom.xml
@MarianMacik could you please take a look?
> Run container tests only when container profile is used

- jbpm-flow/src/test/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidatorTest.java
@mswiderski adding two asserts per @psiroky comment here: https://github.com/kiegroup/jbpm/pull/814
I amended the same to the 7.0.x PRs for this Jira. 
sorry for the inconvenience thanks.
> JBPM-5891 - updating tests

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/DateTimeUtils.java
- jbpm-flow/src/test/java/org/jbpm/process/core/timer/DateTimeUtilsTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/ConcurrentGlobalTimerServiceTest.java
@mswiderski The fix I promised.
> JBPM-5886: Add support for ISO_8601 repeating intervals

- jbpm-runtime-manager/pom.xml
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/TimerInitFailureRuntimeManagerTest.java
this is the same PR as #821, but for master.
Thanks,
Marian
> Fix Byteman test for IBM Java

- jbpm-runtime-manager/pom.xml
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/TimerInitFailureRuntimeManagerTest.java
this is the same PR as #821, but for 7.0.x.
Thanks,
Marian
> [7.0.x] Fix Byteman test for IBM Java

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
same as #841, but for 7.0.x.
Marian
> [7.0.x.] Change revapi-config.json comment to be more general

- jbpm-workitems/pom.xml
- jbpm-workitems/src/main/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskHandler.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskHandlerTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/bpmn2/objects/Person.java
- jbpm-workitems/src/test/java/org/jbpm/test/util/TestWorkItemManager.java
- jbpm-workitems/src/test/resources/0020-vacation-days.dmn
- jbpm-workitems/src/test/resources/businessRule.drl
- jbpm-workitems/src/test/resources/businessRule2.drl
- jbpm-workitems/src/test/resources/businessRuleTaskDMN.bpmn2
- jbpm-workitems/src/test/resources/businessRuleTaskProcess.bpmn2
details what it does can be found [here](http://mswiderski.blogspot.com/2017/04/control-business-rules-execution-from.html)
> JBPM-5923 - Business rule work item handler

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/assignment/impl/strategy/LoadBalanceAssignmentStrategy.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/assignment/LoadBalanceAssignmentStrategyTest.java
Extends test of current LoadBalanceAssignmentStrategy
Fixes a bug where users in excluded groups wouldn't appear in excluded user list and ended up still being assigned.
> JBPM-5842: Add more LoadBalanceStrategy test coverage

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/BPMN2XMLTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-XMLProcessWithErrorInCompositeNode.bpmn2
- jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/XmlProcessReader.java
adding so can align with the 6.5.x pr https://github.com/kiegroup/jbpm/pull/854
(added the parent lookup there as well per kris request)
> RHBPMS-4480 - Improve ExtensibleXmlParser logging - adding parent node lookup

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
Hi, @psiroky,
I have cleaned revapi ignores since we have a new Final version.
Marian
> Clean revapi-config after 7.0.0.Final release

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/QueryServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/QueryServiceImplTest.java
@sutaakar this is what we talked about today.
@tsurdilo do you mind to review?
> JBPM-6122 - Query is registered even when processing fails

- jbpm-flow-builder/src/main/java/org/jbpm/process/workitem/WorkItemRepository.java
- jbpm-flow/pom.xml
- jbpm-flow/src/main/java/org/jbpm/util/WidMVELEvaluator.java
- jbpm-flow/src/test/java/org/jbpm/util/CarsEnum.java
- jbpm-flow/src/test/java/org/jbpm/util/CustomDataType.java
- jbpm-flow/src/test/java/org/jbpm/util/WidMVELEvaluatorSafeTest.java
- jbpm-flow/src/test/java/org/jbpm/util/WidMVELEvaluatorTest.java
- jbpm-flow/src/test/resources/policy/engine.policy
- jbpm-flow/src/test/resources/policy/kie.policy
- jbpm-flow/src/test/resources/wids/test-backwardscompat.wid
- jbpm-flow/src/test/resources/wids/test-backwardscompatmixedandmissingimports.wid
- jbpm-flow/src/test/resources/wids/test-backwardscompatpkgimport.wid
- jbpm-flow/src/test/resources/wids/test-customdatatype.wid
- jbpm-flow/src/test/resources/wids/test-customdatatypenoimport.wid
- jbpm-flow/src/test/resources/wids/test-noimports.wid
JBPM-6144 - Create a wid specific MVELEvaluator
> JBPM-6144 - Create a wid specific MVELEvaluator

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorRunnable.java
Log Stacktrace in ExecutorRunnable for Exceptions. Otherwise if there is some error then its very difficult to debug.
> Log Stacktrace in ExecutorRunnable for Exceptions

- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/DefaultProcessInstanceManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerRequestRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/factory/InMemorySessionFactory.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/factory/JPASessionFactory.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/factory/InMemorySessionFactoryLeakTest.java
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/244
> RHBPMS-4801 - InMemorySessionFactory has apparent memory leak

- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/DefaultProcessInstanceManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerRequestRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/factory/InMemorySessionFactory.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/factory/JPASessionFactory.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/factory/InMemorySessionFactoryLeakTest.java
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/245
> [6.5.x] RHBPMS-4802 - InMemorySessionFactory has apparent memory leak

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/tx/ETransactionTest.java
here is the fix for the test we spoke about.
Thanks,
Marian
> Stabilize humanTask transaction test on WLS/WAS

- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/assignment/BusinessRuleAssignmentTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/resources/assignments/assignment-rules.drl
Adds 3 test methods to cover some corner cases I came up with.
All of them should pass.
@mswiderski Could you take a look please?
> JBPM-6268: Extend BusinessRule assignment strategy tests

- jbpm-bpmn2/src/main/java/org/jbpm/osgi/bpmn2/Activator.java
- jbpm-bpmn2/src/main/resources/META-INF/kie.conf
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/StartCaseCommand.java
- jbpm-flow-builder/src/main/java/org/jbpm/osgi/flow/compiler/Activator.java
- jbpm-flow-builder/src/main/resources/META-INF/kie.conf
- jbpm-flow/src/main/java/org/jbpm/osgi/flow/core/Activator.java
- jbpm-flow/src/main/java/org/jbpm/process/core/impl/XmlProcessDumperFactory.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/StartProcessHelper.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm-flow/src/main/resources/META-INF/kie.conf
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/osgi/services/task/Activator.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/kie.conf
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/IdentityProviderAwareProcessListenerTest.java
- jbpm-test-coverage/src/main/java/org/jbpm/test/listener/IterableProcessEventListener.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/AbstractWorkItemHandlerTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/bpmn2/JaxWSServiceTaskTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/handler/HandlerTest.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/java/JavaInvokerTest.java
[DROOLS-1649] ServiceRegistry refactor
(cherry picked from commit 6fdc5f069ae958a7ea176637386cf21b3f85a38e)
> [DROOLS-1649] ServiceRegistry refactor (#923)

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractDeploymentService.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/DeactivateDeploymentServiceWithSyncTest.java
> Stabilize DeactivateDeploymentServiceWithSyncTest

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractDeploymentService.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/DeactivateDeploymentServiceWithSyncTest.java
here is the test stabilization we spoke about. Should I create a port to master/7.3.x with LinkedHashSet as well?
Thanks,
Marian
> [6.5.x] Stabilize DeactivateDeploymentServiceWithSyncTest

- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogProducer.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogReceiver.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/store/DeploymentStore.java
(cherry picked from commit c8814aef4061cbf78e5b126f6610c7a6b7204516)
> RHBRMS-2784 - XStream: DoS when unmarshalling void type (#928)

- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogProducer.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogReceiver.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/store/DeploymentStore.java
(cherry picked from commit c8814aef4061cbf78e5b126f6610c7a6b7204516)
(cherry picked from commit 7af6e1f6d0cbd9d54be88bdb70db84e5d809589f)
> [7.3.x] RHBRMS-2784 - XStream: DoS when unmarshalling void type (#928)

- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/test/java/org/jbpm/remote/ejb/test/task/ERestServiceTaskTest.java
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/test/java/org/jbpm/remote/ejb/test/task/ETaskCommentTest.java
> [7.3.x] Fix jbpm-remote-ejb-test

- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/test/java/org/jbpm/remote/ejb/test/task/ERestServiceTaskTest.java
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/test/java/org/jbpm/remote/ejb/test/task/ETaskCommentTest.java
I have made some refinements to Remote EJB tests to support various DBs.
Thanks,
Marian
> Fix jbpm-remote-ejb-test

- jbpm-audit/src/test/java/org/jbpm/process/audit/AuditLogServiceTest.java
- jbpm-audit/src/test/resources/logback-test.xml
- jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/correlation/CorrelationPersistenceTest.java
- jbpm-persistence/jbpm-persistence-jpa/src/test/resources/logback-test.xml
- jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java
- pom.xml
cherry-pick of #959  for 7.3.x
> [7.3.x] JBPM-6309: Investigate and fix jBPM community DB tests with Narayana

- jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/util/PersistenceUtil.java
- jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java
There is an additional problem that appears when running with db2 and
sybase - they have no setURL/setUrl methods, so a guard is added to skip
this piece of code. These DB's driver asks for url in connection so as long as it
is in driverProperties it should be set.
Also adds url property into driverProperties for all
databases.
> JBPM-6309: Additional fixes for DB tests with narayana

- jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/util/PersistenceUtil.java
- jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java
> [7.3.x] JBPM-6309: JBPM-6309: Additional fixes for DB tests with narayana

- jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java
@mswiderski I have made a mistake yesterday, this corrects it. I was invoking a method with int paramater using String.
> JBPM-6309: Fix incorrect type in method invocation

- jbpm-test-util/src/main/java/org/jbpm/test/util/PoolingDataSource.java
> [7.3.x] JBPM-6309: Fix incorrect type in method invocation

- jbpm-document/pom.xml
- jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentImpl.java
- jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentStorageServiceImpl.java
- jbpm-document/src/main/java/org/jbpm/document/service/impl/util/DocumentDownloadLinkGenerator.java
- jbpm-document/src/test/java/org/jbpm/document/service/impl/DocumentImplTest.java
- jbpm-document/src/test/java/org/jbpm/document/service/impl/util/DocumentDownloadLinkGeneratorTest.java
Copy of https://github.com/kiegroup/jbpm/pull/981
@mswiderski @hasys could you take a look?
This is part of an ensemble, merge with:
https://github.com/kiegroup/jbpm/pull/982
https://github.com/kiegroup/kie-wb-common/pull/1163
https://github.com/kiegroup/jbpm-form-modeler/pull/143
https://github.com/kiegroup/jbpm-wb/pull/874
> [7.3.x] JBPM-6047: Uploaded documents not visible on Documents tab on process Instance details 

- jbpm-document/pom.xml
- jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentImpl.java
- jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentStorageServiceImpl.java
- jbpm-document/src/main/java/org/jbpm/document/service/impl/util/DocumentDownloadLinkGenerator.java
- jbpm-document/src/test/java/org/jbpm/document/service/impl/DocumentImplTest.java
- jbpm-document/src/test/java/org/jbpm/document/service/impl/util/DocumentDownloadLinkGeneratorTest.java
@mswiderski @hasys could you take a look?
This is part of an ensemble, merge with:
https://github.com/kiegroup/jbpm/pull/981
https://github.com/kiegroup/kie-wb-common/pull/1160
https://github.com/kiegroup/jbpm-form-modeler/pull/142
https://github.com/kiegroup/jbpm-wb/pull/873
> [8.0.x] JBPM-6047: Uploaded documents not visible on Documents tab on process Instance details

- jbpm-installer/src/main/resources/db/upgrade-scripts/oracle/bpms-6.4-to-7.0.sql
- jbpm-installer/src/main/resources/db/upgrade-scripts/oracle/jbpm-6.5-to-7.0.sql
master PR: https://github.com/kiegroup/jbpm/pull/1014
6.5.x PR: https://github.com/kiegroup/jbpm/pull/1012
> RHBPMS-4992 Fix incorrect update statement in upgrade script for Oracle DB

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/main/java/org/jbpm/test/container/listeners/CountDownProcessEventListener.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/EJBService.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/ejbcompl/EThreadInfoTest.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/tx/ETransactionTest.java
Same as #1037, but for master.
> Stabilize jbpm-container tests

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
Hi, @psiroky,
see kiegroup/droolsjbpm-build-bootstrap#595 for more information.
> Revapi checks against 7.0.0.Final now

- jbpm-audit/src/test/java/org/jbpm/process/audit/jms/AsyncAuditLogProducerTest.java
AsyncAuditLogProducerTest test fixed: nodes and process instances logging
> Jbpm tests stabilisation

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/CaseCommentCommand.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/event/CaseEventSupport.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseEventEmittingTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/RecordingCaseEventListener.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/RecordingCaseEventListenerFactory.java
Fixes wrong case comment events emitting and adds a reproducer.
> Fix case comment event emitting

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/QuartzSchedulerService.java
This is a small good-to-have debug log for timer related trouble-shooting. Please merge, thanks!
> adding debug log which is useful for trouble-shooting

- jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentStorageServiceImpl.java
- jbpm-document/src/test/java/org/jbpm/document/service/DocumentStorageServiceImplTest.java
Test to reproduce the issue and proposed fix
> JBPM-6597: Prevent NPE when document storage dir doesn't exist

- jbpm-bpmn2/pom.xml
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-BusinessRuleTaskInfiniteLoop.drl
- jbpm-bpmn2/src/test/resources/BPMN2-BusinessRuleTaskLoop.bpmn2
- jbpm-bpmn2/src/test/resources/BPMN2-BusinessRuleTaskWithDataInputLoop.bpmn2
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
@etirelli could you please have a look?
> JBPM-6618 - Enable rule execution limit in business rule task

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml
@mswiderski @psiroky here is the change we spoke about. Maybe it would help.
> Fix large jbpm-container archives

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-TimerStart.bpmn2
StandaloneBPMNProcessTest:
* repeat limit for timer in process definition BPMN2-TimerStart.bpmn2 set to 5
* junit methods replaced by assertj
> JBPM-6487 JBPM tests stabilisation

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/event/CommentNotificationEventListener.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseCommentNotificationTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/event/CommentNotificationEventListenerTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/CommentNotificationEventListenerFactory.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/TestNotificationPublisher.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/DefaultUserInfo.java
- jbpm-workitems/jbpm-workitems-email/pom.xml
- jbpm-workitems/jbpm-workitems-email/src/main/java/org/jbpm/process/workitem/email/EmailNotificationPublisher.java
- jbpm-workitems/jbpm-workitems-email/src/main/java/org/jbpm/process/workitem/email/EmailWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-email/src/main/java/org/jbpm/process/workitem/email/SendHtml.java
- jbpm-workitems/jbpm-workitems-email/src/main/java/org/jbpm/process/workitem/email/TemplateManager.java
- jbpm-workitems/jbpm-workitems-email/src/main/resources/META-INF/services/org.kie.internal.utils.NotificationPublisher
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/EmailNotificationPublisherTest.java
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/EmailWorkItemHandlerTest.java
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/SendHtmlRealTest.java
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/SendHtmlTest.java
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/TemplateManagerTest.java
- jbpm-workitems/jbpm-workitems-email/src/test/resources/templates/basic-email.html
- jbpm-workitems/jbpm-workitems-email/src/test/resources/userinfo.properties
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/280
> JBPM-6640 - Allow pluggable notifications for case comments

- jbpm-installer/src/main/resources/db/ddl-scripts/mysql5/mysql-jbpm-amend-auto-increment-procedure.sql
Feel free to let me know if you want to concat this ddl to mysql5-jbpm-schema.sql rather than a separated file.
Also should I write a doc PR?
> RHBPMS-5067 - Amend AUTO_INCREMENT on MySQL/MariaDB restart

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
- jbpm-document/pom.xml
- jbpm-document/src/main/java/org/jbpm/document/Document.java
- jbpm-document/src/main/java/org/jbpm/document/marshalling/DocumentMarshallingStrategy.java
- jbpm-document/src/main/java/org/jbpm/document/service/DocumentStorageService.java
- jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentImpl.java
- jbpm-document/src/main/java/org/jbpm/document/service/impl/DocumentStorageServiceImpl.java
- jbpm-document/src/test/java/org/jbpm/document/marshalling/DocumentsMarshallingStrategyTest.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/ProcessServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/UserTaskServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/test/objects/Image.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/BPMN2-UserTaskImageVar.bpmn2
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/283
> JBPM-6681 - Support for lazy loaded variables

- jbpm-flow-builder/src/main/java/org/jbpm/process/workitem/WorkItemRepository.java
- jbpm-flow-builder/src/test/java/org/jbpm/process/workitem/WorkItemRepositoryTest.java
- jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repository/TestServiceOne/TestServiceOne.wid
- jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repository/TestServiceThree/TestServiceThree.wid
- jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repository/TestServiceTwo/TestServiceTwo.wid
- jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repository/TestServiceWithParamValuesThree/TestServiceWithParamValuesThree.wid
- jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repository/TestServiceWithParamValuesTwo/TestServiceWithParamValuesTwo.wid
- jbpm-flow-builder/src/test/resources/org/jbpm/process/workitem/repositorysingledir/repowid.wid
allows single directory workitem repository (as created by workitem archetype) to be used out of the box. Also used for workitem repository integration tests
> JBPM-6699 - Single directory workitem repository

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithPotOwnerDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithModifVarsQueryMapper.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskInstanceWithPotOwnerTest.java
> JBPM-6732 - Return the input&output data of tasks when using Advanced

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorImpl.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/InitExecutorTest.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/QueryServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/BusinessAdminTasksPreprocessor.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/PotOwnerTasksPreprocessor.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/UserTasksPreprocessor.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/QueryServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/NoFormNameHumanTask.bpmn
- jbpm-test-coverage/pom.xml
- jbpm-test-coverage/src/main/java/org/jbpm/test/wih/FirstErrorWorkItemHandler.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/async/AsyncIntermediateCatchSignalTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/ParallelAsyncJobsTest.java
dependes on https://github.com/dashbuilder/dashbuilder/pull/415
> [6.5.x] RHBPMS-5086 - initial delay is not set for the first executor thread, RHBPMS-5086 - initial delay is not set for the first executor thread

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
…ly Aether)
@mareknovotny 
Depends on kiegroup/droolsjbpm-build-bootstrap/pull/680
Marian
> Upgrade shrinkwrap in jbpm-container

- jbpm-human-task/jbpm-human-task-workitems/src/main/java/org/jbpm/services/task/wih/AbstractHTWorkItemHandler.java
- jbpm-human-task/jbpm-human-task-workitems/src/main/java/org/jbpm/services/task/wih/LocalHTWorkItemHandler.java
- jbpm-human-task/jbpm-human-task-workitems/src/main/java/org/jbpm/services/task/wih/NonManagedLocalHTWorkItemHandler.java
- jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/HTWorkItemHandlerBaseTest.java
- jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/HTWorkItemHandlerTest.java
Enable/disable autoclaim functionality
> JBPM-6779: Disable autoclaim functionality of swimlanes

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/DBUserInfoImpl.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/DefaultUserInfo.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/LDAPUserInfoImpl.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/PropertyUserInfoImpl.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/DBUserInfoImplTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/LDAPUserInfoImplTest.java
- jbpm-workitems/jbpm-workitems-email/src/main/java/org/jbpm/process/workitem/email/EmailWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-email/src/main/java/org/jbpm/process/workitem/email/TemplateManager.java
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/EmailNotificationPublisherTest.java
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/291
> JBPM-6807 - Extend UserInfo to allow look up of user id by email

- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/JPATaskLifeCycleEventListener.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java
Added message to the TASKEVENT with people assigment in case of forward event
> JBPM-6770: Information not available in TaskLifeCycleEventListener

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithPotOwnerDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithModifVarsQueryMapper.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithPotOwnerQueryMapper.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskInstanceWithPotOwnerTest.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/UserTaskInstanceWithPotOwnerDesc.java
Added processInstanceDescription as a businessId
> JBPM-6890: Adding the customTaskID as a unique identifier for an active

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AdHocSubProcessHandler.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/StageActivationConditionTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/stage/activation/NoStartNodeAdhocCaseWithActivationCondition.bpmn2
- jbpm-flow-builder/src/main/java/org/jbpm/compiler/ProcessBuilderImpl.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/DynamicNode.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicNodeInstance.java
@krisv @tsurdilo here is (at least from my list) last item for case mgmt that was actually brought up on last summit after our presentation so might be worth to include it as it's low risk overall.
> JBPM-6934 - Activation condition for case stage

- jbpm-services/jbpm-executor-cdi/src/main/java/org/jbpm/executor/cdi/impl/jpa/JPAExecutorServiceProducer.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/ExecutorServiceFactory.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorServiceImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/event/ExecutorEventSupport.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/event/ExecutorEventSupportImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/jpa/JPAExecutorStoreService.java
- jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/src/main/java/org/jbpm/executor/ejb/impl/ExecutorEventSupportEJBImpl.java
- jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/src/main/java/org/jbpm/executor/ejb/impl/ExecutorServiceEJBImpl.java
- jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/src/main/java/org/jbpm/executor/ejb/impl/jms/JmsAvailableJobsExecutorEJBImpl.java
here is the PR about making Executor EJBs work on WAS/WLS. I have tested it on EAP/WAS/WLS locally, so it should be OK now. Should I create an upstream JIRA for this issue too?
>  JBPM-7040 - ExecutorEventSupportEJBImpl EJB does not resolve on WLS and WAS

- jbpm-human-task/jbpm-human-task-core/pom.xml
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/jaxb/AbstractTaskSerializationTest.java
- jbpm-runtime-manager/pom.xml
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/deploy/DeploymentDescriptorManagerTest.java
- Sorry for reformatting the whole DeploymentDescriptorManagerTest, but it wasn't formatted properly. 
To see the changes without whitespaces, see here https://github.com/kiegroup/jbpm/pull/1159/files?w=1
@MarianMacik this is the PR for ComparePair removal we talked about.
> JBPM-7049 Replace ComparePair with AssertJ assertions

- jbpm-bpmn2/src/test/resources/BPMN2-EventSubprocessSignal-Nested.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/log/TaskLogClean-inputAssociation.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/task/HumanTask-inputTransformation.bpmn2
> [6.5.x] Update XSD Schema locations in BPMN2 definitions

- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManager.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/OperationCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/resources/operations-dsl.mvel
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/LifeCycleBaseTest.java
Cherry pick https://github.com/kiegroup/jbpm/pull/1167 into master
> RHBA-71 - Allow forward operation for Business Administrators

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EndEventHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/EndEventTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StartEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-EndEventSignalWithData.bpmn2
- jbpm-bpmn2/src/test/resources/BPMN2-StartEventWithMultipleOutgoingFlows.bpmn2
- jbpm-bpmn2/src/test/resources/BPMN2-SubProcessWrongStartEvent.bpmn2
- jbpm-bpmn2/src/test/resources/MultipleSubprocessWithSignalStartEvent.bpmn2
- jbpm-bpmn2/src/test/resources/SubprocessWithTimer.bpmn2
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/StartNode.java
@hasys here are some of the (imo) most valid fixes for BPMN2 jiras
> Bpmn2 fixes -  JBPM-7055,  JBPM-7066,  JBPM-7062

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SequenceFlowHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/XmlBPMNProcessDumper.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-ScriptTaskFEEL.bpmn2
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/ProcessDialectRegistry.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/feel/FeelProcessDialect.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/feel/FeelReturnValueEvaluatorBuilder.java
- jbpm-flow/pom.xml
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelReturnValueEvaluator.java
@etirelli @tarilabs could you please have a look?
> JBPM-7158 - Support FEEL as expression language for sequence flows

- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/JPATaskLifeCycleEventListener.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/impl/model/AuditTaskImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/events/TaskEventSupport.java
@mswiderski This is the PR to 7.7.x related to https://github.com/kiegroup/jbpm/pull/1184
> RHPAM-806: Enrich Task event listeners data

- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogProducer.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogReceiver.java
- jbpm-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/EDeploymentTest.java
- jbpm-examples/.classpath
- jbpm-examples/.project
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/persistence/TaskTransactionInterceptor.java
- jbpm-runtime-manager/pom.xml
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/DefaultRegisterableItemsFactory.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/DefaultRegisterableItemsFactoryTest.java
- jbpm-runtime-manager/src/test/resources/jbpm.audit.jms.properties
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
- jbpm-test-coverage/src/main/java/org/jbpm/test/entity/Application.java
- jbpm-test-coverage/src/main/java/org/jbpm/test/entity/Person.java
- jbpm-test-coverage/src/test/filtered-resources/META-INF/persistence.xml
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jpa/ParentChildMarshallingJpaTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/jpa/parent-child.bpmn
depends on https://github.com/kiegroup/drools/pull/1868
> [6.5.x] Backports for patch 6.4.10

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessHumanTaskTest.java
Hi @mswiderski,
I have decided to add a test which tests also TaskInstanceView.
The test added is just slightly altered [testProcess](https://github.com/MarianMacik/jbpm/blob/bab1b01a8eb7a3d4f9d306edb3c0f5ec6d6b2590/jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessHumanTaskTest.java#L55) test so in theory I can just extend the existing one with TestEventEmitter check, but then it would test more than one thing... plus I would have to either enable session persistence for whole class or just override it in the existing process like I did in this PR.
So wdyt?
> JBPM-6235 TaskInstanceView Test for NoSQL

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessHumanTaskTest.java
> [7.7.x] JBPM-6235 TaskInstanceView Test

- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseRuntimeDataService.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
Covered remaining methods:
* getCaseInstanceDataItemsByType
* getCaseInstanceDataItemsByName
> JBPM-4646 - Covered remaining methods

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/CompositeCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/GetUserTaskCommand.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/commands/GetUserTaskCommandTest.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/form/FormProviderServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/form/FormProviderServiceImplTest.java
- jbpm-services/jbpm-services-cdi/src/main/java/org/jbpm/services/cdi/impl/form/FormProvidesServiceCDIImpl.java
Copy of https://github.com/kiegroup/jbpm/pull/1201
@mswiderski Could you please review?
This is part of an ensemble merge with:
https://github.com/kiegroup/jbpm/pull/1202
https://github.com/kiegroup/droolsjbpm-integration/pull/1445
https://github.com/kiegroup/jbpm-wb/pull/1075
> [7.7.x] RHPAM-275: A user can display tasks for which he is not Potential Owner or Bussines Admin

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
> [7.7.x]  JBPM-6208 - Case file for related documents: backend - jBPM engine test development

- jbpm-bpmn2/src/test/resources/BPMN2-EventSubprocessSignal-Nested.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/log/TaskLogClean-inputAssociation.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/task/HumanTask-inputTransformation.bpmn2
Cherrypick of https://github.com/kiegroup/jbpm/pull/1172
@mbiarnes This should fix the test failures.
> [7.5.x] Update XSD Schema locations in BPMN2 definitions

- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/JPATaskLifeCycleEventListener.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java
Updated the task field update log message
> JBPM-7213: Tasks First Due Date update writes null to task log

- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/assignment/impl/TotalCompletionTimeLoadCalculator.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/assignment/AbstractTotalCompletionTimeTest.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/assignment/TotalCompletionTimeAssignmentStrategyTest.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/assignment/TotalCompletionTimeLoadCalculatorTest.java
@mswiderski As we discussed, here is the bug fix with a test. I have also created common abstract class since I wanted to reuse some of the existing code.
> Fix TotalCompletionTimeLoadCalculator

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
> [7.7.x] JBPM-7277 - Node SLA is not updated for the right node

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-BoundaryEventWithNonEffectiveSignal.bpmn2
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java
for boundary events, the cancel method should avoid firing and after node
left event causing an unwanted log.
> [JBPM-7296] Signal on boundary event causes an unwanted event listener message

- jbpm-container-test/jbpm-in-container-test/README.md
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/EJBService.java
\+ minor README update.
Should I open another one for 7.7.x? We can merge it when we are able to.
> Use PPI strategy for jbpm-container EJB tests

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/HumanTaskConfigurator.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/DefaultRuntimeEnvironment.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEnvironmentBuilder.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/SimpleRuntimeEnvironment.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/factory/LocalTaskServiceFactory.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/CustomUserInfoImpl.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/RuntimeTimeTaskConfiguratorTest.java
Modified runtime environment to pass the information from the builder to the human task.
> [JBPM-4947] Add userInfo() for RuntimeEnvironmentBuilder to be able to set a custom UserInfo

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-bpmn2/src/test/resources/dmn/BPMN2-BusinessRuleTaskDMNModelById.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/main/java/org/jbpm/casemgmt/cmmn/core/Decision.java
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/main/java/org/jbpm/casemgmt/cmmn/xml/CMMNSemanticModule.java
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/main/java/org/jbpm/casemgmt/cmmn/xml/DecisionElementHandler.java
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/main/java/org/jbpm/casemgmt/cmmn/xml/DefinitionsHandler.java
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/main/java/org/jbpm/casemgmt/cmmn/xml/FileItemHandler.java
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/main/java/org/jbpm/casemgmt/cmmn/xml/ProcessElementHandler.java
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/test/java/org/jbpm/casemgmt/cmmn/CaseTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/test/resources/CMMN-DecisionTaskReferenceCase.cmmn
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/src/test/resources/CMMN-ProcessTaskReferenceCase.cmmn
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CMMNCaseTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/cmmn/CMMN-DecisionTaskWithDMNApprovalCase.cmmn
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/cmmn/CMMN-DecisionTaskWithDMNCase.cmmn
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/dmn/0020-vacation-days.dmn
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
depends on https://github.com/kiegroup/drools/pull/1946
> JBPM-7368 - CMMN ProcesTask and DecisionTask reference support

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/CompensationTest.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/base/TransactionalPersistenceEventManager.java
- jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/processinstance/objects/TestTransactionalPersistenceEventManager.java
- jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/session/PersistentStatefulSessionTest.java
- jbpm-persistence/jbpm-persistence-jpa/src/test/resources/META-INF/services/org.jbpm.persistence.api.integration.PersistenceEventManager
> [7.7.x] Stabilize EventEmitter tests

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/migration/MigrationManager.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/MigrationManagerTest.java
- jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-MultiInstance-v1.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-MultiInstance-v2.bpmn2
https://issues.jboss.org/browse/RHBPMS-5164
> [6.5.x] RHBPMS-5164: IllegalArgumentException: Unknown node id" when migrating MultiInstance

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/QueryServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/DeploymentIdsPreprocessor.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/query/preprocessor/DeploymentIdsPreprocessorTest.java
Introduce an impossible condition when all containers are stopped to avoid show all elements
> JBPM-7401: Show all process instances when all containers are stopped

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseWithJPADataTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/objects/Patient.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/META-INF/persistence.xml
depends on https://github.com/kiegroup/drools/pull/1993
> JBPM-7493 - JPA Entity causes NPE when being used as case file variable

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseWithJPADataTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/objects/Patient.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/AbstractCaseServicesBaseTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/META-INF/persistence.xml
depends on https://github.com/kiegroup/drools/pull/1994
> [7.7.x] RHPAM-1424 - JPA Entity causes NPE when being used as case file variable

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/UserTaskServiceImpl.java
@mswiderski - Created better responses for user without permissions or tasks with status which doesn't match with the operation performed. The following task operations have been changed:
- Claim.
- Completed.
- Forward.
- Delegate.
- Release.
- Nomitate.
> JBPM-7542: Create better response for user without permissions to do REST Forward task operation

- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ProcessInstanceImpl.java
- jbpm-flow/src/test/java/org/jbpm/event/process/ProcessEventSupportTest.java
setting process instance parent to -1 by default
> [RHPAM-153] parentProcessInstanceId in ProcessEventListener is 0

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/AbstractEJBServicesTest.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/EJBService.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/tx/ETransactionTest.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/org/jbpm/test/container/archive/ejbservices/assets/HumanTaskThrowException.bpmn2
- jbpm-examples/.classpath
- jbpm-examples/.project
> [RHPAM-2] NullPointerException during transaction rollback when using CMT

- jbpm-workitems/jbpm-workitems-bpmn2/src/main/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskHandler.java
@mswiderski would you mind to have a look?
> Remove unused parameter and fix typos

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/SLATrackingCommand.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/SLATrackingCommandTest.java
Adding filter to not signal processes that are completed or aborted
> [JBPM-7731] SLA tracking command signals ended process or nodes

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/BusinessCalendarImpl.java
- jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/AbstractUserGroupInfo.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/persistence/JPATaskPersistenceContext.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/persistence/JPATaskPersistenceContextManager.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContextManager.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/PessimisticLockTasksServiceTest.java
depends on 
https://github.com/kiegroup/drools/pull/2091
https://github.com/kiegroup/droolsjbpm-knowledge/pull/329
@tkobayas here is the enhancement for pessimistic locking (see the linked PRs as well)
@martinweiler here is fix to the file handle leak
> JBPM-7820, JBPM-7815, JBPM-7822

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/handler/ErrornousWorkItemHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/handler/WorkItemHandlerExceptionHandlingTest.java
- jbpm-bpmn2/src/test/resources/handler/BPMN2-ReceiveTask.bpmn2
- jbpm-bpmn2/src/test/resources/handler/BPMN2-ScriptTask.bpmn2
- jbpm-bpmn2/src/test/resources/handler/BPMN2-UserTaskWithBooleanOutput.bpmn2
- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java
- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/JBPMMessages.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm-flow/src/main/resources/org/jbpm/marshalling/jbpmmessages.proto
- jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/AbstractLogOrThrowWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-email/src/main/java/org/jbpm/process/workitem/email/EmailWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/EmailWorkItemHandlerTest.java
- jbpm-workitems/jbpm-workitems-rest/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java
- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-webservice/src/test/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandlerTest.java
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/332
@MarianMacik @tsurdilo could you please have a look at this?
some details can be found [here](http://mswiderski.blogspot.com/2018/10/handle-service-exceptions-via-subprocess.html)
> JBPM-7679 - Manage WIH exception through a subproces

- jbpm-container-test/jbpm-in-container-test/README.md
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/archive/LocalTransactions.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/org/jbpm/test/container/archive/localtransactions/tomcat-context.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/org/jbpm/test/container/archive/localtransactions/web.xml
- jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml
- jbpm-container-test/pom.xml
Shows an integration of DBCP pooling data source into jBPM in container tests on Tomcat.
> BAQE-440: Use DBCP for jBPM in container tests on Tomcat

- jbpm-test-coverage/pom.xml
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ScriptTaskWithDependencyTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/ScriptTaskJavaWithDep.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/ScriptTaskMvelWithDep.bpmn
- jbpm-test/src/main/java/org/jbpm/test/services/AbstractServicesTest.java
- Unit test
testScriptTaskJava: Success
testScriptTaskMvel: Failure
> [JBPM-7879] Mvel Script doesn't resolve dependency

- jbpm-installer/src/main/resources/db/ddl-scripts/mysql5/mysql5-jbpm-schema.sql
- jbpm-installer/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-jbpm-schema.sql
moving the idx name in fk to the fk declaration and removing the create index statement.
> [JBPM-7875] Redundant index in mysql5-jbpm-schema.sql

- jbpm-container-test/jbpm-in-container-test/README.md
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/arquillian/wildfly14x/arquillian.xml
- jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/README.md
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-app/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/test/java/org/jbpm/remote/ejb/test/task/ETaskQueryFilterTest.java
- jbpm-container-test/pom.xml
- jbpm-installer/src/main/filtered-resources/lib/readme.txt
- jbpm-installer/src/main/resources/build.properties
Upgrate to Wildfly 14
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* https://github.com/kiegroup/kie-wb-distributions/pull/821 
* https://github.com/kiegroup/kie-docs/pull/1108
* https://github.com/kiegroup/optaplanner/pull/437
* https://github.com/kiegroup/optaplanner-wb/pull/304
> [AF-1555]: Upgrade WF11 to WF14

- jbpm-container-test/jbpm-in-container-test/README.md
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/README.md
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
Should be merged with:
https://github.com/kiegroup/kie-jenkins-scripts/pull/365
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/875
https://github.com/kiegroup/jbpm/pull/1366
https://github.com/kiegroup/droolsjbpm-integration/pull/1627
https://github.com/kiegroup/kie-wb-distributions/pull/841
> Rename profiles after wildfly14 migration

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/DataObjectHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/PropertyHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-WorkingMessageModel.bpmn2
transform id to variable name during message tag process xml processing using
id metadata
> [JBPM-7824] dataInputAssociation sourceRef unable to resolve property /variable

- jbpm-document/src/test/java/org/jbpm/document/marshalling/DocumentsMarshallingStrategyTest.java
@mswiderski as we discussed...
> Fix DocumentStorageServiceImplTest

- jbpm-workitems/jbpm-workitems-rest/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/PATCH.java
- jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java
- jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/TestRESTResource.java
We have updated the RESTWorkItemHandler to support the PATCH HTTP verb
> JBPM-8085 - RESTWorkItemHandler PATCH operation support

- jbpm-services/jbpm-shared-services/src/main/java/org/jbpm/shared/services/impl/TransactionalCommandService.java
Description in kiegroup/droolsjbpm-integration#1688
> JBPM-8120 - Case Data is inserted twice in springboot

- jbpm-audit/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-integration-deps/jbpm-ejb-services/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-integration-deps/jbpm-persistence/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-integration-deps/jbpm/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-integration-deps/rest/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-app/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-domain/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
- jbpm-document/pom.xml
- jbpm-flow/pom.xml
- jbpm-human-task/jbpm-human-task-audit/pom.xml
- jbpm-human-task/jbpm-human-task-core/pom.xml
- jbpm-human-task/jbpm-human-task-jpa/pom.xml
- jbpm-query-jpa/pom.xml
- jbpm-services/jbpm-executor/pom.xml
- jbpm-services/jbpm-kie-services/src/test/resources/kjar-with-deps/data-pom.xml
- jbpm-services/jbpm-services-cdi/pom.xml
- jbpm-test/pom.xml
- jbpm-workitems/jbpm-workitems-bpmn2/pom.xml
- jbpm-workitems/jbpm-workitems-rest/pom.xml
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/900 (Please comment on this PR if you have any questions)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/352
* https://github.com/kiegroup/drools/pull/2191
* https://github.com/kiegroup/jbpm/pull/1394
* https://github.com/kiegroup/optaplanner/pull/469
* https://github.com/kiegroup/droolsjbpm-integration/pull/1667
* https://github.com/kiegroup/appformer/pull/574
* https://github.com/kiegroup/optaplanner-wb/pull/319
* https://github.com/kiegroup/jbpm-wb/pull/1257
* https://github.com/kiegroup/kie-wb-distributions/pull/858
* https://github.com/kiegroup/optaweb-employee-rostering/pull/215
> Align JAXB and JAXWS APIs with Wildfly

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/KModuleDeploymentService.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/KModuleDeploymentServiceTest.java
Assembly:
https://github.com/kiegroup/drools/pull/2257
https://github.com/kiegroup/droolsjbpm-knowledge/pull/370
https://github.com/kiegroup/jbpm/pull/1440
> JBPM-8166: case modeler - register the assets into the workbench and process engine

- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/EmailWorkItemHandlerTest.java
- jbpm-workitems/jbpm-workitems-email/src/test/java/org/jbpm/process/workitem/email/SendHtmlTest.java
Complete some of the current tests for EmailWorkItemHandlerTest and SendHtmlTest to cover also DisplayName checking as requested at RHPAM-1854
> Check also DisplayName at EmailWorkItemHandler (RHPAM-1854)

- jbpm-test/src/main/java/org/jbpm/test/JbpmJUnitBaseTestCase.java
> [JBPM-8152] Add method to jBPM JUnit support to retrieve active nodes

- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/timer/GlobalJpaTimerJobInstance.java
@mswiderski @jstastny-cz could you please take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/jbpm/pull/1466
https://github.com/kiegroup/droolsjbpm-integration/pull/1783
> JBPM-8363: EJB Timer error in development mode for existing process during deploy

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/942
> BAQE-928 - Change revapi to check against 7.18.0.Final

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
We have some ways to confirm runtime strategy with customers but this simple log is really reliable and useful!
> RuntimeManager creation log

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/error/ExecutionErrorHandlerImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/error/ExecutionErrorManagerImpl.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/error/CountExecutionErrorListener.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/error/ExecutionErrorHandlingRuntimeManagerTest.java
- jbpm-runtime-manager/src/test/resources/META-INF/services/org.kie.internal.runtime.error.ExecutionErrorListener
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/QueryServiceImpl.java
Assembly:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1799
- https://github.com/kiegroup/jbpm/pull/1473
- https://github.com/kiegroup/kie-soup/pull/84
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/379
> JBPM-8347 - Add execution error listeners

- jbpm-test/src/main/java/org/jbpm/test/JbpmJUnitTestCase.java
> DROOLS-3988 Fix change-set XSD URL

- jbpm-workitems/pom.xml
- jbpm-workitems/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
- jbpm-workitems/src/test/java/org/jbpm/process/workitem/bpmn2/JaxWSServiceTaskTest.java
- jbpm-workitems/src/test/resources/BPMN2-TwoWebServiceImportsWithTimeout.bpmn
> [RHBPMS-5254] Cannot configure CXF Client connectionTimeout/receiveTimeout for WebServiceWorkItemHandler 

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SubProcessHandler.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNode.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/AsyncEventNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/CompositeNodeInstance.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/AsyncContinuationSupportTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/async/AsyncMultisubprocessTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/AsyncSubMultiprocess.bpmn2
- jbpm-test-coverage/src/test/resources/usergroups.properties
unwrapping async node instances when foreach loop is created.
> [JBPM-8364] AsyncMode True causes error with Multi Instance Sub Process

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/handler/RetryMultipleWorkItemHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/handler/WorkItemHandlerExceptionHandlingTest.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/AbstractLogOrThrowWorkItemHandler.java
change a bit the work item handler
executed work item handler -> error handling -> subprocess fork -> strategy -> retry loop
> [JBPM-8430] RETRY handlingStrategy should handle exception multiple times while handling exception via subprocess

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/KModuleDeploymentService.java
port http://git.app.eng.bos.redhat.com/git/kiegroup/jbpm.git/commit/?h=RHBPMS-5237&id=869f89a0c8666e89d817c4880d300c992de463aa
> [6.5.x] [RHBPMS-5247] Control which classes are registered for serialization at kjar level

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/QueryServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/QueryServiceImplTest.java
Assembly:
- https://github.com/kiegroup/jbpm/pull/1496
- https://github.com/kiegroup/kie-soup/pull/91
> JBPM-8559 - Disable SQLDataSet size estimation

- jbpm-flow/pom.xml
- pom.xml
Introducing new profiles used for code coverage measurement as a preparatory work for SonarCloud analysis, which will be available both daily and for each PR.
> [JBPM-8103] Configure SonarCloud PR analysis for jBPM

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
depends on kiegroup/droolsjbpm-build-bootstrap#1002
> BAQE-1039 - Change revapi to check against 7.23.0.Final

- jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/store/DeploymentStore.java
using proper calls for XstreamUtils
> [RHPAM-2219] XStream Security Framework is not initiated

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/pom.xml
To be merged after kiegroup/droolsjbpm-build-bootstrap#1018
> Take a globally managed version of Tomcat from kie-parent

- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/timer/GlobalJpaTimerJobInstance.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbTimerJobRetry.java
providing recovery of timers. executed till it is succeed
> [JBPM-8688] Timers do not recover after database disconnection

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/prediction/NoOpPredictionService.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/prediction/PredictionServiceRegistry.java
- jbpm-human-task/jbpm-human-task-core/src/main/resources/META-INF/services/org.kie.internal.task.api.prediction.PredictionService
- jbpm-human-task/jbpm-human-task-workitems/src/main/java/org/jbpm/services/task/wih/ExternalTaskEventListener.java
- jbpm-human-task/jbpm-human-task-workitems/src/main/java/org/jbpm/services/task/wih/LocalHTWorkItemHandler.java
Add prediction service integration
> [BAPL-1123] Implement prediction service handlers and listeners

- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/timer/GlobalJpaTimerJobInstance.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbTimerJobRetry.java
providing recovery of timers. executed till it is succeed
> [JBPM-8688] Timers do not recover after database disconnection (#1520)

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/JBossUserGroupCallbackImpl.java
Bug report on https://issues.jboss.org/browse/JBPM-8770
> JBPM-8770 fix for UnsupportedOperationException modifying an inmutable list.

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-IntermediateCatchEventConditionIdWithHyphen.bpmn2
- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
removing the last 2 hyphens so you get the right conditional event.
> [JBPM-8694] ConditionalEvent isn't triggered when process id contains hyphen

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ClassCacheManager.java
> [JBPM-8699] Fix exception handling in ClassCacheManager

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
depends on kiegroup/droolsjbpm-build-bootstrap#1070
> BAQE-1114 - Change revapi to check against 7.26.0.Final

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-IntermediateCatchEventConditionIdWithHyphen.bpmn2
- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
* [JBPM-8694] ConditionalEvent isn't triggered when process id contains hyphen
- Unit test
* [JBPM-8694] [JBPM-8694] ConditionalEvent isn't triggered when process id contains hyphen
> [7.26.x] [JBPM-8694] ConditionalEvent isn't triggered when process id contains hyphen (#1525)

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/DateTimeUtils.java
- jbpm-flow/src/test/java/org/jbpm/process/core/timer/DateTimeUtilsTest.java
Added the support for parsing timer intermediate events with duration over a day
> JBPM-8893 - Add full ISO8601 support for DateTimeUtils

- jbpm-audit/src/main/java/org/jbpm/process/audit/event/DefaultAuditEventBuilderImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseRuntimeDataService.java
- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/model/instance/CaseInstance.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/StartCaseCommand.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/model/instance/CaseInstanceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/resources/META-INF/CaseMgmtorm.xml
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/SubCaseServiceImplTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseWithSubCaseQuery.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/SubSubCase.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/UserTaskCase.bpmn2
- jbpm-flow/src/main/java/org/jbpm/process/instance/AbstractProcessInstanceFactory.java
Adding a query a collection of sub cases from parentCaseId
> [JBPM-8781] API to view all of sub-cases belong to a parent case

- jbpm-audit/src/main/java/org/jbpm/process/audit/event/DefaultAuditEventBuilderImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/CaseRuntimeDataService.java
- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/model/instance/CaseInstance.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/command/StartCaseCommand.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/model/instance/CaseInstanceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/resources/META-INF/CaseMgmtorm.xml
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/SubCaseServiceImplTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseWithSubCaseQuery.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/SubSubCase.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/UserTaskCase.bpmn2
- jbpm-flow/src/main/java/org/jbpm/process/instance/AbstractProcessInstanceFactory.java
Adding a query a collection of sub cases from parentCaseId
cherry pick #1535
> [7.30.x] [JBPM-8781] API to view all of sub-cases belong to a parent case (#1535)

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalQuartzDBTimerServiceTest.java
> [7.30.x] [JBPM-8866] GlobalTimerService.timerJobsPerSession leak with StartProcess

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/ProcessInstanceLogCleanTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/TaskLogCleanTest.java
Need to stabilize w2k16 pipelines (faster CPU) where tests using process startDate to delete logs are not considering that more than one process may have the same startDate.
> Stabilize log clean tests considering repeated startDates

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/util/CountDownListenerFactory.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseWithBoundaryTimerStage.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/CaseWithStageAndBoundaryTimer.bpmn2
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/ProcessNodeBuilderRegistry.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- jbpm-test-util/src/main/java/org/jbpm/test/listener/process/DefaultCountDownProcessEventListener.java
Dynamic nodes can have timers associated
> [JBPM-8895] case management - stage boundary timer does not trigger

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/MilestoneNodeInstance.java
Modify the activation type for milestone so it is unique among cases
> [RHPAM-2526] Lots of queries against ContextMappingInfo when satisfying Milestone

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/commands/TriggerNodeCommand.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/async/AsyncAdHocSubprocessTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/subprocess/AdHocSubProcessTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/async/AsyncAdHocSubprocess.bpmn2
adding support for async ad-hoc subprocess
> [JBPM-8698] Cannot trigger activities inside asynchronous ad-hoc subprocess

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/error/JobAutoAckErrorCommand.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/error/ProcessAutoAckErrorCommand.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/error/TaskAutoAckErrorCommand.java
…Command" execution fails on Postgres database
type conversion are not implicit in postgres db
@Lob field needs to be in a tx
> [JBPM-8988] The "org.jbpm.executor.commands.error.ProcessAutoAckError  Command" execution fails on Postgres database

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/ProcessInstanceLogCleanTest.java
Changes to solve some issues when running Jenkins jobs due to w2k16 servers which are assigning same start date for several processes.
> Fixed deleteLogsByDate method to avoid issue with dates

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
depends on kiegroup/droolsjbpm-build-bootstrap#1190
> BAQE-1267 - Change revapi to check against 7.33.0.Final

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/CoreFunctionQueryParamBuilder.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/preprocessor/UserAndGroupsTasksPreprocessor.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/query/CoreFunctionQueryParamBuilderTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/query/preprocessor/UserAndGroupsTasksPreprocessorTest.java
modify some function to allow AST expressions for filtering
> [JBPM-8910] How to use a "OR" query operator in a custom query in the query-parameters

- jbpm-human-task/jbpm-human-task-core/pom.xml
- jbpm-workitems/jbpm-workitems-webservice/pom.xml
adding only javax.activation dependency based on profile activated by jdk
> Fix issues with javax.activation duplication after jbpm#1598

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/util/HumanTaskHandlerHelper.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/TimerUpdateTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/ISOTimerTest.bpmn2
deadline parser allows empty string
> [RHDM-1278] NotificationListener is starting with no iso expression

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/subprocess/ReusableSubProcessTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/subprocess/ErrorHandlingMainProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/subprocess/ErrorHandlingSubprocess.bpmn
error boundary compensation event is not thrown.
> [RHPAM-2782] Error boundary event not working as expected with reusable subprocess node.

- jbpm-audit/src/main/java/org/jbpm/process/audit/event/DefaultAuditEventBuilderImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CMMNCaseTest.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/ProcessInstanceAdminServiceImplTest.java
modify query for milestones as a plain value object
> [RHPAM-2774] AchievedAtDate for milestone is not preserved when case is reopen

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/util/HumanTaskHandlerHelper.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/TimerUpdateTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/ISOTimerTest.bpmn2
deadline parser allows empty string
> [7.7.x] [RHDM-1278] NotificationListener is starting with no iso expression

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskQueryServiceImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskQueryFilterTest.java
https://issues.redhat.com/browse/JBPM-9085
just in case adding check for null value
> [JBPM-9085],[JBPM-9086] - fixed failing tests

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskQueryServiceImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskQueryFilterTest.java
backport of fixes for https://issues.redhat.com/browse/JBPM-9085 and https://issues.redhat.com/browse/JBPM-9086 #1621
> [7.33.x] backport of JBPM-9085 and JBPM-9086

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventSubProcessNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/event/SubProcessWithTimerStartEventTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/event/SubProcessWithTimerStartEvent.bpmn2
discrimate wheter the timer is triggered for subprocess or not
> [RHPAM-2839] Event Sub-process with timer start node fire if an intermediate timer from process is triggered

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/AddContentCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/TaskContext.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskInstanceServiceImpl.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/LifeCycleBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/LifeCycleLocalCommandBasedTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/RuntimeDataServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
- jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/RuntimeDataServiceCDIImplTest.java
- jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/UserTaskServiceCDIImplTest.java
- jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/util/CDITestHelperNoTaskService.java
added permission check to task add content
> [RHPAM-2810] Non potential owner of task able to update task variable through REST api

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/ConcurrentGlobalTimerServiceTest.java
test failure caused by concurrent problem
> [JBPM-9075] Test failure: org.jbpm.test.functional.timer.ConcurrentGlobalTimerServiceTest.testSessionPerProcessInstance

- pom.xml
https://issues.redhat.com/browse/BXMSPROD-702
Alternative idea to #1630
> BXMSPROD-702: jbpm-installer excluded and added to the productized profile

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/AddContentCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/command/CommandBasedTaskService.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/task/SynchronizedTaskService.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/UserTaskServiceImpl.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/UserTaskService.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/main/java/org/jbpm/services/ejb/impl/TaskServiceEJBImpl.java
kie api service in jbpm to store task event with another user.
> [RHPAM-2813] Allow to use 'user' query parameter with /contents/output REST API.

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/deadlines/notifications/impl/NotificationListenerManager.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/deadlines/notifications/impl/NotificationListenerManagerTest.java
add flags for include/excluding notification listeners
> [JBPM-9118] Support disabling of Notification Listener

- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/AdvanceCaseRuntimeDataService.java
- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/utils/CaseServiceConfigurator.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/AdvanceCaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/utils/DefaultCaseServiceConfigurator.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/AdvanceCaseRuntimeDataServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/ProcessInstanceWithVarsDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithPotOwnerDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/utils/DefaultKieServiceConfigurator.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/SingleHumanTaskWithVarsA.bpmn2
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/SingleHumanTaskWithVarsB.bpmn2
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/AdvanceRuntimeDataService.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/ProcessInstanceWithVarsDesc.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/UserTaskInstanceWithPotOwnerDesc.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/query/model/QueryParam.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/utils/KieServiceConfigurator.java
- jbpm-services/jbpm-shared-services/src/main/java/org/jbpm/shared/services/impl/JpaPersistenceContext.java
- jbpm-test/src/main/java/org/jbpm/test/services/AbstractCaseServicesTest.java
- jbpm-test/src/main/java/org/jbpm/test/services/AbstractKieServicesTest.java
added search for process with variables and task with variables
> [RHPAM-2552] Ability to Search for tasks by multiple task variables a nd / or process variables via the kie-server api.

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
removing transient objects when the timer is created.
> [RHPAM-2805] memory growth when starting a high number of process instances with a high timers

- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/generator/CaseIdGenerator.java
- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/generator/CasePrefixCannotBeGeneratedException.java
- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/model/CaseDefinition.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/generator/CaseIdExpressionFunctions.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/generator/TableCaseIdGenerator.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/model/CaseDefinitionImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseIdGeneratorTest.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/EmptyCaseWithCaseIdPrefix1.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/EmptyCaseWithCaseIdPrefix2.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/EmptyCaseWithCaseIdPrefix3.bpmn2
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/cases/EmptyCaseWithCaseIdPrefix4.bpmn2
adding expression support for case Id and prefix
> [JBPM-9094] Add the ability to specify an CaseId Expression and Sequence Name / Case Prefix Expression

- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogProducer.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogReceiver.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/jms/AsyncCaseInstanceAuditEventProducer.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/jms/AsyncCaseInstanceAuditEventReceiver.java
- jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/jms/AsyncTaskLifeCycleEventProducer.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/jms/AsyncTaskLifeCycleEventReceiver.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/store/DeploymentStore.java
Part of https://github.com/kiegroup/kie-soup/pull/137
> KOGITO-1546 XStreamUtils kie-soup refactoring

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
- jbpm-bpmn2/src/test/resources/BPMN2-CallActivityWithBoundaryEvent.bpmn2
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/ExtendedNodeBuilder.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/SignalNodeInstanceAction.java
replace inverted commas in duration time expression for avoiding
java compilation problems.
> [RHPAM-2845] Expression in timer is not interpreted correctly

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/TaskQueryBuilderTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/hr/hiring_parallel.bpmn2
Include _formName_ into the UserTaskInstanceDesc object returned by getTaskById, getTaskByWorkItemId and getProcessInstanceById.
> [JBPM-9147] getTaskById does not return formName

- pom.xml
https://issues.redhat.com/browse/BXMSPROD-702
> BXMSPROD-702 jbm-distribution removed from community-only profile

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceQueryMapper.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/TaskQueryBuilderTest.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/UserTaskInstanceDesc.java
Adding subject to existing constructor.
Changing query
> [JBPM-9126] Missing "subject" attribute in the UserTaskInstanceDesc

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/oracle-new-jbpm-drop-schema.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/oracle-new-jbpm-schema.sql
- jbpm-db-scripts/src/test/filtered-resources/META-INF/persistence.xml
- jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/GenerateDDLScriptsTests.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/TestsUtil.java
changed oracle scripts to reflect properly the increment by = allocation size in entities.
> [RHPAM-2591] Task identifers are recorded on the DB with negative numbers

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/sybase/task_assigning_tables_sybase.sql
- remove wrong  semicolon from sybase script
> PLANNER-1985:  [Tasks Assignment] Add task assignment tables to the DB scripts

- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/quartzdialects/PostgreSQLCustomDialect.java
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1350
> Bump postgresql version to kie-parent version

- .gitignore
- jbpm-audit/pom.xml
- jbpm-bpmn2/pom.xml
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/pom.xml
- jbpm-case-mgmt/jbpm-case-mgmt-impl/pom.xml
- jbpm-human-task/jbpm-human-task-audit/pom.xml
- jbpm-human-task/jbpm-human-task-core/pom.xml
- jbpm-human-task/jbpm-human-task-jpa/pom.xml
- jbpm-persistence/jbpm-persistence-jpa/pom.xml
- jbpm-query-jpa/pom.xml
- jbpm-runtime-manager/pom.xml
- jbpm-services/jbpm-executor/pom.xml
- jbpm-services/jbpm-kie-services/pom.xml
- jbpm-services/jbpm-services-cdi/pom.xml
- jbpm-test-coverage/pom.xml
- jbpm-test-util/pom.xml
- jbpm-workitems/jbpm-workitems-bpmn2/pom.xml
- jbpm-workitems/jbpm-workitems-rest/pom.xml
- jbpm-xes/pom.xml
Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1347
excluding Weld changes from https://github.com/kiegroup/jbpm/pull/1654
> BXMSPROD-685: upgrade of hibernate libs

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/RuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/BPMN2DataServicesTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/DeploymentServiceWithSyncTest.java
Check if deployment id is available in the in memory list and throw
proper exception if not.
> JBPM-9151 API return 200 if containerId does not exist

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/db2/task_assigning_tables_db2.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/derby/task_assigning_tables_derby.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/h2/task_assigning_tables_h2.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/hsqldb/task_assigning_tables_hsqldb.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/task_assigning_tables_drop_mysql.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysql5/task_assigning_tables_mysql.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/task_assigning_tables_drop_mysql_innodb.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/task_assigning_tables_mysql_innodb.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/oracle/task_assigning_tables_oracle.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/task_assigning_tables_drop_postgres.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/postgresql/task_assigning_tables_postgresql.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver/task_assigning_tables_drop_sqlserver.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver/task_assigning_tables_sqlserver.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver2008/task_assigning_tables_drop_sqlserver2008.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/sqlserver2008/task_assigning_tables_sqlserver2008.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/sybase/task_assigning_tables_drop_sybase.sql
- jbpm-db-scripts/src/main/resources/db/ddl-scripts/sybase/task_assigning_tables_sybase.sql
…
(cherry picked from commit 8fd85b8a0425b8e735cbe51b57bf83e84c6b363f)
> PLANNER-2047: Using Task Assigning with DDL prevents users from completing tasks

- jbpm-audit/src/test/java/org/jbpm/process/audit/AbstractAuditLogServiceTest.java
- jbpm-audit/src/test/java/org/jbpm/process/audit/StandaloneAuditLogServiceTest.java
- jbpm-audit/src/test/resources/ruleflow4.rf
Backporting [jbpm#1694](https://github.com/kiegroup/jbpm/pull/1694) to 7.39.x
> [7.39.x] [RHPAM-2796] Test for aborted type task when aborting process

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
- jbpm-flow/src/main/java/org/jbpm/process/core/timer/JobNameHelper.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/commands/ListTimersCommand.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/ProcessInstanceAdminServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/boundarytimer.bpmn2
Add boundary event name to timer name
> [JBPM-9185] use BoundaryEvent name to compose timer name

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/UserGroupCallbackTaskCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/deadlines/notifications/impl/email/EmailNotificationListener.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/util/HumanTaskHandlerHelper.java
- jbpm-human-task/jbpm-human-task-core/src/test/filtered-resources/META-INF/persistence.xml
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/EmailDeadlinesBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/resources/org/jbpm/services/task/service/DeadlineWithNotification.mvel
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/EmailImpl.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/persistence/JPATaskModelFactory.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/persistence/JPATaskPersistenceContext.java
- jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/HumanTaskHandlerHelperTest.java
allow arbitrary emails notifications through parameter toemails
> [JBPM-9197] Allow the introduction of emails in Tasks notifications

- jbpm-installer/src/main/resources/build.properties
- jbpm-workitems/jbpm-workitems-archetype/README.md
> upgraded version to 7.42.0-SNAPSHOT

- jbpm-runtime-manager/pom.xml
[JBPM-9302 ](https://github.com/fjtirado/jbpm/pull/new/JBPM-9302)
> [JBPM-9302] Adding missing import to manifest

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ProcessFactoryTest.java
- jbpm-bpmn2/src/test/java/org/kie/api/fluent/ProcessBuilderTest.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowNodeContainerFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactoryBuilder.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/AbstractCompositeNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ActionNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/BoundaryEventNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/CompositeNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/DialectConverter.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/DynamicNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/EndNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/EventNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/FaultNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ForEachNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/HumanTaskNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/JoinFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/MilestoneNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/NodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/RuleSetNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/SplitFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/StartNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/SubProcessNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/TimerNodeFactory.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/TypeConverter.java
- jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/WorkItemNodeFactory.java
- jbpm-flow/src/test/java/org/jbpm/process/ProcessFactoryTest.java
- jbpm-test/src/test/resources/kmodule/humantask.bpmn
Implementing fluent API in already existing classes
**JIRA**: 
[JBPM-9287](https://issues.redhat.com/browse/JBPM-9287)
https://github.com/kiegroup/droolsjbpm-knowledge/pull/457
> [JBPM-9287] Adding official support for fluent API

- jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
Jira: 
https://issues.redhat.com/browse/JBPM-9304
> [JBPM-9304] NullPointerException in case SLA on user task is violated

- jbpm-audit/src/main/java/org/jbpm/process/audit/AbstractAuditLogger.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/AbstractAuditLoggerAdapter.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/NodeInstanceLog.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/ProcessInstanceLog.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/JPATaskLifeCycleEventListener.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/impl/model/AuditTaskImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/impl/model/BAMTaskSummaryImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/impl/model/TaskEventImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/impl/model/TaskVariableImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/lifecycle/listeners/BAMTaskEventListener.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/events/TaskEventImpl.java
refactor task listeners and process listener to adapters
for data replication
> [JBPM-9277]  JMS Audit Data Replication in spring boot

- jbpm-bpmn2/src/test/resources/dmn/0020-vacation-days.dmn
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/resources/dmn/0020-vacation-days.dmn
- jbpm-workitems/jbpm-workitems-bpmn2/src/test/resources/0020-vacation-days.dmn
**JIRA**: https://issues.redhat.com/browse/DROOLS-5602
**referenced Pull Requests**: none
<pre>
How to retest a PR or trigger a specific build:
</pre>
> DROOLS-5602 Review jbpm DMN examples version in codebase

- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/PersistenceEventManager.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/base/TransactionalPersistenceEventManager.java
JIRA: 
https://issues.redhat.com/browse/JBPM-9308
> [JBPM-9308] EventEmitter is not working in spring boot

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/ExecuteDeadlinesCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/ExecuteReminderCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/deadlines/notifications/impl/NotificationListenerManager.java
Jira: https://issues.redhat.com/browse/JBPM-9317
> [JBPM-9317] userTaskService.saveContent doesn't work

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/deadlines/notifications/impl/email/EmailNotificationListener.java
**JIRA**:  [JBPM-9320](https://issues.redhat.com/browse/JBPM-9320)
> [JBPM-9320] NPE at EmailNotificationListener toString

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerRequestRuntimeManager.java
**JIRA**: 
[JBPM-9342](https://issues.redhat.com/browse/JBPM-9342)
> [JBPM-9342] disposeRuntimeEngine shouldn't throw exception if already closed

- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
Generating custom class loader with list of jars in case ModuleClassLoader is found in hierachy
**JIRA**:  [RHPAM-3106](https://issues.redhat.com/browse/RHPAM-3106)
> [RPHAM-3106] Getting error then try to generate classes from WSDL file or URL

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/HumanTaskVariablesAccessTest.java
**JIRA**: [JBPM-9418](https://issues.redhat.com/browse/JBPM-9418)
<details>
<summary>
</summary>
</details>
> JBPM-9418 - Enhance test coverage for human task variables in listeners

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
**JIRA**: [BAQE-1567](https://issues.redhat.com/browse/BAQE-1567)
depends on kiegroup/droolsjbpm-build-bootstrap#1485
> BAQE-1567 - Change revapi to check against 7.44.0.Final

- jbpm-human-task/jbpm-human-task-audit/pom.xml
- jbpm-services/jbpm-executor-cdi/pom.xml
- jbpm-services/jbpm-services-cdi/pom.xml
- jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/pom.xml
https://issues.redhat.com/browse/BXMSPROD-685
Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1320
> BXSMPROD-685: upgrade of weld to 3.x

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SplitHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/persistence/DynamicProcessTest.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ProcessInstanceImpl.java
RHPAM-3188: Exception after dynamically adding new node to process
instance + Fix default in exclusive gateway dumper
Co-authored-by: Enrique Gonzalez Martinez <egonzale@localhost.localdomain>
> [7.x] RHPAM-3188: Exception after dynamically adding new node to process

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
Jira:
https://issues.redhat.com/browse/JBPM-9447
> [JBPM-9447] No session found for context in case SLA on user task is violated

- jbpm-event-emitters/jbpm-event-emitters-kafka/.gitignore
Adding ignore to git
**JIRA**: 
[JBPM-9413](https://issues.redhat.com/browse/JBPM-9413)
> [JBPM-9413] AMQ Streams (Kafka) integration Notifier / producer

- jbpm-workitems/jbpm-workitems-archetype/src/main/resources/archetype-resources/src/test/java/__classPrefix__WorkitemIntegrationTest.java
**JIRA**: [JBPM-9417](https://issues.redhat.com/browse/JBPM-9417)
> [JBPM-9417] testWorkitemValidity fails on Windows

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/ProcessServiceImpl.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/ProcessService.java
Jira: https://issues.redhat.com/browse/JBPM-9405
Added process service to signal by correlation key.
> [JBPM-9405] Provide API method to signal process instance with correlation key

- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/TaskQueryServiceBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/jaxb/JaxbTaskSerializationTest.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/resources/META-INF/Taskorm.xml
Jira: https://issues.redhat.com/browse/JBPM-9426
> [JBPM-9426] No tasks returned when userId == null, exlOwner !=null and groups !=null

- jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/java/org/jbpm/event/emitters/kafka/KafkaEventEmitter.java
- jbpm-event-emitters/jbpm-event-emitters-kafka/src/test/java/org/jbpm/event/emitters/kafka/KafkaEventEmitterTest.java
**JIRA**
[JBPM-9457](https://issues.redhat.com/browse/JBPM-9457)
Using one producer to publish all kafka events. 
Since the events are published at the end of transaction there is no chance for the appearance of "ghost events"
The main caveat againts the previous implementation is that there exist a minimal chance (if Kafka broker goes down or out of reach during publishing of events) that not all events associate to the transaction are published if Kafka is avaialble (normally there is only one event associated to the transaction, so 99% of the cases this error scenario is equivalent to the transacted one, where the options were none vs all published).
> [JBPM-4957] Kafka Event Emitter should reuse the same Producer

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/ProcessServiceImpl.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/ProcessService.java
Jira https://issues.redhat.com/browse/RHPAM-3269
> (GSS-exception) [ 7.44.x] [JBPM-9405] Provide API method to signal process instance with correlationKey

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/AddTaskCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskInstanceServiceImpl.java
JIRA: [link](https://issues.redhat.com/browse/JBPM-9427)
cherry picked from https://github.com/kiegroup/jbpm/commit/d5ca77a00c29d853f36a89c8b50469f06a31cf7e
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/481
> (QE) [7.44.x] [JBPM-9427] IllegalArgumentException when task is skipped in afterTaskAddedEvent

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
Jira: https://issues.redhat.com/browse/JBPM-9403
> [JBPM-9403] Process work-flow breaks for processes with timers if one of Nodes is starting or shutting down at the time of workflow execution

- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/TaskQueryServiceBaseTest.java
**JIRA**: [JBPM-9462](https://issues.redhat.com/browse/JBPM-9462)
This fixes tests when running on MySQL/MariaDB databases.
<details>
<summary>
</summary>
</details>
> JBPM-9462 - Stabilize TaskQueryServiceBaseTest added by JBPM-9426

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EscalationHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/elements/DataAssociationFactory.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xpath/XPATHAssignmentAction.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xpath/XPATHAssignmentBuilder.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/AssignmentBuilder.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/EventNodeBuilder.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/WorkItemNodeBuilder.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/AssignmentProducer.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/BoundaryEventNode.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/ExtendedNodeInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/MapResolverFactory.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/event/BoundaryEventWithOutputSetPersistenceTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/BoundaryCompensationProcessWithOutputSet.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/BoundaryConditionalProcessWithOutputSet.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/BoundaryErrorProcessWithOutputSet.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/BoundaryEscalationProcessWithOutputSet.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/BoundaryMessageProcessWithOutputSet.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/BoundarySignalProcessWithOutputSet.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/BoundaryTimerProcessWithOutputSet.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-9411
Add dataOuputs to boundary events.
> [JBPM-9411] Provide a way to access task details in boundary event

- jbpm-event-emitters/jbpm-event-emitters-kafka/pom.xml
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/bpmn2/BPMN2DataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/bpmn2/ProcessDescriptor.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/MessageDescImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/ProcessAssetDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/SignalDescBaseImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/SignalDescImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/xml/ServicesProcessDataEventListener.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/model/MessageDescImplTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/model/ProcessAssetDescTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/model/SignalDescImplTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/BPMN2DataServicesReferencesTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/BPMN2-MessageStart.bpmn2
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/MessageDesc.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/ProcessDefinition.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/SignalDesc.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/SignalDescBase.java
Adding method getSignalsMetadata to ProcessDefinition interface
Merge with [#droolsjbpm-integration:2288](https://github.com/kiegroup/droolsjbpm-integration/pull/2288)
**JIRA**: 
[JBPM-9436](https://issues.redhat.com/browse/JBPM-9436)
> [JBPM-9436] AMQ Streams (Kafka) listener functionality / consumer

- jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/java/org/jbpm/event/emitters/kafka/KafkaEventEmitter.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/base/TransactionalPersistenceEventManager.java
**JIRA**: [JBPM-9466](https://issues.redhat.com/browse/JBPM-9466)
> [JBPM-9466] Make configurable Kafka Producer max.block.ms

- jbpm-test/src/main/java/org/jbpm/test/services/AbstractKieServicesTest.java
- jbpm-test/src/main/java/org/jbpm/test/services/AbstractServicesTest.java
**[BAQE-1562](https://issues.redhat.com/browse/BAQE-1562)**: Follow-up regarding jbpm performance test for search variables API scenario
> [BAQE-1562] Follow-up regarding jbpm performance test for search variables API scenario

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-GatewayFEEL-wrong.bpmn2
- jbpm-bpmn2/src/test/resources/BPMN2-GatewayFEEL.bpmn2
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelErrorEvaluatorListener.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelReturnValueEvaluator.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelReturnValueEvaluatorException.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelReturnValueEvaluatorListener.java
**JIRA**: https://issues.redhat.com/browse/JBPM-9484
**referenced Pull Requests**: none
<details>
<summary>
</summary>
</details>
> JBPM-9484 Improve BPMN -> FEEL integration

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/Message.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/Signal.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/SendMessageAction.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/SendSignalAction.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/VariableResolver.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ActionNodeHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EndEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EndNodeHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateCatchEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ReceiveTaskHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SendTaskHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/StartEventHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-EndEventSignalWithData.bpmn2
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/ActionNodeBuilder.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/JavaAction.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/JavaDroolsAction.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/ProcessServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/MessageDescImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/SignalDescBaseImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/SignalDescImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/BPMN2DataServicesReferencesTest.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/ProcessService.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/SignalDescBase.java
Firing event when signal is thrown or message is sent
**JIRA**: 
[JBPM-9474](https://issues.redhat.com/browse/JBPM-9474)
**depends on**:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/486
https://github.com/kiegroup/drools/pull/3264
**merge with**
https://github.com/kiegroup/droolsjbpm-integration/pull/2322
> [JBPM-9474] AMQ Streams (Kafka) integration - Produce events to Kafka by Signal or Messages Events 

- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
Jira: https://issues.redhat.com/browse/JBPM-9399
process service start in clustered environment.
> [JBPM-9399] Add support to jBPM and runtime/cluster environments detection

- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/DeadlinesImpl.java
**JIRA**: _(https://issues.redhat.com/browse/JBPM-9506)_
> [JBPM-9506] Not able to add task reassignment through TaskEventListener

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
This certifies that runtime engines are clean up during signal sent
> DISPOSE_CLEANUP

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BusinessRuleTaskHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/TaskHandler.java
- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/elements/DataAssociationFactory.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/DataTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-DataInputAssociationStunner.bpmn2
- jbpm-bpmn2/src/test/resources/BPMN2-DataInputAssociationsWithoutSource.bpmn2
- jbpm-bpmn2/src/test/resources/BPMN2-DataOutputAssociationStunner.bpmn2
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/MVELAssignmentAction.java
Changes in parser and evaluator to align with non standard behavior
**JIRA**: 
[JBPM-9507](https://issues.redhat.com/browse/JBPM-9507)
> [JBPM-9507] Align DataAssociation behavior with kogito

- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/db2/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/db2/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/derby/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/derby/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/h2/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/h2/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/hsqldb/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/hsqldb/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/rhpam-7.9-to-7.10.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sybase/jbpm-7.41-to-7.48.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sybase/rhpam-7.9-to-7.10.sql
**[JBPM-9509](https://issues.redhat.com/browse/JBPM-9509)**
> JBPM-9509 - Upgrade scripts regarding duplicated processes with same correlationKey

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/BusinessCalendarImpl.java
- jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java
Jira: https://issues.redhat.com/browse/JBPM-9546
> [JBPM-9546] BusinessCalendar Calculations when timer created prior to Business Hours are wrong

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/AsyncEventNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/gateway/ParallelGatewayAsyncTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/gateway/ParallelGatewayAsync.bpmn
Jira: https://issues.redhat.com/browse/JBPM-9555
> [JBPM-9555] Process with multiple parallel gateways is not completed in Async mode

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/BusinessCalendarImpl.java
- jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java
- jbpm-flow/src/test/resources/business-custom-calendar.properties
Add the possibility to specify business calendar outside the class path
> [JBPM-9554] jbpm.business.calendar.properties property not working inOCP environment

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseServiceImplTest.java
**JIRA**: [JBPM-9594](https://issues.redhat.com/browse/JBPM-9594)
* Improved synchronization so now it is guaranteed that at least 2 out of 6 iterations are run after the process instance is aborted. Before it was possible that the spawned thread finished before the abort happened, thus not testing the desired scenario. I also considered to interleave the threads deterministically with 2 latches, but the code was less clear and not the worth it.
* Swapped the order of asserts and logs to first print log message and only then potentially fail on assert.
> JBPM-9594 - Improve synchronization of testPerCaseCleanup

- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
Changed reflection approach so it is based on public methods
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9589)
> [JBPM-9589] Problem invoking WebServiceWorkItemHandler with EAP 7.3.5

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/AbstractRuntimeManagerLockStrategy.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/DebugRuntimeManagerLock.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/DefaultRuntimeManagerLock.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/FreeRuntimeManagerLockStrategy.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/LegacyRuntimeManagerLockStrategy.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/RuntimeManagerLockWatcherSingletonService.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/SelfReleaseRuntimeManagerLock.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/lock/SelfReleaseRuntimeManagerLockFactory.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/spi/RuntimeManagerLockStrategy.java
- jbpm-runtime-manager/src/main/resources/META-INF/services/org.jbpm.runtime.manager.spi.RuntimeManagerLockFactory
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/lock/CustomRuntimeManagerLockStrategyTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/lock/RuntimeManagerLockStrategyTest.java
Jira: https://issues.redhat.com/browse/JBPM-9551
> [JBPM-9551] Allow automatic system recovery when locks gets locked for an amount idle time

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/assignment/AssignmentService.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/assignment/impl/AssignmentServiceImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessHumanTaskTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/HumanTaskWithCustomAssignmentStrategy.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-9547
> [JBPM-9547] Create a higher-level way to define task assignment strategy

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAAuditLogService.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/query/AbstractAuditDeleteBuilderImpl.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/query/NodeInstanceLogDeleteBuilderImpl.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/query/ProcessInstanceLogDeleteBuilderImpl.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/query/VarInstanceLogDeleteBuilderImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/audit/CaseFileDataLogDeleteBuilderImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/audit/CaseLogCleanupCommand.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/audit/CaseRoleAssignmentLogDeleteBuilderImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/service/AuditTaskDeleteBuilderImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/service/TaskEventDeleteBuilderImpl.java
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/service/TaskVariableDeleteBuilderImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/LogCleanupCommand.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/jpa/ErrorInfoDeleteBuilderImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/jpa/RequestInfoDeleteBuilderImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/LogCleanupCommandTest.java
Splitting delete transaction in several ones by using where in
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9579)
https://github.com/kiegroup/droolsjbpm-knowledge/pull/499
https://github.com/kiegroup/droolsjbpm-integration/pull/2390
> [JBPM-9579] Adding a pagination parameter to LogCleanupCommand

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ContextMappingInfo.java
Jira: https://issues.redhat.com/browse/JBPM-9615
> [JBPM-9615] Data type conversion exception in MSSQL and Sybase databases

- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
Previous solution was not valid because URLS generated by
VFSResouceLoader has vfs protocol, which is not understood by cxf.
Hence I sligthly modified original approach. First list of
ResourceLoaders is obtained (package method). Then, depending on ResourceLoader type (we
are really only interested on Jar or VFS) we access different internal
private fields (since ResourceLoader unfortunately does not have getRootURL method).
In the case of VFS, we need extra logic to generate the right path to
jar file (went to parent and the append the jar name, as in original
fix)
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9614)
> [JBPM-9614] Problem invoking WebServiceWorkItemHandler on Java 11

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ContextMappingInfo.java
cherry pick https://github.com/kiegroup/jbpm/commit/9910229dd6f5778a220e24f8069b21d0a9bbabfe
https://issues.redhat.com/browse/JBPM-9615
> (QE) [7.48.x] [JBPM-9615] Data type conversion exception in MSSQL and Sybase databases

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
Jira: https://issues.redhat.com/browse/JBPM-9633
> [JBPM-9633] Task instance marked as Completed despite OptimisticLockException

- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/subprocess/MultipleTasksLoopSubprocessTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/subprocess/MultipleTasksLoopParentProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/subprocess/MultipleTasksLoopSubProcess.bpmn
**[JBPM-9638](https://issues.redhat.com/browse/JBPM-9638)**: Test case for JBPM-9623 (Dynamic Sub process is getting invoked twice instead of once when implemented in loop back) - backport.
> (GSS)[7.48.x][JBPM-9638] - Test case for JBPM-9623 (Dynamic Sub process is getting invoked twice instead of once when implemented in loop back)

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
cherry pick from master
https://github.com/kiegroup/jbpm/commit/6a74128533d683dcd7200b6e3067d22d2d93eb3f
> (GSS) [7.48.x] [JBPM-9633] Task instance marked as Completed despite OptimisticLockException

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventSubProcessNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/subprocess/MainProcessExceptionHandlerTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/subprocess/MainProcessExceptionHandler.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/subprocess/MainSubprocessExceptionHandler.bpmn2
Jira : https://issues.redhat.com/browse/JBPM-9631
> [JBPM-9631] Exception generated on subprocess is not correctly propagated to parent process

- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
**JIRA**:  [JBPM-9642](https://issues.redhat.com/browse/JBPM-9642)
> [JBPM-9642] Add test for task listeners not removed after engine disposal

- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/subprocess/MultipleTasksLoopSubprocessTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/subprocess/MultipleTasksLoopParentProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/regression/subprocess/MultipleTasksLoopSubProcess.bpmn
**[JBPM-9638](https://issues.redhat.com/browse/JBPM-9638)**: Test case for JBPM-9623 (Dynamic Sub process is getting invoked twice instead of once when implemented in loop back).
> [JBPM-9638] - Test case for JBPM-9623 (Dynamic Sub process is getting invoked twice instead of once when implemented in loop back)

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/UserTaskAdminServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/commands/AddPeopleAssignmentsCommand.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/commands/RemovePeopleAssignmentsCommand.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/UserTaskAdminServiceImplTest.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/admin/UserTaskAdminService.java
Jira: https://issues.redhat.com/browse/JBPM-9625
> [JBPM-9625] Allow to bypass the authenticated user in the KIE REST API that is adding users or groups as potential owners

- jbpm-container-test/jbpm-in-container-test/shrinkwrap-war-profiles/pom.xml
**JIRA**: [JBPM-9672](https://issues.redhat.com/browse/JBPM-9672)
<details>
<summary>
</summary>
</details>
> Make TransactionsTest on Tomcat compatible with Java 11

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/ExecuteDeadlinesCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/util/DeadlineSchedulerHelper.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/EmailDeadlinesBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/MvelFilePath.java
- jbpm-human-task/jbpm-human-task-core/src/test/resources/org/jbpm/services/task/service/DeadlineWith2Notifications.mvel
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/DeadlineImpl.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/DeadlinesImpl.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/EmailNotificationHeaderImpl.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/EmailNotificationImpl.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/EscalationImpl.java
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9647)
> [JBPM-9647]  Multiple humantask email notifications are send

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/concurrent/LoadAndScheduleRequestsTask.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/concurrent/PrioritisedScheduledThreadPoolExecutor.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/jms/JmsAvaiableJobExecutorTest.java
Jira : https://issues.redhat.com/browse/JBPM-9657
> [JBPM-9657] Job execution retryDelay not honored after LoadAndScheduleRequestsTask

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/ExceptionWorkItemHandler.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/WorkItemExceptionHandlingStrategyTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/BPMN2-UserTaskWithBooleanOutputWaitSignal.bpmn2
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/BPMN2-WaitSignal.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-9677
> [JBPM-9677] Invalid session was used for this context when aborting process instance with active exception handling sub process

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithPotOwnerDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithModifVarsQueryMapper.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithPotOwnerQueryMapper.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java
**JIRA**: 
[https://issues.redhat.com/browse/JBPM-9684](https://issues.redhat.com/browse/JBPM-9684)
Add task description to `GetTasksByIdList` query and `UserTaskInstanceWithPotOwnerDesc` POJO
> [JBPM-9684] Add task description

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/ProcessAssetDesc.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/model/ProcessDefinition.java
**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)
<details>
<summary>
</summary>
</details>
> AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
Jira: https://issues.redhat.com/browse/JBPM-9690
> [JBPM-9690] Task deadline timers are not removed in multi-node setup and fire repeatedly

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithPotOwnerDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithModifVarsQueryMapper.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithPotOwnerQueryMapper.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java
**JIRA**: 
[https://issues.redhat.com/browse/RHPAM-3584](https://issues.redhat.com/browse/RHPAM-3584)
* https://github.com/kiegroup/jbpm/pull/1903 (cherry-pick)
<details>
<summary>
</summary>
</details>
> (GSS) [7.11.1] [RHPAM-3584] Add task description

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-BoundarySignalWithVariableNameEventOnTaskbpmn.bpmn
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9700)
> [JBPM-9700] Signal name not resolved when adding listener

- jbpm-workitems/jbpm-workitems-rest/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java
- jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java
- jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/RestWorkitemHandlerClientCreationTest.java
- jbpm-workitems/jbpm-workitems-rest/src/test/java/org/jbpm/process/workitem/rest/TestRESTResource.java
**JIRA**: _(https://issues.redhat.com/browse/JBPM-9673)_
> [JBPM-9673] Allow to send cookies in REST workItemHandler

- jbpm-test-coverage/pom.xml
- jbpm-test-coverage/src/test/filtered-resources/quartz-db-short-misfire.properties
- jbpm-test-coverage/src/test/filtered-resources/quartz-db.properties
**[BAQE-1811](https://issues.redhat.com/browse/BAQE-1811)** Add support for Quart delegate class dynamically
depends on https://github.com/jboss-integration/bxms-qe-tests/pull/3770
> [BAQE-1811] Add support for Quartz delegate class dynamically

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java
- jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/RegisteredTimerServiceDelegate.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPAProcessInstanceManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeManagerFactoryImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/tx/NoTransactionalTimerResourcesCleanupAwareSchedulerServiceInterceptor.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/tx/TransactionAwareSchedulerServiceInterceptor.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
during rollback transaction the timer were incorrecly removed
Jira https://issues.redhat.com/browse/JBPM-9717
> [JBPM-9717] Timer instance incorrectly removed upon process execution error

- jbpm-test-coverage/src/test/filtered-resources/META-INF/persistence.xml
- jbpm-test-coverage/src/test/filtered-resources/quartz-db-short-misfire.properties
- jbpm-test-coverage/src/test/filtered-resources/quartz-db.properties
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalQuartzDBTimerServiceTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalTimerServiceBaseTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/GlobalTimerServiceVolumeTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/MultipleTimerServicesTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/timer/TimerBaseTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/DatabaseType.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/ScriptsBase.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/TestPersistenceContextBase.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/TestsUtil.java
**[BAQE-1810](https://issues.redhat.com/browse/BAQE-1810)** Update jbpm-test-coverage module to start using DDL scripts for Quartz
> [BAQE-1810] Update jbpm-test-coverage module to start using DDL scripts for Quartz

- jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessFlowControlTest.java
Remove useless tests that are ignored since 2010.
> [DROOLS-6331] remove useless test methods

- jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/src/main/assembly/assembly-ejb-war.xml
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/main/assembly/assembly-ejb-war.xml
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/assembly/assembly-ejb-war.xml
**[BAQE-1833](https://issues.redhat.com/browse/BAQE-1833)**: Some projects are failing as persistence.xml was moved to a different location
> [BAQE-1833] Some projects are failing as persistence.xml was moved to a different location

- jbpm-audit/pom.xml
- jbpm-audit/src/main/java/org/jbpm/process/audit/support/AuditJbpmEntityContributor.java
- jbpm-audit/src/main/resources/META-INF/services/org.jbpm.persistence.api.JbpmEntityContributor
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/audit/CaseAuditJbpmEntityContributor.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/resources/META-INF/services/org.jbpm.persistence.api.JbpmEntityContributor
- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/support/TaskAuditJbpmEntityContributor.java
- jbpm-human-task/jbpm-human-task-audit/src/main/resources/META-INF/services/org.jbpm.persistence.api.JbpmEntityContributor
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/JbpmEntityContributor.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/PersistenceEnvironmentName.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/support/JbpmMetadataContributor.java
Jira: https://issues.redhat.com/browse/JBPM-9748
> [JBPM-9748] Avoid count check in hibernate for audit table.

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/BasicExecutorBaseTest.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/NoCDISimpleExecutorTest.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/ReoccurringPrintOutCommand.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/test/CountDownAsyncJobStartedListener.java
Jira: https://issues.redhat.com/browse/JBPM-9752
> [JBPM-9752] Graceful shutdown leave hanging jobs with the state of a RUNNING causing the job to stale

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
**JIRA**: [BAQE-1904](https://issues.redhat.com/browse/BAQE-1904)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1665
> BAQE-1904 - Change revapi to check against 7.52.0.Final

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/resources/BPMN2-BoundarySignalWithVariableNameEventOnTaskbpmn.bpmn
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
Backport of https://github.com/kiegroup/jbpm/pull/1916
See https://issues.redhat.com/browse/RHPAM-3603?focusedCommentId=16230156&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16230156
> [7.52.x][JBPM-9700] Signal name not resolved when adding listener

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
use querycontext to add sorting information to native query
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9714)
https://github.com/kiegroup/droolsjbpm-integration/pull/2506
> [JBPM-9714] Include sort column to queries processes

- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/ParallelAsyncJobsTest.java
**[BXMSPROD-1366](https://issues.redhat.com/browse/BXMSPROD-1366)**: [Improve community CI] [jbpm] test errors
> [BXMSPROD-1366] - [Improve community CI] [jbpm] test errors

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/main/java/org/jbpm/test/container/mock/RestService.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/ejbcompl/EThreadInfoTest.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/task/ERestServiceTaskTest.java
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-suite/src/main/java/org/jbpm/remote/ejb/test/mock/RestService.java
**[BXMSPROD-1367](https://issues.redhat.com/browse/BXMSPROD-1367)**: [Improve community CI] [jbpm] timeout
> [BXMSPROD-1367] - [Improve community CI] [jbpm] timeout

- jbpm-flow/pom.xml
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/util/ComparablePeriodSerializer.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/util/TypeTransformer.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
- jbpm-flow/src/test/java/org/jbpm/workflow/instance/node/RuleSetInstanceTest.java
- jbpm-flow/src/test/java/org/jbpm/workflow/instance/node/TypeTransformerTest.java
- jbpm-test-coverage/src/main/java/org/jbpm/test/domain/Structure.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/BusinessRuleTaskTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNDate.dmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNDateProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNNestedStructure.dmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNNestedStructureProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNPeriod.dmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNPeriodProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNStructure.dmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNStructureFieldNameMismatch.dmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNStructureFieldNameMismatchProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNStructureProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNWithMoreTypesStructure.dmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/buildDMNWithMoreTypesStructureProcess.bpmn
- jbpm-workitems/jbpm-workitems-bpmn2/src/main/java/org/jbpm/process/workitem/bpmn2/AbstractRuleTaskHandler.java
- jbpm-workitems/jbpm-workitems-bpmn2/src/test/java/org/jbpm/process/workitem/bpmn2/BusinessRuleTaskTest.java
- jbpm-workitems/jbpm-workitems-bpmn2/src/test/java/org/jbpm/process/workitem/bpmn2/objects/Person.java
Jira: https://issues.redhat.com/browse/JBPM-9774
> [JBPM-9783] Incorrect object type returned in a DMN business-rule task of a BPMN (RuleSetNode Instance)

- jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/GlobalTimerService.java
- jbpm-flow/src/main/java/org/jbpm/process/core/timer/impl/RegisteredTimerServiceDelegate.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPAProcessInstanceManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeManagerFactoryImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/tx/NoTransactionalTimerResourcesCleanupAwareSchedulerServiceInterceptor.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/tx/TransactionAwareSchedulerServiceInterceptor.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
cherry picked from https://github.com/kiegroup/jbpm/commit/b7057f126f6fca35759b46ec65ca8563b3b689f8
https://issues.redhat.com/browse/JBPM-9717
> [7.52.x] [JBPM-9717] Timer instance incorrectly removed upon process execution error

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java
- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/objects/TestWorkItemHandler.java
- jbpm-bpmn2/src/test/resources/BPMN2-MultiInstanceLoopHumanTaskWithBoundaryTimer.bpmn2
- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProcessInstanceMarshaller.java
- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java
- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/JBPMMessages.java
- jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/ExtendedNodeImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java
- jbpm-flow/src/main/resources/org/jbpm/marshalling/jbpmmessages.proto
- jbpm-test-util/src/main/java/org/jbpm/test/listener/process/DefaultCountDownProcessEventListener.java
cherry picked from https://github.com/kiegroup/jbpm/commit/cf161c7d548a1dbc11a33889c7b0a18fa1b9fb1d
Jira : https://issues.redhat.com/browse/RHPAM-2103
> [7.52.x] [JBPM-9002] no catching timer for parallel task or subprocess

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/ExecuteSQLQueryCommand.java
- jbpm-services/jbpm-shared-services/src/main/java/org/jbpm/shared/services/impl/JpaPersistenceContext.java
- jbpm-services/jbpm-shared-services/src/main/java/org/jbpm/shared/services/impl/commands/NativeQueryStringCommand.java
cherry pick 20392913f25c0eba40c1b6e4257964b253788cff
> [GSS] [7.52.x] [JBPM-9706] Create Native SQL command to operate database to execute functions / SQL queries and stores in the execution results

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
cherry picked https://github.com/kiegroup/jbpm/commit/62f92c98f5d3f68f08fd519638259be97aa2d574
Jira: https://issues.redhat.com/browse/RHPAM-3574
> [7.52.x] [JBPM-9690] Task deadline timers are not removed in multi-node setup and fire repeatedly

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
https://issues.redhat.com/browse/JBPM-9794
> JBPM-9794: Locking issue with aborted parent process instance

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
Jira: https://issues.redhat.com/browse/JBPM-9794
backport
> [ENG] [7.52.x] [JBPM-9794] Locking issue with aborted parent process instance

- jbpm-case-mgmt/jbpm-case-mgmt-api/src/main/java/org/jbpm/casemgmt/api/AdvanceCaseRuntimeDataService.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/AdvanceCaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/AdvanceCaseRuntimeDataServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplWithVariableChangesTest.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/AdvanceRuntimeDataService.java
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/query/model/QueryParam.java
**JIRA**: JBPM-9675
[https://issues.redhat.com/browse/JBPM-9675](https://issues.redhat.com/browse/JBPM-9675)
> [JBPM-9675] Find pot-owners as OR

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java
Jira: https://issues.redhat.com/browse/JBPM-9797
> [JBPM-9797] Fix dispose engine for cancel dependent subprocess node

- jbpm-event-emitters/jbpm-event-emitters-kafka/src/main/java/org/jbpm/event/emitters/kafka/KafkaEventEmitter.java
- jbpm-event-emitters/jbpm-event-emitters-kafka/src/test/java/org/jbpm/event/emitters/kafka/KafkaEventEmitterTest.java
Adding functionality for Kafka event emitter
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9798)
> [JBPM-9798] Accept all possible properties for Kafka Consumer/Producer

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java
Jira: https://issues.redhat.com/browse/JBPM-9803
> [QE] [7.52.x] [JBPM-9797] Fix dispose engine for cancel dependent subprocess node

- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/SLATrackingCommandTest.java
**[JBPM-9819](https://issues.redhat.com/browse/JBPM-9819)**: SLATrackingCommandTest#testSLATrackingOnUserTaskSLAMet test is failing on master
> [JBPM-9819] - SLATrackingCommandTest#testSLATrackingOnUserTaskSLAMet test is failing on master

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorImpl.java
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9823)
> [JBPM-9823] add jms header to include job

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9826)
> [JBPM-9826] Getting potential owners for a case task

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EJBTimerScheduler.java
Jira. https://issues.redhat.com/browse/RHPAM-3826
> [RHPAM-3826] Task deadline timers leave stale entries in Database in multi-node setup and fired repeatedly (WIP)

- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/Assignment.java
Metadata should be transient for assigment
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9507)
> [JBPM-9507] Fixing serialization issue

- jbpm-audit/src/main/java/org/jbpm/process/audit/AuditLoggerArchiveTreat.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
- jbpm-audit/src/main/java/org/jbpm/process/audit/jms/AsyncAuditLogReceiver.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/log/ProcessInstanceLogArchiveTest.java
Jira: https://issues.redhat.com/browse/JBPM-9849
> [JBPM-9849] Remove default behavior for end_date

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/store/DeploymentSynchronizer.java
**JIRA**: [JBPM-9873](https://issues.redhat.com/browse/JBPM-9873)
> [JBPM-9873] DeploymentSynchronizer may lose updates due to uncommitted updateDate

- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9867)
> [JBPM-9867] Changing getTaskInstances queries

- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplAuditNoneTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
**JIRA**: [JBPM-9867](https://issues.redhat.com/browse/JBPM-9867)
* https://github.com/kiegroup/jbpm/pull/1999
> [JBPM-9867] Add test with NONE audit mode

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/DataTest.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/MVELAssignmentAction.java
- jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/MVELResolverFactory.java
- jbpm-flow/src/main/java/org/jbpm/process/core/impl/ObjectCloner.java
- jbpm-flow/src/test/java/org/jbpm/process/core/impl/ObjectClonerTest.java
Variable change event was not triggered when evaluating mvel expression
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9861)
> [JBPM-9861] Mvel expressions should fire variable change event

- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/LocalTaskAuditWithDeadlineTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/listener/task/CountDownTaskEventListener.java
**JIRA**: [JBPM-9895](https://issues.redhat.com/browse/JBPM-9895)
> [7.59.x][JBPM-9895] Fix flaky tests at LocalTaskAuditWithDeadlineTest

- jbpm-audit/pom.xml
- jbpm-bpmn2/pom.xml
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/pom.xml
- jbpm-case-mgmt/jbpm-case-mgmt-impl/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-db-scripts/pom.xml
- jbpm-distribution/pom.xml
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/pom.xml
- jbpm-examples/pom.xml
- jbpm-human-task/jbpm-human-task-core/pom.xml
- jbpm-human-task/jbpm-human-task-workitems/pom.xml
- jbpm-human-task/pom.xml
- jbpm-persistence/jbpm-persistence-jpa/pom.xml
- jbpm-runtime-manager/pom.xml
- jbpm-services/jbpm-executor-cdi/pom.xml
- jbpm-services/jbpm-executor/pom.xml
- jbpm-services/jbpm-kie-services/pom.xml
- jbpm-services/jbpm-services-cdi/pom.xml
- jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/pom.xml
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-client/pom.xml
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/pom.xml
- jbpm-test-util/pom.xml
- jbpm-test/pom.xml
- jbpm-workitems/jbpm-workitems-rest/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/droolsjbpm-integration/pull/2602
* https://github.com/kiegroup/jbpm-work-items/pull/215
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/optaplanner/pull/1574
* https://github.com/kiegroup/kie-soup/pull/227
* https://github.com/jboss-integration/rhba-installers/pull/92
> RHPAM-3897: switch to jboss-transaction-spi-jakarta

- jbpm-audit/pom.xml
- jbpm-bpmn2/pom.xml
- jbpm-case-mgmt/jbpm-case-mgmt-cmmn/pom.xml
- jbpm-case-mgmt/jbpm-case-mgmt-impl/pom.xml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-db-scripts/pom.xml
- jbpm-distribution/pom.xml
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/pom.xml
- jbpm-examples/pom.xml
- jbpm-human-task/jbpm-human-task-core/pom.xml
- jbpm-human-task/jbpm-human-task-workitems/pom.xml
- jbpm-human-task/pom.xml
- jbpm-persistence/jbpm-persistence-jpa/pom.xml
- jbpm-runtime-manager/pom.xml
- jbpm-services/jbpm-executor-cdi/pom.xml
- jbpm-services/jbpm-executor/pom.xml
- jbpm-services/jbpm-kie-services/pom.xml
- jbpm-services/jbpm-services-cdi/pom.xml
- jbpm-services/jbpm-services-ejb/jbpm-executor-ejb/pom.xml
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-client/pom.xml
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/pom.xml
- jbpm-test-util/pom.xml
- jbpm-test/pom.xml
- jbpm-workitems/jbpm-workitems-rest/pom.xml
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1775
* https://github.com/kiegroup/drools/pull/3839
* https://github.com/kiegroup/droolsjbpm-integration/pull/2609
* https://github.com/kiegroup/jbpm-work-items/pull/218
* https://github.com/kiegroup/kie-jpmml-integration/pull/67
* https://github.com/kiegroup/optaplanner/pull/1580
* https://github.com/kiegroup/kie-soup/pull/230
* https://github.com/jboss-integration/rhba-installers/pull/93
> [7.59.x] RHPAM-3897: switch to jboss-transaction-spi-jakarta

- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/LocalTaskAuditWithDeadlineTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/listener/task/CountDownTaskEventListener.java
**JIRA**: [JBPM-9895](https://issues.redhat.com/browse/JBPM-9895)
Cherry-pick from adc8aaf884bb967b2d25bb0072b4063b3ddcdf96
> [JBPM-9895] Fix flaky tests at LocalTaskAuditWithDeadlineTest

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/listener/process/NodeLeftCountDownProcessEventListener.java
**JIRA**: [JBPM-9897](https://issues.redhat.com/browse/JBPM-9897)
> [JBPM-9897] Stabilize bpmn2 tests with cron in boundary timers

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/listener/process/NodeLeftCountDownProcessEventListener.java
**JIRA**: [JBPM-9897](https://issues.redhat.com/browse/JBPM-9897)
cherry-picked from 92131f4223a7bf429a7492685b5973fa1de80d34
> [7.59.x][JBPM-9897] Stabilize bpmn2 tests with cron in boundary timers

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/elements/DataAssociationFactory.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/RuleTaskTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/DMNOutputExpression.dmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/DMNOutputExpressionProcess.bpmn
Jira: https://issues.redhat.com/browse/JBPM-9888
> [JBPM-9888] Business Rules Task to allow dynamic definition of DMN Decision Name

- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java
- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/JBPMMessages.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/HumanTaskNodeInstance.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- jbpm-flow/src/main/resources/org/jbpm/marshalling/jbpmmessages.proto
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/events/WorkflowBridgeTaskLifeCycleEventListener.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerRequestRuntimeManagerTest.java
- jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/impl/manager/SingleRuntimeManagerWithListenersTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/AdminAPIsWithListenerTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessHumanTaskTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/HumanTaskWithSuspendUntil.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-9886
> [JBPM-9886] Task suspension and automatic reactivation after defined time period in jBPM

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/HumanTaskConfigurator.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskDeadlinesServiceImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/SingletonRuntimeManager.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractDeploymentService.java
This is a draft so testing folks can try if they need to call dispose with that change. Once this is verified, we will see how to proceed "officially"
> [JBPM-9920] Trying to avoid call to dispose in tests

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/HumanTaskNodeInstance.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/events/WorkflowBridgeTaskLifeCycleEventListener.java
Jira: https://issues.redhat.com/browse/JBPM-9886
> [JBPM-9886] fix when a task is being cancel

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImplTest.java
Removing sort from named query and sorting in memory according to the
sorted list of ids
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9952)
> [JBPM-9952] Include sort  processes by variables and tasks queries

- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/jpa/hibernate/PostgreSQLLobTypeContributor.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/resources/META-INF/services/org.hibernate.boot.model.TypeContributor
Jira: https://issues.redhat.com/browse/JBPM-9939
> [JBPM-9939] Text contributor for @Lob String fields

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/AbstractAdvanceRuntimeDataServiceImplTest.java
Removing sort from named query and sorting in memory according to the sorted list of ids
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9952)
> [7.59.x] [JBPM-9952] Include sort  processes by variables and tasks queries

- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java
**[JBPM-9953](https://issues.redhat.com/browse/JBPM-9953)**: Add a test case for advanced queries when sorting by columns
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), …
> [JBPM-9953] - Add a test case for advanced queries when sorting by columns

- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/AdvanceRuntimeDataServiceImplTest.java
Backport of https://github.com/kiegroup/jbpm/pull/2064
> [7.59.x][JBPM-9953] - Add a test case for advanced queries when sorting by columns

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/AbstractAvailableJobsExecutor.java
Jira: https://issues.redhat.com/browse/JBPM-9970
> [JBPM-9970] Process instance migration does not update command data

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/test/java/org/jbpm/services/ejb/timer/EJBTimerSchedulerTest.java
**JIRA**: [JBPM-9915](https://issues.redhat.com/browse/JBPM-9915)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …
> [JBPM-9915] Add unit test for evictCache

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/util/HumanTaskHandlerHelper.java
- jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/util/HumanTaskHandlerHelperTest.java
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9974)
> [JBPM-9974] Supporting new line in mail body

- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9867)
> [7.59.x] [JBPM-9867] Changing query using union

- jbpm-flow/src/main/java/org/jbpm/process/instance/timer/TimerManager.java
Jira: https://issues.redhat.com/browse/JBPM-9912
Cherry-pick https://github.com/kiegroup/jbpm/commit/83e3c17d0aa3f4592817180de7ea646973d1c21e
> [7.59.x] [JBPM-9912] Duplicate timer creation in multi-node setup

- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/ExecutorImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/concurrent/LoadAndScheduleRequestsTask.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/jpa/ExecutorQueryServiceImpl.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/impl/jpa/JPAExecutorStoreService.java
- jbpm-services/jbpm-executor/src/main/resources/META-INF/Executor-orm.xml
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/BasicExecutorBaseTest.java
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/ExtendedExecutorTest.java
Jira: https://issues.redhat.com/browse/JBPM-9900
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/583
cherry-pick https://github.com/kiegroup/jbpm/commit/9acb37aabd3cbbd7f3cbc7dd26212ba009b40dce
> (GSS) [7.59.x] [JBPM-9900] RequestInfo.owner is null even if org.kie.executor.id is defined

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/assignment/impl/strategy/RoundRobinAssignmentStrategy.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/assignment/RoundRobinAssignmentTest.java
**JIRA**: [JBPM-9562](https://issues.redhat.com/browse/JBPM-9562)
> [JBPM-9562] RoundRobin Assignment Strategy stuck if no potentialOwners

- jbpm-human-task/jbpm-human-task-workitems/src/main/java/org/jbpm/services/task/wih/AbstractHTWorkItemHandler.java
- jbpm-human-task/jbpm-human-task-workitems/src/test/java/org/jbpm/services/task/wih/HTWorkItemHandlerBaseTest.java
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9964)
> [JBPM-9964] Avoid cast exception when priority is integer

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
**[JBPM-9977](https://issues.redhat.com/browse/JBPM-9977)**:  Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task
* https://github.com/kiegroup/droolsjbpm-integration/pull/2673
<details>
<summary>
</summary>
[build-chain …
> [JBPM-9977] - Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImplTest.java
**[JBPM-9977](https://issues.redhat.com/browse/JBPM-9977)**:  Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task
* https://github.com/kiegroup/droolsjbpm-integration/pull/2674
<details>
<summary>
</summary>
[build-chain …
> [7.59.x][JBPM-9977] - Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
Jira: https://issues.redhat.com/browse/JBPM-9988
> [JBPM-9988] Boundary timer not triggered after rollback

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
Jira: https://issues.redhat.com/browse/JBPM-9988
depends on https://github.com/kiegroup/jbpm/pull/2083
> [7.59.x] [JBPM-9988] Boundary timer not triggered after rollback

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
Jira: https://issues.redhat.com/browse/JBPM-9997
> [JBPM-9997] TimerRollbackRegressionIntegrationTest throws PSQLExceptin on PostgreSQL database

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
Jira: https://issues.redhat.com/browse/JBPM-9997
cherry-pick https://github.com/kiegroup/jbpm/commit/bf15ca77640666bff5fd1fa744495025251c33dc
> [7.59.x] [JBPM-9997] TimerRollbackRegressionIntegrationTest throws PSQLException on PostgreSQL database

- jbpm-db-scripts/src/test/filtered-resources/META-INF/persistence.xml
- jbpm-db-scripts/src/test/java/org/jbpm/persistence/types/PosgresqlTypesTest.java
- jbpm-db-scripts/src/test/java/org/jbpm/persistence/types/TestEntity.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/PersistenceUnit.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/TestPersistenceContextBase.java
Jira https://issues.redhat.com/browse/JBPM-9962
> [JBPM-9962] Text contributor for @Lob String fields / TEST CASE

- jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-10001)
> [JBPM-10001] Variable name might be null in IntermediateThrowHandler

- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/test/java/org/jbpm/services/ejb/timer/EJBTimerSchedulerTest.java
**JIRA**: [JBPM-9915](https://issues.redhat.com/browse/JBPM-9915)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …
> [7.59.x][JBPM-9915] Add unit test for evictCache

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/commands/ListTimersCommand.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/ProcessInstanceAdminServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/BPMN2-ProcessSLA.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-10004
> [JBPM-10004] GET "instances/{processInstanceId}/timers" endpoint is not returning process SLA timers

- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplAuditNoneTest.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/UserTaskServiceImplTest.java
JIRA: [JBPM-9867](https://issues.redhat.com/browse/JBPM-9867)
cherry-picked from https://github.com/kiegroup/jbpm/pull/2005
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> [7.59.x][JBPM-9867] Add parameterized test with NONE audit mode

- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/impl/admin/ProcessInstanceAdminServiceImplTest.java
- jbpm-services/jbpm-kie-services/src/test/resources/repo/processes/general/BPMN2-SuspendUntil.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-10005
> [JBPM-10005] Add suspendUntil timer to getTimers call

- jbpm-workitems/jbpm-workitems-core/pom.xml
- jbpm-workitems/jbpm-workitems-core/src/main/java/org/jbpm/process/workitem/core/AbstractLogOrThrowWorkItemHandler.java
Jira: https://issues.redhat.com/browse/JBPM-10011
> [JBPM-10011] failure database during tx in WIH causes spawn a process error handling

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/HumanTaskNodeInstance.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/SuspendTaskCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/events/TaskEventSupport.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/events/WorkflowBridgeTaskLifeCycleEventListener.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskInstanceServiceImpl.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/command/CommandBasedTaskService.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/LifeCycleManager.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/task/SynchronizedTaskService.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/UserTaskServiceImpl.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/UserTaskService.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-impl/src/main/java/org/jbpm/services/ejb/impl/TaskServiceEJBImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessHumanTaskTest.java
Jira: https://issues.redhat.com/browse/JBPM-10015 
depends on 
https://github.com/kiegroup/droolsjbpm-knowledge/pull/589
> [JBPM-10015] Allow to set suspendUntil during user task suspend operation as parameter.

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/PersistentExceptionWorkItemHandler.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/WorkItemExceptionHandlingStrategyTest.java
**JIRA**: [JBPM-10011](https://issues.redhat.com/browse/JBPM-10011)
<details>
<summary>
</summary> …
> [JBPM-10011] test for db exception at WIH shouldn't trigger subprocess

- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessInstanceManager.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/event/DefaultSignalManager.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/event/SignalManager.java
- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/DefaultProcessInstanceManager.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/ProcessPersistenceContext.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/MapBasedProcessPersistenceContext.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPAProcessInstanceManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/async/AsyncIntermediateCatchSignalTest.java
Jira: https://issues.redhat.com/browse/JBPM-10016
> [JBPM-10016] Drools/jBPM integration: high number of instances waiting for signal adversely impacts execution time

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/admin/commands/ListTimersCommand.java
Jira: https://issues.redhat.com/browse/RHPAM-4192
> [RHPAM-4192] NullPointer related to timers

- jbpm-flow/src/main/java/org/jbpm/process/instance/command/UpdateTimerCommand.java
Jira: https://issues.redhat.com/browse/JBPM-10027
> [JBPM-10027] UpdateTimerCommand should be aware of suspendUntil timer

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-cluster-jbpm-schema.sql
Jira: https://issues.redhat.com/browse/JBPM-10034
> [JBPM-10034] Add primary keys to all tables in order to fulfill MySQL clustering prerequisites

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/RuntimeDataServiceImpl.java
- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/RuntimeDataServiceImplTest.java
- jbpm-services/jbpm-services-api/src/build/revapi-config.json
- jbpm-services/jbpm-services-api/src/main/java/org/jbpm/services/api/RuntimeDataService.java
**JIRA**:
[RHPAM-4028](https://issues.redhat.com/browse/RHPAM-4028)
* https://github.com/kiegroup/process-migration-service/pull/45
> [RHPAM-4028] Add countProcessInstances query

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
**JIRA:** [BAQE-2254](https://issues.redhat.com/browse/BAQE-2254)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1923
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
> BAQE-2254 - Change revapi to check against 7.67.0.Final

- jbpm-services/jbpm-services-api/src/build/revapi-config.json
**JIRA**: [BAQE-2253](https://issues.redhat.com/browse/BAQE-2253)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1925
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
> [7.67.x] BAQE-2253 - Change revapi to check against 7.59.0.Final

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/pom.xml
- jbpm-container-test/jbpm-remote-ejb-test/jbpm-remote-ejb-test-app/pom.xml
- jbpm-workitems/jbpm-workitems-bpmn2/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-6853
Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1912
https://github.com/kiegroup/drools/pull/4261
https://github.com/kiegroup/jbpm/pull/2122
https://github.com/kiegroup/droolsjbpm-integration/pull/2736
https://github.com/kiegroup/drools-wb/pull/1541
https://github.com/kiegroup/jbpm-designer/pull/929
https://github.com/kiegroup/jbpm-wb/pull/1546
https://github.com/kiegroup/kie-wb-distributions/pull/1158
> [DROOLS-6853] jdk17 compatibility

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/LDAPUserInfoImpl.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/utils/LdapSearcher.java
**JIRA**: [JBPM-10051](https://issues.redhat.com/browse/JBPM-10051)
<details>
<summary>
</summary> …
> [JBPM-10051] Task operations fail intermittently when using LDAPUserGroupCallback

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/identity/LDAPUserInfoImpl.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/utils/LdapSearcher.java
**JIRA**: [JBPM-10051](https://issues.redhat.com/browse/JBPM-10051)
Backported from f2c7670702700ddefd68e0d8ed54a4b82ce589f3
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> [7.67.x][JBPM-10051] Task operations fail intermittently when using LDAPUserGroupCallback

- jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/DDLScriptsTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/ScriptFilter.java
**[JBPM-10055](https://issues.redhat.com/browse/JBPM-10055)**: Add test case for MySQL clustering DDL
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
> [JBPM-10055] - Add test case for MySQL clustering DDL

- jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/DDLScriptsTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/ScriptFilter.java
Backport of https://github.com/kiegroup/jbpm/pull/2137
> [7.67.x][JBPM-10055] - Add test case for MySQL clustering DDL

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithVarsDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithCustomVarsQueryMapper.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/TaskVariablesQueryServiceTest.java
Jira- https://issues.redhat.com/browse/JBPM-10053
Updated UserTaskInstanceWithCustomVarsQueryMapper with the missing column name- COLUMN_TASK_SLA_DUE_DATE
> [JBPM-10053]-UserTaskInstanceWithCustomVarsQueryMapper not returning "COLUMN_TASK_SLA_DUE_DATE"

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm-test-coverage/pom.xml
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/MockRestWorkItemHandler.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/WorkItemExceptionHandlingMultipleWIHRetryTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/ExceptionHandlingProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/ParentProcessMultipleRestWIH.bpmn
Jira: https://issues.redhat.com/browse/JBPM-10074
> [JBPM-10074] Abort fails with SessionNotFoundException for process instance with multiple REST WorkItemHandlers and RETRY strategy

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManager.java
Jira: https://issues.redhat.com/browse/JBPM-10043
> [JBPM-10043] EventEmitter return wrong "task-status" : "Ready" instead "task-status" : "Reserved"

- jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java
Jira: https://issues.redhat.com/browse/JBPM-10078
> [JBPM-10078] Non-existing [SLA]... timer with session id=0 shown when using REST API to list all available timers in migrated process instance

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerRequestRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
Jira: https://issues.redhat.com/browse/JBPM-10089
> [JBPM-10089] Orphan sessions in memory due to an exception on PerRequestRuntimeManager

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessPersistenceHumanTaskTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/ProcessWithMutableDescription.bpmn2
anytime a variable that is lable as process_description changes it will
automatically update the process description in the log.
Jira: https://issues.redhat.com/browse/RHPAM-4251
> [RHPAM-4251] "kcontext.getProcessInstance()).setDescription" is not updating the description immediately

- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/ProcessPersistenceContext.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/JPAProcessInstanceManager.java
- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/processinstance/ProcessInstanceInfo.java
- jbpm-persistence/jbpm-persistence-jpa/src/test/java/org/jbpm/persistence/session/GetProcessInstancesTest.java
Jira: https://issues.redhat.com/browse/JBPM-10048
> [JBPM-10048] Row was updated or deleted by another transaction

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
Backport of https://github.com/kiegroup/jbpm/pull/2140/commits/4420b9c3aa4a1bf21a7c755e8b57fc024f5b731d
> [7.67.x][JBPM-10063] - UserGroupCallback impl is not getting injected into kie-server when using SpringBoot - cases only

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAAuditLogService.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/LogCleanupCommand.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/LogCleanupCommandTest.java
Rescheduling command automatically if suspecting there might be more
records to delete when records per transaction is set
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> [7.67.x-blue] [JBPM-10037] LogCleanupCommnand and records per transation

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAAuditLogService.java
- jbpm-services/jbpm-executor/src/main/java/org/jbpm/executor/commands/LogCleanupCommand.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/LogCleanupCommandTest.java
Rescheduling command automatically if suspecting there might be more
records to delete when records per transaction is set
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> [7.67.x] [JBPM-10037] LogCleanupCommnand and records per transation

- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/model/UserTaskInstanceWithVarsDesc.java
- jbpm-services/jbpm-kie-services/src/main/java/org/jbpm/kie/services/impl/query/mapper/UserTaskInstanceWithCustomVarsQueryMapper.java
- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/TaskVariablesQueryServiceTest.java
Jira- https://issues.redhat.com/browse/JBPM-10053
> [7.67.x-blue]..[JBPM-10053]-UserTaskInstanceWithCustomVarsQueryMapper not returning "COLUMN_TASK_SLA_DUE_DATE"

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/AddTaskCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskInstanceServiceImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/task/HumanTaskTest.java
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [7.67.x-blue] [JBPM-10065] Triggering task activated event in a different way

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/commands/AddTaskCommand.java
- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/impl/TaskInstanceServiceImpl.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/regression/task/HumanTaskTest.java
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-10065)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …
> [7.67.x] [JBPM-10065] Triggering task activated event in a different way

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-cluster-jbpm-schema.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/rhpam-7.13-to-7.13.1.sql
**[JBPM-10087](https://issues.redhat.com/browse/JBPM-10087)**: Some ddl scripts fixed as a result of the PR https://github.com/kiegroup/jbpm/pull/2154
* https://github.com/kiegroup/jbpm/pull/2154
<details>
<summary>
</summary>
[build-chain …
> [JBPM-10087] - DDL scripts fix

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
**[JBPM-10063](https://issues.redhat.com/browse/JBPM-10063)**: UserGroupCallback impl is not getting injected into kie-server when using SpringBoot - cases only
* https://github.com/kiegroup/droolsjbpm-integration/pull/2775
<details>
<summary>
</summary>
[build-chain …
> [JBPM-10063] - UserGroupCallback impl is not getting injected into kie-server when using SpringBoot - cases only

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManager.java
Jira: https://issues.redhat.com/browse/JBPM-10043
> [7.67.x] [JBPM-10043] EventEmitter return wrong "task-status" : "Ready" instead "task-status" : "Reserved" 

- jbpm-human-task/jbpm-human-task-core/src/main/java/org/jbpm/services/task/internals/lifecycle/MVELLifeCycleManager.java
Jira: https://issues.redhat.com/browse/JBPM-10043
> [7.67.x blue] [JBPM-10043] EventEmitter return wrong "task-status" : "Ready" instead "task-status" : "Reserved"

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm-test-coverage/pom.xml
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/MockRestWorkItemHandler.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/workitem/WorkItemExceptionHandlingMultipleWIHRetryTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/ExceptionHandlingProcess.bpmn
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/workitem/ParentProcessMultipleRestWIH.bpmn
Jira: https://issues.redhat.com/browse/JBPM-10074
> [7.67.x] [JBPM-10074] Abort fails with SessionNotFoundException for process instance with multiple REST WorkItemHandlers and RETRY strategy (#2146)

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerRequestRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
Jira: https://issues.redhat.com/browse/JBPM-10089
> [7.67.x] [JBPM-10089] Orphan sessions in memory due to an exception on PerRequestRuntimeManager (#2155)

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerRequestRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
Jira: https://issues.redhat.com/browse/JBPM-10089
> [7.67.x-blue] [JBPM-10089] Orphan sessions in memory due to an exception on PerRequestRuntimeManager (#2155)

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/StageCancelTest.java
**JIRA**: [JBPM-10059](https://issues.redhat.com/browse/JBPM-10059)
<details>
<summary>
</summary> …
> [JBPM-10059] Aborted staged remains active in the process engine

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/StageCancelTest.java
**JIRA**: [JBPM-10059](https://issues.redhat.com/browse/JBPM-10059)
cherry-picked from 0835b80e2b0265c7cd7d2e15eee36e926d774c86
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …
> [7.67.x][JBPM-10059] Aborted staged remains active in the process engine

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/test/java/org/jbpm/casemgmt/impl/StageCancelTest.java
**JIRA**: [JBPM-10059](https://issues.redhat.com/browse/JBPM-10059)
cherry-picked from https://github.com/kiegroup/jbpm/commit/0835b80e2b0265c7cd7d2e15eee36e926d774c86
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) …
> [7.67.x-blue][JBPM-10059] Aborted staged remains active in the process engine

- jbpm-case-mgmt/jbpm-case-mgmt-impl/src/main/java/org/jbpm/casemgmt/impl/CaseRuntimeDataServiceImpl.java
Backport of https://github.com/kiegroup/jbpm/pull/2140/commits/c099e28a7af444d205dedc82a42b6590c29ae023
**Referenced pull requests**
* https://github.com/kiegroup/droolsjbpm-integration/pull/2806
> [7.67.x-blue][JBPM-10063] - UserGroupCallback impl is not getting injected into kie-server when using SpringBoot - cases only

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-cluster-jbpm-schema.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/rhpam-7.13-to-7.13.1.sql
**[JBPM-10087](https://issues.redhat.com/browse/JBPM-10087)**: Some ddl scripts fixed as a result of the PR https://github.com/kiegroup/jbpm/pull/2169
Depends on:
* https://github.com/kiegroup/jbpm/pull/2169
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a …
> [7.67.x][JBPM-10087] - DDL scripts fix

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/mysqlinnodb/mysql-innodb-cluster-jbpm-schema.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysql5/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/mysqlinnodb/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/oracle/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/postgresql/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver/rhpam-7.13-to-7.13.1.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/jbpm-7.71-to-7.72-TimerMappingInfo.sql
- jbpm-db-scripts/src/main/resources/db/upgrade-scripts/sqlserver2008/rhpam-7.13-to-7.13.1.sql
**[JBPM-10087](https://issues.redhat.com/browse/JBPM-10087)**: Some ddl scripts fixed as a result of the PR https://github.com/kiegroup/jbpm/pull/2170
Depends on:
* https://github.com/kiegroup/jbpm/pull/2170
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a …
> [7.67.x-blue][JBPM-10087] - DDL scripts fix

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessPersistenceHumanTaskTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/ProcessWithMutableDescription.bpmn2
Jira: https://issues.redhat.com/browse/RHPAM-4251
> [7.67.x] [RHPAM-4251] "kcontext.getProcessInstance()).setDescription" is not updating the description immediately (#2156)

- jbpm-audit/src/main/java/org/jbpm/process/audit/JPAWorkingMemoryDbLogger.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/task/ProcessPersistenceHumanTaskTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/task/ProcessWithMutableDescription.bpmn2
Jira: https://issues.redhat.com/browse/RHPAM-4251
> [7.67.x-blue] [RHPAM-4251] "kcontext.getProcessInstance()).setDescription" is not updating the description immediately (#2156)

- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/audit/JPATaskLifeCycleEventListener.java
- jbpm-human-task/jbpm-human-task-audit/src/test/java/org/jbpm/services/task/audit/service/TaskAuditBaseTest.java
- jbpm-human-task/jbpm-human-task-jpa/src/main/java/org/jbpm/services/task/impl/model/TaskImpl.java
**JIRA**: _(https://issues.redhat.com/browse/RHPAM-4445)_
> [7.67.x] [RHPAM-4445] Unable to update the task description with long string(more than 255 chars)

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/mapper/InMemoryMapper.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
**JIRA**: https://issues.redhat.com/browse/JBPM-10106
**referenced Pull Requests**: https://github.com/kiegroup/jbpm/pull/2184
> [JBPM-10106] Orphaned records in the sessionInfo table

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/tx/ETransactionTest.java
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/org/jbpm/test/container/archive/ejbservices/assets/TxProcess.bpmn2
@elguardian this stabilizes the test mostly for the productized builds.
**JIRA**: [JBPM-10123](https://issues.redhat.com/browse/JBPM-10123)
backport of https://github.com/kiegroup/jbpm/pull/2216
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …
> JBPM-10123 - Stabilize ETransactionTest#testTimer() test

- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/RawWriterInterceptor.java
- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/RawXMLStreamWriter.java
- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
**JIRA**: [JBPM-10125](https://issues.redhat.com/browse/JBPM-10125)
<details>
<summary>
</summary> …
> [JBPM-10125] Write raw content to avoid escape chars in SOAP headers

- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/CancelNodeInstanceAction.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/CompositeNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/event/SignalEventTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/TestSignalClose.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-10129
> [JBPM-10129] Signals inside a multinode process are not captured correctly by same process

- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/CancelNodeInstanceAction.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/CompositeNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/event/SignalEventTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/TestSignalClose.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-10129
chery-pìck https://github.com/kiegroup/jbpm/commit/5ff4a6f0bfb3b98661e819487099c539848752aa
> [7.67.x] [JBPM-10129] Signals inside a multinode process are not captured correctly by same process (#2228)

- jbpm-flow/src/main/java/org/jbpm/process/instance/impl/CancelNodeInstanceAction.java
- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/CompositeNodeInstance.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/event/SignalEventTest.java
- jbpm-test-coverage/src/test/resources/org/jbpm/test/functional/event/TestSignalClose.bpmn2
Jira: https://issues.redhat.com/browse/JBPM-10129
chery-pìck https://github.com/kiegroup/jbpm/commit/5ff4a6f0bfb3b98661e819487099c539848752aa
> [7.67.x-blue] [JBPM-10129] Signals inside a multinode process are not captured correctly by same process (#2228)

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/mapper/InMemoryMapper.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
Jira: https://issues.redhat.com/browse/RHPAM-4403
cherry-pick
https://github.com/kiegroup/jbpm/commit/816e9b5089e4d5b9e7aa9a02a5f4d66023b5ba75
> [7.67.x] [JBPM-10106] Orphaned records in the sessionInfo table (#2213)

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/RuntimeEngineImpl.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/mapper/InMemoryMapper.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManagerTest.java
Jira: https://issues.redhat.com/browse/RHPAM-4403
cherry-pick
https://github.com/kiegroup/jbpm/commit/816e9b5089e4d5b9e7aa9a02a5f4d66023b5ba75
> [7.67.x-blue] [JBPM-10106] Orphaned records in the sessionInfo table (#2213)

- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/RawWriterInterceptor.java
- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/RawXMLStreamWriter.java
- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
**JIRA**: [RHPAM-4501](https://issues.redhat.com/browse/RHPAM-4501)
cherrypicked and squashed from 82a17fc8a110f1e27d67e3564a98234ec4834de2 and d35a658d2af0118c0c77ddaf1ee9772886bc6eaf
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be …
> [7.67.x][JBPM-10125] Write raw content to avoid escape chars in SOAP headers

- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/RawWriterInterceptor.java
- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/RawXMLStreamWriter.java
- jbpm-workitems/jbpm-workitems-webservice/src/main/java/org/jbpm/process/workitem/webservice/WebServiceWorkItemHandler.java
JIRA: [RHPAM-4501](https://issues.redhat.com/browse/RHPAM-4501)
cherrypicked and squashed from https://github.com/kiegroup/jbpm/commit/82a17fc8a110f1e27d67e3564a98234ec4834de2 and https://github.com/kiegroup/jbpm/commit/d35a658d2af0118c0c77ddaf1ee9772886bc6eaf
<details>
<summary>
</summary>
[build-chain …
> [7.67.x-blue][JBPM-10125] Write raw content to avoid escape chars in SOAP headers

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/error/DefaultExecutionErrorStorage.java
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> [JBPM-10142] Improving clean up

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManager.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManagerTest.java
- jbpm-runtime-manager/src/test/resources/signal-test.bpmn
**JIRA**: https://issues.redhat.com/browse/RHPAM-4603
> [7.67.x] JBPM-10139: Avoid duplicate entries in PerCaseRuntimeManager.local map to avoid multiple signals being sent (#2235)

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManager.java
- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/PerCaseRuntimeManagerTest.java
- jbpm-runtime-manager/src/test/resources/signal-test.bpmn
**JIRA**: https://issues.redhat.com/browse/RHPAM-4603
> [7.67.x-blue] JBPM-10139: Avoid duplicate entries in PerCaseRuntimeManager.local map to avoid multiple signals being sent (#2235)

- .github/workflows/pull_request.yml
- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/java/org/jbpm/test/container/test/ejbservices/ejbcompl/EThreadInfoTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/LDAPBaseTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/java/org/jbpm/services/task/identity/LDAPUserGroupCallbackImplTest.java
- jbpm-human-task/jbpm-human-task-core/src/test/resources/jbpm.usergroup.callback.properties
- jbpm-services/jbpm-executor/src/test/java/org/jbpm/executor/impl/wih/CleanupExecutionErrorCommandWithProcessTest.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/LdapJbpmTestCase.java
- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/jobexec/CaseLogCleanupCommandTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/listener/process/NodeLeftCountDownProcessEventListener.java
- jbpm-test-util/src/main/java/org/jbpm/test/util/SocketUtils.java
Cherry pick changes from main branch
> 7.67.x fixes

- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/pom.xml
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/DefaultESInstanceViewTransformer.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/ElasticSearchEventEmitter.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/java/org/jbpm/event/emitters/elasticsearch/ElasticsearchEventEmitterProcessTest.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/child.bpmn
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/parent.bpmn
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/testTaskInstanceThroughEmitter.json
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/model/CaseInstanceView.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/model/ProcessInstanceView.java
**JIRA**: 
[JBPM-10143](https://issues.redhat.com/browse/JBPM-10143)
The PR addresses two issues:
1. Events getting "swallowed" (eg. process start and end events emitted in a single transaction)
2. Elasticsearch bulk API returning 400 for "update" events
> [JBPM-10143] Ensure all events are sent to Elasticsearch

- jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
JIRA: https://issues.redhat.com/browse/JBPM-10145
> [JBPM-10145] Handle SessionNotFoundException when exception process has already ended

- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
**JIRA**: _(JBPM-10150)_ 
[link](https://issues.redhat.com/browse/JBPM-10150)
<details>
<summary>
Updated the log statement
</summary>
</details>
<details>
<summary>
</summary>
</details>
<details> …
> JBPM-10150: Updated the log statement

- jbpm-test-coverage/src/test/java/org/jbpm/test/functional/CorrelationKeyTest.java
**JIRA**: [JBPM-10156](https://issues.redhat.com/browse/JBPM-10156)
<details>
<summary>
</summary> …
> [JBPM-10156] Test failures after changing log with persist (CK)

- jbpm-services/jbpm-kie-services/src/main/resources/META-INF/Servicesorm.xml
As proposed by @martinweiler  in JIRA description
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9946)
> [JBPM-9946] servicesorm.xml validation failure

- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/pom.xml
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/DefaultESInstanceViewTransformer.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/ElasticSearchEventEmitter.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/java/org/jbpm/event/emitters/elasticsearch/ElasticsearchEventEmitterProcessTest.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/child.bpmn
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/parent.bpmn
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/testTaskInstanceThroughEmitter.json
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/model/CaseInstanceView.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/model/ProcessInstanceView.java
* [JBPM-10143] Ensure ElasticSearch data contains events from parent/child process hierarchy
* [JBPM-10143] Add test case
> [7.67.x] [JBPM-10143] Ensure all events are sent to Elasticsearch (#2247)

- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/pom.xml
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/DefaultESInstanceViewTransformer.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/main/java/org/jbpm/event/emitters/elasticsearch/ElasticSearchEventEmitter.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/java/org/jbpm/event/emitters/elasticsearch/ElasticsearchEventEmitterProcessTest.java
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/child.bpmn
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/parent.bpmn
- jbpm-event-emitters/jbpm-event-emitters-elasticsearch/src/test/resources/testTaskInstanceThroughEmitter.json
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/model/CaseInstanceView.java
- jbpm-persistence/jbpm-persistence-api/src/main/java/org/jbpm/persistence/api/integration/model/ProcessInstanceView.java
Jira: https://jsw.ibm.com/browse/DBACLD-75257
cherry-pick from https://github.com/kiegroup/jbpm/commit/6387a541ff27b65dba037861f6aeab99599dd8ee
> [7.67.x-blue] [JBPM-10143] Ensure all events are sent to Elasticsearch (#2247)

- jbpm-container-test/jbpm-in-container-test/jbpm-container-test-suite/src/test/resources/persistence.xml
- jbpm-container-test/pom.xml
**JIRA**: [JBPM-10186](https://issues.redhat.com/browse/JBPM-10186)
<details>
<summary>
</summary> …
> [JBPM-10186] drop-script-source for h2 test must be absolute path

- jbpm-workitems/jbpm-workitems-rest/pom.xml
**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-4734
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2324
* https://github.com/kiegroup/jbpm/pull/2315
* https://github.com/kiegroup/jbpm-work-items/pull/288
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds …
> [RHPAM-4734] [CVE-2023-33201] bouncycastle upgraded to 1.74

- jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/SLAComplianceTest.java
**JIRA**: [JBPM-10191](https://issues.redhat.com/browse/JBPM-10191)
<details>
<summary>
</summary> …
> JBPM-10191 - Enhance update process timer SLAComplianceTest

- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/TimerMigrationManagerTest.java
- jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-SLAOnTask-v1.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-SLAProcess-v1.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-SLAOnTask-v2.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-SLAProcess-v2.bpmn2
**JIRA**:  [JBPM-10192](https://issues.redhat.com/browse/JBPM-10192)
<details>
<summary>
</summary> …
> [JBPM-10192] Tests for SLA timers are not migrated after migrating process instances

- jbpm-human-task/jbpm-human-task-audit/src/main/java/org/jbpm/services/task/assignment/impl/TotalCompletionTimeLoadCalculator.java
**JIRA**: [JBPM-10194](https://issues.redhat.com/browse/JBPM-10194)
<details>
<summary>
</summary> …
> [JBPM-10194] Fix TASK_AVG_DURATION query for postgres

- jbpm-db-scripts/src/test/filtered-resources/META-INF/persistence.xml
- jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/DDLScriptsTest.java
- jbpm-db-scripts/src/test/java/org/jbpm/persistence/scripts/UpgradeScriptsTest.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/ScriptsBase.java
- jbpm-test-util/src/main/java/org/jbpm/test/persistence/scripts/util/ScriptFilter.java
**JIRA**: [JBPM-10195](https://issues.redhat.com/browse/JBPM-10195)
<details>
<summary>
</summary> …
> [JBPM-10195] Schema validation exception when validating Spring Boot DDL Scripts for Oracle and PostgreSQL

- jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNode.java
issue : https://github.com/kiegroup/jbpm/pull/2352/files
> [incubator-kie-issues-646] fix recursion

- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/TimerMigrationManagerTest.java
- jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-SLAOnTask-v1.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-SLAProcess-v1.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-SLAOnTask-v2.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-SLAProcess-v2.bpmn2
**JIRA**: [JBPM-10192](https://issues.redhat.com/browse/JBPM-10192)
<details>
<summary>
</summary> …
> [7.67.x-blue][JBPM-10192] SLA timers are not migrated after migrating process instances

- jbpm-runtime-manager/src/test/java/org/jbpm/runtime/manager/impl/migration/TimerMigrationManagerTest.java
- jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-SLAOnTask-v1.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v1/BPMN2-SLAProcess-v1.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-SLAOnTask-v2.bpmn2
- jbpm-runtime-manager/src/test/resources/migration/v2/BPMN2-SLAProcess-v2.bpmn2
**JIRA**: [JBPM-10192](https://issues.redhat.com/browse/JBPM-10192)
<details>
<summary>
</summary> …
> [7.67.x][JBPM-10192] SLA timers are not migrated after migrating process instances

- jbpm-flow/src/main/java/org/jbpm/process/instance/command/UpdateTimerCommand.java
[JBPM-10198](https://issues.redhat.com/browse/JBPM-10198)
> [JBPM-10198] delete correct old timer rescheduling a timer

- jbpm-services/jbpm-kie-services/src/test/java/org/jbpm/kie/services/test/QueryServiceImplTest.java
This is a test to check how the filters work in kie server.
> test filter with in queries

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/PerProcessInstanceRuntimeManager.java
issue : https://github.com/kiegroup/jbpm/pull/2403
> [incubator-kie-issues-1016] avoid race condition for awaiting signals and process instance completed (#2403) [7.67.x-blue]

- jbpm-persistence/jbpm-persistence-jpa/src/main/java/org/jbpm/persistence/JpaProcessPersistenceContext.java
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-10228)
> [JBPM-10228] Fixing wrong flush call

- jbpm-db-scripts/src/main/resources/db/ddl-scripts/db2/db2-jbpm-schema.sql
Integrate DB2 ddl-scripts with creation of required sequences
JIRA: [JBPM-10226](https://issues.redhat.com/browse/JBPM-10226)
> [JBPM-10226] Integrate DB2 ddl-scripts with creation of required sequences

- jbpm-installer/src/main/resources/db/mysql_module.xml
- jbpm-xes/pom.xml
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2488
* https://github.com/kiegroup/droolsjbpm-integration/pull/3063
* https://github.com/kiegroup/appformer/pull/1422
* https://github.com/kiegroup/jbpm/pull/2438
* https://github.com/kiegroup/kie-wb-distributions/pull/1245
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/649
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
> [7.67.x-blue] Updating mysql connector gav

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/TimerMappingInfo.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
See https://issues.redhat.com/browse/JBPM-10251 for details
> [JBPM-10251] Update TimerMappingInfo entry if EjbSchedulerService.internalSchedule is called

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/TimerMappingInfo.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
See https://issues.redhat.com/browse/JBPM-10251 for details
This is the 7.67.x-blue PR equivalent to https://github.com/kiegroup/jbpm/pull/2458 on main
> [7.67.x-blue][JBPM-10251] Update TimerMappingInfo entry if EjbSchedulerService.internalSchedule is called

- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/AbstractRuntimeManager.java
- jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/TimerMappingInfo.java
- jbpm-services/jbpm-services-ejb/jbpm-services-ejb-timer/src/main/java/org/jbpm/services/ejb/timer/EjbSchedulerService.java
- jbpm-workitems/jbpm-workitems-rest/pom.xml
[7.67.x-blue] Upgrade netty handler version to 4.1.118.Final
> [7.67.x-blue] Upgrade netty handler version to 4.1.118.Final 

- jbpm-container-test/jbpm-remote-ejb-test/pom.xml
- jbpm-container-test/pom.xml
Ensemble PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2589
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds …
> DBACLD-177443: update-jboss-ejb-client

- jbpm-container-test/jbpm-in-container-test/jbpm-container-integration-deps/rest/pom.xml
Related PRs : 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2560
https://github.com/kiegroup/jbpm-work-items/pull/314
https://github.com/kiegroup/kie-wb-distributions/pull/1247
https://github.com/kiegroup/appformer/pull/1442
https://github.com/kiegroup/droolsjbpm-integration/pull/3079
> [7.67.x-blue] Update resteasy-jackson-provider
